package guard

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/gomoni/snug/test/modroot"
)

// ── every committed *.bwrap.txt fixture sizes its own tmpfs ─────────────────
//
// internal/policy/tmpfssize_test.go's TestEveryTmpfsInTheArgvCarriesASize
// guards the GENERATOR: an unsized tmpfs falls back to the kernel default,
// half of physical RAM, on every tmpfs this sandbox creates — a private
// build directory that can fill the whole machine. That test proves
// BwrapArgs never emits one; it says nothing about the committed bytes a
// reviewer actually reads in a golden diff (CLAUDE.md: "a change to a golden
// file is a change to the security posture", read by a human, not
// regenerated and trusted). This sweep is the same property asserted over
// the FILES, so a golden file hand-edited or regenerated by a stale binary
// is still caught.
//
// goldenFormat (bwrap_test.go) puts one flag and its own operands per line,
// so "--size 1073741824" and "--tmpfs /tmp" are each a single line; the
// property is exactly: no line naming --tmpfs is missing a --size line
// immediately above it.

// tmpfsLinesWithoutPrecedingSize returns the 1-based line numbers of every
// --tmpfs line in body not immediately preceded by a --size line, and the
// total number of --tmpfs lines seen (the walk's own positive control).
func tmpfsLinesWithoutPrecedingSize(body string) (bad []int, tmpfsSeen int) {
	lines := strings.Split(body, "\n")
	for i, line := range lines {
		if line != "--tmpfs" && !strings.HasPrefix(line, "--tmpfs ") {
			continue
		}
		tmpfsSeen++
		if i == 0 || !strings.HasPrefix(lines[i-1], "--size ") {
			bad = append(bad, i+1)
		}
	}
	return bad, tmpfsSeen
}

// TestTmpfsLinesWithoutPrecedingSizeSeesEverySpelling is the control on the
// line-scan detector above.
func TestTmpfsLinesWithoutPrecedingSizeSeesEverySpelling(t *testing.T) {
	sized := "--proc /proc\n--size 1073741824\n--tmpfs /tmp\n--ro-bind /usr /usr\n"
	if bad, seen := tmpfsLinesWithoutPrecedingSize(sized); len(bad) != 0 || seen != 1 {
		t.Errorf("a --tmpfs immediately preceded by --size was flagged: bad=%v seen=%d", bad, seen)
	}

	unsized := "--proc /proc\n--tmpfs /tmp\n--ro-bind /usr /usr\n"
	if bad, seen := tmpfsLinesWithoutPrecedingSize(unsized); len(bad) != 1 || seen != 1 {
		t.Errorf("a --tmpfs with no preceding --size was NOT flagged: bad=%v seen=%d", bad, seen)
	}

	first := "--tmpfs /tmp\n--size 1073741824\n"
	if bad, seen := tmpfsLinesWithoutPrecedingSize(first); len(bad) != 1 || seen != 1 {
		t.Errorf("a --tmpfs on the FIRST line (nothing can precede it) was not flagged: bad=%v seen=%d", bad, seen)
	}
}

// TestEveryCommittedTmpfsFixtureHasAPrecedingSize is the sweep, over the
// committed bytes rather than over BwrapArgs's output.
func TestEveryCommittedTmpfsFixtureHasAPrecedingSize(t *testing.T) {
	root, err := modroot.Find()
	if err != nil {
		t.Fatal(err)
	}
	out, err := exec.Command("git", "-C", root, "ls-files").Output()
	if err != nil {
		t.Fatalf("git -C %s ls-files: %v", root, err)
	}
	var files []string
	for _, rel := range strings.Split(string(out), "\n") {
		if rel != "" && strings.HasSuffix(rel, ".bwrap.txt") {
			files = append(files, rel)
		}
	}
	sort.Strings(files)

	// POSITIVE CONTROL: the fixture set itself must be non-empty, or the
	// property below is vacuous.
	if len(files) == 0 {
		t.Fatal("`git ls-files` found no committed *.bwrap.txt fixture, so this sweep checked nothing")
	}

	var bad []string
	tmpfsSeen := 0
	for _, rel := range files {
		body, rerr := os.ReadFile(filepath.Join(root, rel))
		if rerr != nil {
			if errors.Is(rerr, fs.ErrNotExist) {
				// Vanished between `git ls-files` and the read; see
				// TestEverySourceSweepToleratesAVanishedEntry for why every
				// such walk in this module carries this exact tolerance.
				continue
			}
			t.Fatalf("reading %s: %v", rel, rerr)
		}
		lines, seen := tmpfsLinesWithoutPrecedingSize(string(body))
		tmpfsSeen += seen
		for _, line := range lines {
			bad = append(bad, fmt.Sprintf("%s:%d", rel, line))
		}
	}

	// POSITIVE CONTROL: at least one --tmpfs token must actually have been
	// read, or the property "none is unsized" is true of an empty set.
	if tmpfsSeen == 0 {
		t.Fatal("no --tmpfs token was found across any committed *.bwrap.txt fixture, so this " +
			"sweep measures nothing")
	}

	for _, b := range bad {
		t.Errorf("%s: --tmpfs with no --size line immediately above it. An unsized tmpfs falls "+
			"back to the kernel default, half of physical RAM — see "+
			"internal/policy/tmpfssize_test.go, which guards the generator; this fixture is what "+
			"a reviewer actually reads.", b)
	}
}
