package policy

import "fmt"

// browserBridgeShim is staged whenever a profile sets login =
// ["claude"] and Resolve does not refuse it. Every line is load-bearing,
// same discipline as httpDoorShim: this script is the only client the bridge
// can count on (`/bin/sh` — curl and python3 are not guaranteed by @sys, and
// sh cannot speak AF_UNIX, which is why the transport is a FIFO and not a
// third staged socket), and it makes no decision of its own. The predicate
// that decides whether the URL it hands over is the Claude login snug will
// open lives in internal/loginbridge, on the host side of the FIFO — this
// script cannot be the security boundary, because anything in the sandbox can
// write BrowserFIFOGuest directly without ever running it.
const browserBridgeShim = `#!/bin/sh
# Generated by snug because a profile in this selection set
# login = ["claude"]. Hands ONE argument to snug over the FIFO snug
# bound at /snug/browser.fifo; snug alone decides whether it is the Claude
# login it will open in your browser. This script opens nothing.
[ "$#" -eq 1 ] || { echo "snug-browser: expected exactly one URL" >&2; exit 2; }
printf '%s\n' "$1" > /snug/browser.fifo
`

// BrowserBridgeShellError refuses login = ["claude"] on a selection with
// no shell inside.
//
// The shim BROWSER points at is a `/bin/sh` script for the same reason the
// http door's descriptor handover is (HTTPDoorShellError): shellIsVisible is
// the only thing internal/policy can check before a sandbox exists, and a
// selection that fails it would otherwise fail LATER, when Claude Code execs
// $BROWSER and gets ENOENT instead of a login prompt.
func BrowserBridgeShellError(shell string) error {
	return fmt.Errorf("login = [\"claude\"] points BROWSER at a %s script, but this "+
		"selection has no %s inside:\n"+
		"       the shim snug stages hands the sandbox's login URL to snug over a FIFO, and that "+
		"needs\n"+
		"       a shell to run. Add the '@sys' profile, which grants %s — or drop login from "+
		"the\n"+
		"       profile.",
		VisibleText(shell), VisibleText(shell), VisibleText(shell))
}
