package policy

import (
	"strings"
	"testing"
)

// SNUG'S OWN GENERATED CONTENT MUST NEVER BE WRITTEN ONTO THE HOST.
//
// The property, stated once so the cases below can be read against it:
//
//	for every resolved policy, no KindData mount's guest path resolves
//	through a writable host bind.
//
// It is issue #186, and it is the rarest kind of finding here: not a payload
// doing something, not a grant being exceeded, but SNUG writing, during setup,
// before the sandbox is useful. A profile granted rw on a tree, snug generated a
// file at a path inside it, and bwrap's `--file` copied the generated content
// onto the host's file. A real ~/.claude lost its settings.json to the allowlist
// output, its .credentials.json to the staged copy (refreshToken gone), and
// gained a 0-byte read-only CLAUDE.md.
//
// Every mitigation aimed at the sandboxed process — seccomp, the fd sweep,
// --remount-ro / — is irrelevant to it, because the writer is on the other side.
//
// The cases are deliberately not all @claude. KindData carries /etc/resolv.conf
// and the identity files too, and a fix keyed to the three files that happened
// to be damaged would close one instance of a general defect.

// generated authors a KindData mount the way snug itself does — through
// Policy.Replace, which is what sets Authored. That matters: Authored is exactly
// the field rejectMasking exempts, and this rule exists because that exemption's
// reach does not cover a profile STEERING where the authored mount lands.
func generated(p *Policy, guest string, access Access) {
	p.Replace(Mount{
		Guest:   guest,
		Kind:    KindData,
		Access:  access,
		Content: Secret("generated by snug\n"),
	})
}

// bind puts a profile's grant into an already-resolved policy. Post-resolution
// mutation is the honest fixture here: the defect is about what Validate does
// with a policy, and building it through two profiles would test Resolve's
// merge on the way to testing this.
func bind(p *Policy, guest, host string, access Access) {
	p.Mounts[guest] = Mount{
		Guest: guest, Kind: KindBind, Host: host, Access: access, From: []string{"evil"},
	}
}

func tmpfsAt(p *Policy, guest string) {
	p.Mounts[guest] = Mount{Guest: guest, Kind: KindTmpfs, Access: AccessRW, From: []string{"evil"}}
}

// TestGeneratedFileOverAWritableHostBindIsRefused is the regression. Each row
// that must be refused names a DIFFERENT generator, because the defect is not
// @claude's.
func TestGeneratedFileOverAWritableHostBindIsRefused(t *testing.T) {
	for _, tc := range []struct {
		name  string
		build func(p *Policy)
		want  []string // substrings the refusal must carry; empty means "must not refuse"
	}{
		{
			// The shape that really happened.
			name: "claude settings under an rw grant on ~/.claude",
			build: func(p *Policy) {
				bind(p, "/home/u/.claude", "/home/u/.claude", AccessRW)
				generated(p, "/home/u/.claude/settings.json", AccessRW)
			},
			want: []string{"evil", "/home/u/.claude", "settings.json", "on the HOST", "Fix:"},
		},
		{
			// A generated file snug authors READ-ONLY is refused too, and the
			// reason is measured rather than assumed: bwrap's --ro-bind-data
			// calls ensure_file, which CREATES the destination before mounting
			// over it. That is how a 0-byte -r--r--r-- CLAUDE.md appeared in the
			// host's ~/.claude, in a directory nothing had otherwise touched.
			name: "a read-only generated file is still created on the host",
			build: func(p *Policy) {
				bind(p, "/home/u/.claude", "/home/u/.claude", AccessRW)
				generated(p, "/home/u/.claude/CLAUDE.md", AccessRO)
			},
			want: []string{"CLAUDE.md", "on the HOST"},
		},
		{
			// NOT @claude. The identity band generates here, and a profile
			// granting rw over the ssh directory is the same defect writing
			// snug's known_hosts onto the host's.
			name: "an identity file under an rw grant on ~/.ssh",
			build: func(p *Policy) {
				bind(p, "/home/u/.ssh", "/home/u/.ssh", AccessRW)
				generated(p, "/home/u/.ssh/known_hosts", AccessRO)
			},
			want: []string{"/home/u/.ssh", "known_hosts", "on the HOST"},
		},
		{
			// Nor is it home-rooted. /etc/resolv.conf is generated on every
			// networked run, and rw on /etc reaches it.
			name: "resolv.conf under an rw grant on /etc",
			build: func(p *Policy) {
				bind(p, "/etc", "/etc", AccessRW)
				generated(p, "/etc/resolv.conf", AccessRW)
			},
			want: []string{"/etc/resolv.conf", "on the HOST"},
		},
		{
			// The grant does not have to be the file's own directory. An
			// ancestor resolves it just as well, which is the direction
			// rejectMasking's first version missed on its own rule.
			//
			// On a neutral tree rather than {home}: an rw bind over the
			// ephemeral home would be refused by rejectMasking first (it covers
			// @home's own tmpfs children), and a fixture that trips a different
			// rule proves nothing about this one.
			name: "an ancestor grant two levels up",
			build: func(p *Policy) {
				bind(p, "/srv/app", "/srv/app", AccessRW)
				generated(p, "/srv/app/deep/gen.conf", AccessRW)
			},
			want: []string{"/srv/app", "gen.conf", "on the HOST"},
		},

		{
			// Fail closed on a shape nobody produces. A KindBind with no host
			// source is malformed rather than legitimate, and the rule refuses
			// it: "I cannot tell where this resolves" must give the same answer
			// as "it resolves onto the host". This case exists because the
			// earlier skip-if-empty branch could not be mutation-tested — no
			// break of it made anything fail, which is how an unreachable-looking
			// fail-open branch stays in a security check.
			name: "a malformed writable bind with no host source still refuses",
			build: func(p *Policy) {
				p.Mounts["/srv/app"] = Mount{
					Guest: "/srv/app", Kind: KindBind, Access: AccessRW, From: []string{"evil"},
				}
				generated(p, "/srv/app/gen.conf", AccessRW)
			},
			want: []string{"/srv/app", "gen.conf", "on the HOST"},
		},

		// ── Must NOT refuse ──────────────────────────────────────────────
		{
			// The normal case, and the reason this rule cannot simply refuse
			// every KindData with a bind anywhere above it: everything snug
			// generates into the ephemeral $HOME sits inside @home's tmpfs.
			name:  "a generated file on the ephemeral home tmpfs",
			build: func(p *Policy) { generated(p, "/home/u/.gitconfig", AccessRW) },
		},
		{
			// A READ-ONLY bind covering a generated path is left to bwrap,
			// which fails loudly by itself — "Can't create file …: Read-only
			// file system" is the error that identified this whole mechanism.
			// A second refusal here would be a rule with no failure to prevent.
			name: "a read-only bind is bwrap's to refuse, loudly",
			build: func(p *Policy) {
				bind(p, "/home/u/.claude", "/home/u/.claude", AccessRO)
				generated(p, "/home/u/.claude/settings.json", AccessRW)
			},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			p := mustResolveDefaults(t)
			tc.build(p)
			err := p.Validate(newFakeEnv())

			if len(tc.want) == 0 {
				if err != nil {
					t.Fatalf("refused a policy that writes nothing to the host: %v", err)
				}
				return
			}
			if err == nil {
				t.Fatal("accepted a policy in which snug would write its generated content onto " +
					"the HOST. Nothing escapes and no grant is exceeded — snug itself does the " +
					"writing, during setup, and there is no undo (issue #186)")
			}
			for _, want := range tc.want {
				if !strings.Contains(err.Error(), want) {
					t.Errorf("refusal does not name %q, so it does not tell anyone which line to "+
						"delete:\n%v", want, err)
				}
			}
		})
	}
}

// TestTheGeneratedOntoHostRuleNamesBothGrants is the "errors name the fix"
// half, asserted separately because it is the part a later message edit would
// quietly drop. The refusal has to name a genuine CHOICE between two grants —
// the rw one and the profile that generates at that path — since snug cannot
// know which the human meant, and picking one silently would be a downgrade.
func TestTheGeneratedOntoHostRuleNamesBothGrants(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/home/u/.claude", "/host/real/.claude", AccessRW)
	generated(p, "/home/u/.claude/settings.json", AccessRW)

	err := p.Validate(newFakeEnv())
	if err == nil {
		t.Fatal("accepted the reproduction from issue #186")
	}
	for _, want := range []string{
		"evil",                             // the profile that granted rw
		"/host/real/.claude/settings.json", // the HOST file that would be overwritten
		"drop the rw grant",                // one of the two ways out
		"deselect",                         // the other
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not carry %q:\n%v", want, err)
		}
	}
}

// TestTheDeepestMountDecidesWhichCoverIsJudged pins the half of the rule that
// cannot be reached through Validate, and says why it still has to hold.
//
// The rule asks the DEEPEST mount covering the generated path, the same relation
// join is keyed on. Walking every ancestor instead would look more thorough and
// would be wrong: a tmpfs between the writable bind and the file means the write
// lands on the tmpfs, and refusing there is a false positive — the kind that
// teaches the next person to delete the check rather than fix it.
//
// That shape is unreachable in a real policy, because a tmpfs nested inside a
// bind is masking and rejectMasking refuses it first. Both halves are asserted
// here so the reason stays visible: the predicate says "fine", the policy is
// still refused, and neither fact is evidence about the other.
func TestTheDeepestMountDecidesWhichCoverIsJudged(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/srv/app", "/srv/app", AccessRW)
	tmpfsAt(p, "/srv/app/deep")
	generated(p, "/srv/app/deep/gen.conf", AccessRW)

	if err := p.rejectGeneratedOntoHost(); err != nil {
		t.Fatalf("the generated file resolves onto a tmpfs, not the host, and was still "+
			"refused — a rule that walks past the deepest cover reports writes that do not "+
			"happen:\n%v", err)
	}
	if err := p.Validate(newFakeEnv()); err == nil {
		t.Fatal("a tmpfs nested inside a bind was accepted by Validate; if rejectMasking " +
			"stopped refusing that shape, this rule's deepest-cover reading becomes reachable " +
			"and needs its own end-to-end case")
	}
}
