package policy

import (
	"io/fs"
	"strings"
	"syscall"
	"testing"
)

// SNUG'S OWN GENERATED CONTENT MUST NEVER BE WRITTEN ONTO THE HOST.
//
// The property, stated once so the cases below can be read against it:
//
//	for every resolved policy, no KindData mount's guest path resolves
//	through a writable host bind.
//
// It is issue #186, and it is the rarest kind of finding here: not a payload
// doing something, not a grant being exceeded, but SNUG writing, during setup,
// before the sandbox is useful. A profile granted rw on a tree, snug generated a
// file at a path inside it, and bwrap's `--file` copied the generated content
// onto the host's file. A real ~/.claude lost its settings.json to the allowlist
// output, its .credentials.json to the staged copy (refreshToken gone), and
// gained a 0-byte read-only CLAUDE.md.
//
// Every mitigation aimed at the sandboxed process — seccomp, the fd sweep,
// --remount-ro / — is irrelevant to it, because the writer is on the other side.
//
// The cases are deliberately not all @claude. KindData carries /etc/resolv.conf
// and the identity files too, and a fix keyed to the three files that happened
// to be damaged would close one instance of a general defect.

// generated authors a KindData mount the way snug itself does — through
// Policy.Replace, which is what sets Authored. That matters: Authored is exactly
// the field rejectMasking exempts, and this rule exists because that exemption's
// reach does not cover a profile STEERING where the authored mount lands.
func generated(p *Policy, guest string, access Access) {
	p.Replace(Mount{
		Guest:   guest,
		Kind:    KindData,
		Access:  access,
		Content: Secret("generated by snug\n"),
		// From, because every generated mount snug really authors carries one:
		// "(snug)" for /etc/resolv.conf and the procfs replacements, "identity:…"
		// for the identity files, "@claude" for the plugin manifest. The fixture
		// left it empty, and the refusal it steers renders provenance — which
		// showed up as `deselect , which generates at …` the moment the text
		// reached a golden. A fixture that a message reads has to look like the
		// mounts that message is written for.
		From: []string{"(snug)"},
	})
}

// bind puts a profile's grant into an already-resolved policy. Post-resolution
// mutation is the honest fixture here: the defect is about what Validate does
// with a policy, and building it through two profiles would test Resolve's
// merge on the way to testing this.
func bind(p *Policy, guest, host string, access Access) {
	p.Mounts[guest] = Mount{
		Guest: guest, Kind: KindBind, Host: host, Access: access, From: []string{"evil"},
	}
}

func tmpfsAt(p *Policy, guest string) {
	p.Mounts[guest] = Mount{Guest: guest, Kind: KindTmpfs, Access: AccessRW, From: []string{"evil"}}
}

// TestGeneratedFileOverAWritableHostBindIsRefused is the regression. Each row
// that must be refused names a DIFFERENT generator, because the defect is not
// @claude's.
func TestGeneratedFileOverAWritableHostBindIsRefused(t *testing.T) {
	for _, tc := range []struct {
		name  string
		build func(p *Policy)
		want  []string // substrings the refusal must carry; empty means "must not refuse"
	}{
		{
			// The shape that really happened.
			name: "claude settings under an rw grant on ~/.claude",
			build: func(p *Policy) {
				bind(p, "/home/u/.claude", "/home/u/.claude", AccessRW)
				generated(p, "/home/u/.claude/settings.json", AccessRW)
			},
			want: []string{"evil", "/home/u/.claude", "settings.json", "on the HOST", "Fix:"},
		},
		{
			// A generated file snug authors READ-ONLY is refused too, and the
			// reason is measured rather than assumed: bwrap's --ro-bind-data
			// calls ensure_file, which CREATES the destination before mounting
			// over it. That is how a 0-byte -r--r--r-- CLAUDE.md appeared in the
			// host's ~/.claude, in a directory nothing had otherwise touched.
			name: "a read-only generated file is still created on the host",
			build: func(p *Policy) {
				bind(p, "/home/u/.claude", "/home/u/.claude", AccessRW)
				generated(p, "/home/u/.claude/CLAUDE.md", AccessRO)
			},
			want: []string{"CLAUDE.md", "on the HOST"},
		},
		{
			// NOT @claude. The identity band generates here, and a profile
			// granting rw over the ssh directory is the same defect writing
			// snug's known_hosts onto the host's.
			name: "an identity file under an rw grant on ~/.ssh",
			build: func(p *Policy) {
				bind(p, "/home/u/.ssh", "/home/u/.ssh", AccessRW)
				generated(p, "/home/u/.ssh/known_hosts", AccessRO)
			},
			want: []string{"/home/u/.ssh", "known_hosts", "on the HOST"},
		},
		{
			// Nor is it home-rooted. /etc/resolv.conf is generated on every
			// networked run, and rw on /etc reaches it.
			name: "resolv.conf under an rw grant on /etc",
			build: func(p *Policy) {
				bind(p, "/etc", "/etc", AccessRW)
				generated(p, "/etc/resolv.conf", AccessRW)
			},
			want: []string{"/etc/resolv.conf", "on the HOST"},
		},
		{
			// The grant does not have to be the file's own directory. An
			// ancestor resolves it just as well, which is the direction
			// rejectMasking's first version missed on its own rule.
			//
			// On a neutral tree rather than {home}: an rw bind over the
			// ephemeral home would be refused by rejectMasking first (it covers
			// @home's own tmpfs children), and a fixture that trips a different
			// rule proves nothing about this one.
			name: "an ancestor grant two levels up",
			build: func(p *Policy) {
				bind(p, "/srv/app", "/srv/app", AccessRW)
				generated(p, "/srv/app/deep/gen.conf", AccessRW)
			},
			want: []string{"/srv/app", "gen.conf", "on the HOST"},
		},

		{
			// Fail closed on a shape nobody produces. A KindBind with no host
			// source is malformed rather than legitimate, and the rule refuses
			// it: "I cannot tell where this resolves" must give the same answer
			// as "it resolves onto the host". This case exists because the
			// earlier skip-if-empty branch could not be mutation-tested — no
			// break of it made anything fail, which is how an unreachable-looking
			// fail-open branch stays in a security check.
			name: "a malformed writable bind with no host source still refuses",
			build: func(p *Policy) {
				p.Mounts["/srv/app"] = Mount{
					Guest: "/srv/app", Kind: KindBind, Access: AccessRW, From: []string{"evil"},
				}
				generated(p, "/srv/app/gen.conf", AccessRW)
			},
			want: []string{"/srv/app", "gen.conf", "on the HOST"},
		},
		{
			// #580. This used to be a "must NOT refuse" case, on the theory
			// that a read-only bind covering a generated path was bwrap's own
			// to refuse, loudly and by itself:
			//     bwrap: Can't create file .../.claude/settings.json: Read-only file system
			// That sentence names neither snug nor the profile nor a fix. ARM 3
			// pre-empts it: nothing exists at the destination on the host, so
			// bwrap would have to CREATE the file inside a read-only mount and
			// cannot, and snug now refuses with its own message before bwrap
			// ever runs, rather than letting the run die on bwrap's.
			name: "a read-only bind over an absent destination is now snug's to refuse, not bwrap's",
			build: func(p *Policy) {
				bind(p, "/home/u/.claude", "/home/u/.claude", AccessRO)
				generated(p, "/home/u/.claude/settings.json", AccessRW)
			},
			want: []string{"evil", "/home/u/.claude", "settings.json", "Read-only file system", "Fix:"},
		},

		// ── Must NOT refuse ──────────────────────────────────────────────
		{
			// The normal case, and the reason this rule cannot simply refuse
			// every KindData with a bind anywhere above it: everything snug
			// generates into the ephemeral $HOME sits inside @home's tmpfs.
			name:  "a generated file on the ephemeral home tmpfs",
			build: func(p *Policy) { generated(p, "/home/u/.gitconfig", AccessRW) },
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			p := mustResolveDefaults(t)
			tc.build(p)
			err := p.Validate(newFakeEnv())

			if len(tc.want) == 0 {
				if err != nil {
					t.Fatalf("refused a policy that writes nothing to the host: %v", err)
				}
				return
			}
			if err == nil {
				t.Fatal("accepted a policy in which snug would write its generated content onto " +
					"the HOST. Nothing escapes and no grant is exceeded — snug itself does the " +
					"writing, during setup, and there is no undo (issue #186)")
			}
			for _, want := range tc.want {
				if !strings.Contains(err.Error(), want) {
					t.Errorf("refusal does not name %q, so it does not tell anyone which line to "+
						"delete:\n%v", want, err)
				}
			}
		})
	}
}

// TestTheGeneratedOntoHostRuleNamesBothGrants is the "errors name the fix"
// half, asserted separately because it is the part a later message edit would
// quietly drop. The refusal has to name a genuine CHOICE between two grants —
// the rw one and the profile that generates at that path — since snug cannot
// know which the human meant, and picking one silently would be a downgrade.
func TestTheGeneratedOntoHostRuleNamesBothGrants(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/home/u/.claude", "/host/real/.claude", AccessRW)
	generated(p, "/home/u/.claude/settings.json", AccessRW)

	err := p.Validate(newFakeEnv())
	if err == nil {
		t.Fatal("accepted the reproduction from issue #186")
	}
	for _, want := range []string{
		"evil",                             // the profile that granted rw
		"/host/real/.claude/settings.json", // the HOST file that would be overwritten
		"drop the rw grant",                // one of the two ways out
		"deselect",                         // the other
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not carry %q:\n%v", want, err)
		}
	}
}

// TestTheDeepestMountDecidesWhichCoverIsJudged pins the half of the rule that
// cannot be reached through Validate, and says why it still has to hold.
//
// The rule asks the DEEPEST mount covering the generated path, the same relation
// join is keyed on. Walking every ancestor instead would look more thorough and
// would be wrong: a tmpfs between the writable bind and the file means the write
// lands on the tmpfs, and refusing there is a false positive — the kind that
// teaches the next person to delete the check rather than fix it.
//
// That shape is unreachable in a real policy, because a tmpfs nested inside a
// bind is masking and rejectMasking refuses it first. Both halves are asserted
// here so the reason stays visible: the predicate says "fine", the policy is
// still refused, and neither fact is evidence about the other.
func TestTheDeepestMountDecidesWhichCoverIsJudged(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/srv/app", "/srv/app", AccessRW)
	tmpfsAt(p, "/srv/app/deep")
	generated(p, "/srv/app/deep/gen.conf", AccessRW)

	if err := p.rejectGeneratedOntoHost(newFakeEnv()); err != nil {
		t.Fatalf("the generated file resolves onto a tmpfs, not the host, and was still "+
			"refused — a rule that walks past the deepest cover reports writes that do not "+
			"happen:\n%v", err)
	}
	if err := p.Validate(newFakeEnv()); err == nil {
		t.Fatal("a tmpfs nested inside a bind was accepted by Validate; if rejectMasking " +
			"stopped refusing that shape, this rule's deepest-cover reading becomes reachable " +
			"and needs its own end-to-end case")
	}
}

// ── the containment arm (#576) ───────────────────────────────────────────────
//
// A generated file's destination has to stay inside the grant that is meant to
// cover it. A HOST symlink at a directory component between a bind's root and
// the generated file's own directory can take the destination somewhere the
// grant never named — bwrap's mkdir_with_parents follows it when it creates
// the mountpoint, with no error of its own, so the write lands on the host
// silently. Measured (rejectGeneratedOntoHost's own comment): `ro
// {home}/.config` plus a host `~/.config/git -> ~/proj/sub/dotfiles-git`
// produced a 0-byte read-only allowed_signers file on the host, snug exit 0 —
// the old guard passed this exact shape because it skipped every read-only
// cover outright, on the theory that bwrap itself would refuse loudly. It does
// not, once a symlink is involved.

// TestGeneratedFileRefusedWhenAHostSymlinkRedirectsItOutOfItsCoveringGrant is
// the finding itself, under a read-only cover — the shape the pre-#576 guard
// let straight through.
func TestGeneratedFileRefusedWhenAHostSymlinkRedirectsItOutOfItsCoveringGrant(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/home/u/.config", "/home/u/.config", AccessRO)
	generated(p, "/home/u/.config/git/allowed_signers", AccessRO)

	env := newFakeEnv()
	env.links["/home/u/.config/git"] = "/home/u/proj/sub/dotfiles-git"

	err := p.Validate(env)
	if err == nil {
		t.Fatal("accepted a policy where a host symlink takes a generated file's destination " +
			"outside the read-only grant that covers it")
	}
	for _, want := range []string{"evil", "/home/u/.config", "OUTSIDE", "allowed_signers", "symlink"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not name %q:\n%v", want, err)
		}
	}
}

// TestGeneratedFileRefusedWhenAHostSymlinkRedirectsItOutOfARwCoveringGrant is
// the same escape under an RW cover, so the new containment arm is not
// silently shadowed by issue #186's own arm (ARM 2), which already refuses
// most rw cases without needing a symlink at all. The assertion below checks
// for the containment arm's own wording rather than #186's generic overwrite
// text, so a regression that made ARM 2 catch this by accident — leaving the
// containment arm itself unreachable under rw — would still be caught.
func TestGeneratedFileRefusedWhenAHostSymlinkRedirectsItOutOfARwCoveringGrant(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/home/u/.config", "/home/u/.config", AccessRW)
	generated(p, "/home/u/.config/git/allowed_signers", AccessRO)

	env := newFakeEnv()
	env.links["/home/u/.config/git"] = "/home/u/proj/sub/dotfiles-git"

	err := p.Validate(env)
	if err == nil {
		t.Fatal("accepted a policy where a host symlink takes a generated file's destination " +
			"outside an rw grant that covers it")
	}
	if !strings.Contains(err.Error(), "symlink") {
		t.Errorf("refusal does not read as the containment arm's (no mention of a symlink); "+
			"got:\n%v", err)
	}
}

// TestGeneratedFileAllowedWhenTheHostSymlinkStaysInsideTheCoveringGrant is the
// negative of the negative: a symlink that stays inside its own bind is an
// ordinary dotfile layout (~/.config/git -> ~/.config/git.d), not an escape.
// Without this case the rule degrades to "refuse if any symlink is anywhere in
// the chain", which breaks real dotfile layouts that happen to use one.
//
// The destination is made to EXIST on the host (env.files below). #580's ARM 3
// refuses whenever it does not, which after #580 landed was tripping this
// fixture on ARM 3 instead of on the containment check it is named for — this
// test would have passed for the wrong reason. Making the destination exist
// takes ARM 3 out of the decision, so ARM 1's containment check is what
// accepts this policy again.
//
// This is a NEGATIVE CONTROL, and its own limit is worth stating rather than
// assuming away: with ARM 1's loop deleted outright, this fixture still
// reports no error, because nothing is left to object — the loop can only
// ever REFUSE, never require. Confirmed by deleting the loop and re-running:
// this test stays green. What actually holds ARM 1 accountable is the paired
// positive control above,
// TestGeneratedFileRefusedWhenAHostSymlinkRedirectsItOutOfItsCoveringGrant,
// which goes red the moment the loop is gone. This test's job is narrower: it
// proves ARM 1 does not over-refuse an ordinary dotfile symlink, not that ARM
// 1 exists at all.
func TestGeneratedFileAllowedWhenTheHostSymlinkStaysInsideTheCoveringGrant(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/home/u/.config", "/home/u/.config", AccessRO)
	generated(p, "/home/u/.config/git/allowed_signers", AccessRO)

	env := newFakeEnv()
	env.links["/home/u/.config/git"] = "/home/u/.config/git.d"
	// The fixture publishes what such a host really holds: the DIRECTORY the
	// link points at, and the file inside IT. The walk follows the link the way
	// bwrap does and asks about the destination it lands on, so a fixture that
	// published only the pre-link spelling described a host where the link
	// points at nothing.
	env.dirs["/home/u/.config/git.d"] = true
	env.files["/home/u/.config/git.d/allowed_signers"] = true

	if err := p.Validate(env); err != nil {
		t.Fatalf("refused a host symlink whose target stays inside its own covering grant: %v", err)
	}
}

// TestGeneratedFileRefusedWhenTheDestinationDoesNotExistYet replaces
// "TestGeneratedFileAllowedWhenNoAncestorExistsYet", whose whole premise —
// every ancestor between the bind's root and the generated file's own
// directory answers fs.ErrNotExist, therefore ALLOWED — is exactly what #580
// reverses. This is the same fixture that test used, and it is also ARM 3's
// canonical case: nothing exists yet at the destination itself, so bwrap
// would have to CREATE the file inside the read-only bind covering it and
// cannot.
//
// ARM 1's own tolerance for an absent ancestor is UNCHANGED by #580 — its
// loop still treats fs.ErrNotExist as "not created yet, the escape can only
// be higher up" and continues rather than refusing. What changed is that ARM
// 3 now also looks at the final destination and refuses on its absence alone,
// so the old test's premise cannot survive as an "allowed" case; it inverts
// wholesale rather than leaving a narrower survivor, because the fixture IS
// #580's reproduction.
func TestGeneratedFileRefusedWhenTheDestinationDoesNotExistYet(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/home/u/.config", "/home/u/.config", AccessRO)
	generated(p, "/home/u/.config/git/allowed_signers", AccessRO)

	err := p.Validate(newFakeEnv())
	if err == nil {
		t.Fatal("accepted a policy in which bwrap would have to create the generated file " +
			"inside a read-only bind — it cannot, and the run used to die on bwrap's own " +
			"message, naming neither snug nor the profile nor a fix (issue #580)")
	}
	for _, want := range []string{"evil", "/home/u/.config", "allowed_signers", "Read-only file system", "Fix:"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not name %q:\n%v", want, err)
		}
	}
}

// TestGeneratedFileRefusedWhenAnAncestorCannotBeExamined is the fail-closed
// arm: an ancestor whose Lstat answers a real error (EACCES here, not
// ErrNotExist) must refuse rather than be treated the same as "not created yet"
// — "I cannot tell where this resolves" and "it resolves outside the grant"
// have to give the same answer, or the guard fails open on exactly the input
// nobody anticipated.
//
// The fixture used to fail EvalSymlinks, which is what the arm called before it
// started resolving in the sandbox's namespace. It fails the Lstat now: the
// walk reads shapes and link TEXT, so that is the call an unreadable ancestor
// breaks.
func TestGeneratedFileRefusedWhenAnAncestorCannotBeExamined(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/home/u/.config", "/home/u/.config", AccessRO)
	generated(p, "/home/u/.config/git/allowed_signers", AccessRO)

	env := newFakeEnv()
	env.statErrs["/home/u/.config/git"] = &fs.PathError{
		Op: "lstat", Path: "/home/u/.config/git", Err: syscall.EACCES,
	}

	err := p.Validate(env)
	if err == nil {
		t.Fatal("accepted a policy whose covering directory cannot be examined on the host — " +
			"snug cannot tell where the generated file's destination lands, so it must refuse " +
			"rather than guess")
	}
	for _, want := range []string{"/home/u/.config/git", "cannot be examined", "permission denied"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not carry %q:\n%v", want, err)
		}
	}
}

// ── ARM 3: what bwrap can actually do at that destination (#580) ───────────
//
// A read-only bind covering a generated path used to be left entirely to
// bwrap, which dies with a sentence naming neither snug, nor the profile, nor
// a fix. Which sentence depends on what is AT the destination, and that is the
// table ARM 3 has to agree with. MEASURED on bubblewrap 0.12.0, destination
// inside a --ro-bind:
//
//	shape           --ro-bind-data (AccessRO)             --file (AccessRW)
//	regular file    exit 0, binds over the inode          Can't create file …: Read-only file system
//	absent          Can't create file …: Read-only …      same
//	symlink         Can't mount on symlink destination …  Too many levels of symbolic links
//	directory       Destination is not a file …           —
//
// Two things follow, and both are refusals this arm makes before bwrap runs.
// AccessRW is refused under a read-only cover WHATEVER is at the destination,
// because --file copies rather than binds. AccessRO is accepted only over a
// REGULAR FILE, which is why the arm asks Lstat — Stat follows the link and
// would report a symlink-to-a-file as a file, agreeing with a row bwrap does
// not have.
//
// These cases use a neutral tree (/srv/app) rather than {home}, for the same
// reason "an ancestor grant two levels up" above does: an rw bind over the
// ephemeral home is refused by rejectMasking first, and a fixture that trips a
// different rule proves nothing about this one.

// refusalGeneratedOverAnAbsentDestinationUnderARoBind is ARM 3's own case: a
// read-only bind, and nothing at the destination.
//
// It is a TestGoldenRefusals row as well as the test below, and the golden is
// the point rather than a formality: ARM 3's entire purpose is to REPLACE
// bwrap's sentence with snug's, so the refusal's exact text IS the change. A
// strings.Contains assertion can say the message names the profile and the
// path; it cannot show a reviewer the screen the human ends up reading, which
// is what refusals.txt is for.
func refusalGeneratedOverAnAbsentDestinationUnderARoBind(t testing.TB) error {
	p := resolveDefaults(t)
	bind(p, "/srv/app", "/srv/app", AccessRO)
	generated(p, "/srv/app/deep/gen.conf", AccessRO)
	return p.Validate(newFakeEnv())
}

func TestGeneratedFileOverAnAbsentDestinationUnderAReadOnlyBindIsRefused(t *testing.T) {
	err := refusalGeneratedOverAnAbsentDestinationUnderARoBind(t)
	if err == nil {
		t.Fatal("accepted a policy in which bwrap would have to create a file inside a " +
			"read-only bind — it cannot, and the run used to die on bwrap's own message, " +
			"naming neither snug nor the profile nor a fix (issue #580)")
	}
	for _, want := range []string{
		"evil",                   // the profile that granted the ro bind
		"/srv/app",               // the grant
		"/srv/app/deep/gen.conf", // the generated guest path
		"Read-only file system",  // bwrap's own sentence, quoted so the reader recognises it
		"Fix:",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not name %q:\n%v", want, err)
		}
	}
}

// TestReadOnlyGeneratedFileOverAPresentDestinationUnderAReadOnlyBindIsAllowed
// is the bind-over that already worked before #580 and must keep working:
// bwrap's --ro-bind-data binds over an EXISTING inode rather than creating one
// (issue #73), so a read-only cover is harmless once a REGULAR FILE is there.
// This also carries the part of the old
// "TestGeneratedFileAllowedWhenNoAncestorExistsYet" that #580 did not
// reverse: the intermediate directory /srv/app/deep is absent from the fake
// host too, and ARM 1's loop still tolerates that (fs.ErrNotExist there means
// "not created yet, the escape can only be higher up", not a refusal).
func TestReadOnlyGeneratedFileOverAPresentDestinationUnderAReadOnlyBindIsAllowed(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/srv/app", "/srv/app", AccessRO)
	generated(p, "/srv/app/deep/gen.conf", AccessRO)

	env := newFakeEnv()
	env.files["/srv/app/deep/gen.conf"] = true

	if err := p.Validate(env); err != nil {
		t.Fatalf("refused a read-only bind-over of a file that already exists on the host: %v", err)
	}
}

// refusalWritableGeneratedFileUnderAReadOnlyBind is the redteam round's first
// finding on #580, and the test above is the half that used to assert the bug:
// it built an AccessRW generated file over a PRESENT destination and called the
// acceptance correct, justifying it with --ro-bind-data's semantics. AccessRW
// is not --ro-bind-data. bwrap.go renders it as --file, which COPIES onto the
// destination, and a read-only cover refuses that however present the file is.
//
// MEASURED on bubblewrap 0.12.0, destination an existing regular file inside a
// --ro-bind:
//
//	--file           bwrap: Can't create file <path>: Read-only file system
//	--ro-bind-data   exit 0
//
// Reached end-to-end with the shipped @claude and a profile granting
// `ro = ["{home}/.claude"]`: ~/.claude/settings.json is AccessRW and present,
// snug accepted the policy, and the run died on bwrap's sentence — the exact
// failure ARM 3 exists to pre-empt, arriving through ARM 3's own accept path.
func refusalWritableGeneratedFileUnderAReadOnlyBind(t testing.TB) error {
	p := resolveDefaults(t)
	bind(p, "/srv/app", "/srv/app", AccessRO)
	generated(p, "/srv/app/deep/gen.conf", AccessRW)

	env := newFakeEnv()
	env.files["/srv/app/deep/gen.conf"] = true // present, and it does not help
	return p.Validate(env)
}

func TestWritableGeneratedFileUnderAReadOnlyBindIsRefusedEvenWhenPresent(t *testing.T) {
	err := refusalWritableGeneratedFileUnderAReadOnlyBind(t)
	if err == nil {
		t.Fatal("accepted a WRITABLE generated file under a read-only bind because its " +
			"destination exists — bwrap delivers that with --file, which copies onto the " +
			"destination, and a read-only cover refuses it: the run dies on `Can't create " +
			"file …: Read-only file system` (measured, bubblewrap 0.12.0)")
	}
	for _, want := range []string{
		"evil",                   // the profile that granted the ro bind
		"/srv/app/deep/gen.conf", // the generated guest path
		"--file",                 // WHY presence does not save it
		"Read-only file system",  // bwrap's own sentence
		"Fix:",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not name %q:\n%v", want, err)
		}
	}
}

// refusalGeneratedThroughATranslatingCoverWhoseDestinationIsAbsent is the
// second redteam round's first finding, and it inverts the test that used to
// stand here — "HostDestExists short-circuits before any Lstat", which asserted
// the exemption as a feature.
//
// HostDestExists is set by the CLI from an os.Lstat of the mount's GUEST path.
// The guard's question is about hostDest: the guest path translated through the
// covering grant. The grant language has a translating form (`rw =
// ["/host/dir:/guest/dir"]`), so the two are DIFFERENT PATHS whenever one of
// those covers a generated file — the CLI's fact was true about a file that is
// not the one bwrap would touch.
//
// MEASURED end to end before the fix, with the shipped @claude and
// `rw = ["$S/out:$S/target"]`: snug exit 0, no refusal, nothing on --dry-run
// (whose FILESYSTEM block prints the GUEST path for every generated row), and
// afterwards $S/out — empty before the run — held a 0444 .mcp.json, a .claude/
// directory and a .claude/settings.json, created by snug on the HOST before the
// payload existed. That is issue #186's mechanism, reached through the
// exemption written to prevent it.
//
// The fixture below is that shape: the guest path exists on the fake host (so
// the CLI's HostDestExists is honest), and the translated destination does not.
func refusalGeneratedThroughATranslatingCoverWhoseDestinationIsAbsent(t testing.TB) error {
	p := resolveDefaults(t)
	bind(p, "/srv/app", "/host/elsewhere", AccessRW)
	p.Replace(Mount{
		Guest: "/srv/app/gen.conf", Kind: KindData,
		Access: AccessRO, Content: Secret("generated by snug\n"),
		From: []string{"(snug)"}, HostDestExists: true,
	})

	env := newFakeEnv()
	env.files["/srv/app/gen.conf"] = true // the GUEST path, which is what the CLI statted
	return p.Validate(env)                // /host/elsewhere/gen.conf is not there
}

func TestHostDestExistsDoesNotExemptAPathTranslatingCover(t *testing.T) {
	err := refusalGeneratedThroughATranslatingCoverWhoseDestinationIsAbsent(t)
	if err == nil {
		t.Fatal("accepted a generated mount because HostDestExists said its GUEST path exists, " +
			"while the covering grant translates that path elsewhere — bwrap creates the " +
			"mountpoint at the TRANSLATED destination, on the host, which is issue #186")
	}
	for _, want := range []string{
		"evil",                     // the profile that granted the translating cover
		"/host/elsewhere/gen.conf", // the path bwrap would really create
		"creates",                  // what it does there
		"on the HOST",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not name %q:\n%v", want, err)
		}
	}
	if strings.Contains(err.Error(), "/srv/app/gen.conf on the HOST") {
		t.Errorf("the refusal names the GUEST path as the thing written; the whole finding is "+
			"that those differ:\n%v", err)
	}
}

// refusalWritableGeneratedFileWithHostDestExistsOverARwBind is the redteam
// round's fourth finding: ARM 2's exemption used to read `if m.HostDestExists`
// alone, and its justification — an overmount of an existing file writes
// nothing to the host — is true of --ro-bind-data and FALSE of --file.
//
// MEASURED on bubblewrap 0.12.0, destination an existing regular file inside a
// writable --bind:
//
//	--ro-bind-data   exit 0, host file unchanged   (HOST-ORIGINAL)
//	--file           exit 0, HOST FILE OVERWRITTEN (GENERATED)
//
// So this shape is issue #186 itself: snug writing the host during setup. No
// setter pairs HostDestExists with AccessRW today — all three are AccessRO —
// which is exactly why it needs a test rather than a comment: the fourth setter
// would otherwise reopen #186 in silence.
func refusalWritableGeneratedFileWithHostDestExistsOverARwBind(t testing.TB) error {
	p := resolveDefaults(t)
	bind(p, "/srv/app", "/srv/app", AccessRW)
	p.Replace(Mount{
		Guest: "/srv/app/deep/gen.conf", Kind: KindData,
		Access: AccessRW, Content: Secret("generated by snug\n"),
		From: []string{"(snug)"}, HostDestExists: true,
	})

	env := newFakeEnv()
	env.files["/srv/app/deep/gen.conf"] = true // the host's own file, about to be overwritten
	return p.Validate(env)
}

func TestWritableGeneratedFileIsNotExemptedByHostDestExists(t *testing.T) {
	err := refusalWritableGeneratedFileWithHostDestExistsOverARwBind(t)
	if err == nil {
		t.Fatal("HostDestExists exempted a WRITABLE generated mount over a writable host " +
			"bind. bwrap's --file COPIES onto the destination, so that policy overwrites the " +
			"host's file — issue #186, reached through the exemption meant for --ro-bind-data")
	}
	for _, want := range []string{"evil", "/srv/app/deep/gen.conf", "overwrites", "on the HOST", "Fix:"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not name %q:\n%v", want, err)
		}
	}
}

// refusalGeneratedOverASymlinkDestination is the redteam round's third finding:
// bwrap does not follow the FINAL component, so a symlink at the destination is
// refused by bwrap with its own sentence —
//
//	bwrap: Can't mount on symlink destination <path>
//
// (measured, bubblewrap 0.12.0, and the same shape CVE-2026-87766 hardened).
// ARM 3 used to ask Stat, which FOLLOWS the link and answers "a regular file is
// there", so snug accepted the policy; and where the link dangled, Stat said
// ErrNotExist and snug refused while telling the human nothing exists at a path
// an `ls` shows. Lstat is what makes the guard's question bwrap's question.
func refusalGeneratedOverASymlinkDestination(t testing.TB) error {
	p := resolveDefaults(t)
	bind(p, "/srv/app", "/srv/app", AccessRO)
	generated(p, "/srv/app/deep/gen.conf", AccessRO)

	env := newFakeEnv()
	env.links["/srv/app/deep/gen.conf"] = "/srv/app/deep/real.conf"
	env.files["/srv/app/deep/real.conf"] = true
	return p.Validate(env)
}

func TestGeneratedFileOverASymlinkDestinationIsRefused(t *testing.T) {
	err := refusalGeneratedOverASymlinkDestination(t)
	if err == nil {
		t.Fatal("accepted a generated file whose destination is a SYMLINK on the host. " +
			"bwrap does not follow it — `Can't mount on symlink destination …` — so the run " +
			"dies on bwrap's message; Stat followed the link and reported the file it points at")
	}
	for _, want := range []string{
		"evil",
		"/srv/app/deep/gen.conf",
		"a symlink",                          // the shape, said plainly
		"Can't mount on symlink destination", // the sentence bwrap would print
		"Fix:",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not name %q:\n%v", want, err)
		}
	}
}

// refusalGeneratedOverADirectoryDestination is the same finding's other shape,
// and bwrap says something different again: `Destination is not a file <path>`
// (measured, bubblewrap 0.12.0). A refusal that told the human "nothing exists
// there" about a directory they can `ls` would send them looking for the wrong
// thing.
func refusalGeneratedOverADirectoryDestination(t testing.TB) error {
	p := resolveDefaults(t)
	bind(p, "/srv/app", "/srv/app", AccessRO)
	generated(p, "/srv/app/deep/gen.conf", AccessRO)

	env := newFakeEnv()
	env.dirs["/srv/app/deep/gen.conf"] = true
	return p.Validate(env)
}

func TestGeneratedFileOverADirectoryDestinationIsRefused(t *testing.T) {
	err := refusalGeneratedOverADirectoryDestination(t)
	if err == nil {
		t.Fatal("accepted a generated file whose destination is a DIRECTORY on the host; " +
			"bwrap refuses that with `Destination is not a file …` and the run does not start")
	}
	for _, want := range []string{
		"evil",
		"/srv/app/deep/gen.conf",
		"a directory",
		"Destination is not a file",
		"Fix:",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not name %q:\n%v", want, err)
		}
	}
}

// refusalGeneratedDestinationCannotBeExamined is ARM 3's fail-closed branch: an
// Lstat error that is NOT fs.ErrNotExist (EACCES here). "It is not there" and "I
// cannot tell whether it is there" must give the same answer, or the rule fails
// open on exactly the input nobody anticipated — the same argument
// TestGeneratedFileRefusedWhenAnAncestorCannotBeResolved makes for ARM 1.
//
// This branch was unreachable by any fixture until fakeEnv grew statErrs:
// dirs/files/sockets/fifos can only produce success or fs.ErrNotExist, which
// is why the map exists rather than the branch going untested. Also a
// TestGoldenRefusals row — the message quotes the error verbatim, and whether
// that reads as a sentence a human can act on is a golden's question.
func refusalGeneratedDestinationCannotBeExamined(t testing.TB) error {
	p := resolveDefaults(t)
	bind(p, "/srv/app", "/srv/app", AccessRO)
	generated(p, "/srv/app/deep/gen.conf", AccessRO)

	env := newFakeEnv()
	env.statErrs["/srv/app/deep/gen.conf"] = &fs.PathError{
		Op: "lstat", Path: "/srv/app/deep/gen.conf", Err: syscall.EACCES,
	}
	return p.Validate(env)
}

func TestGeneratedFileRefusedWhenTheDestinationCannotBeExamined(t *testing.T) {
	err := refusalGeneratedDestinationCannotBeExamined(t)
	if err == nil {
		t.Fatal("accepted a policy whose generated destination cannot be statted on the host — " +
			"snug cannot tell whether bwrap would have to create it, so it must refuse rather " +
			"than guess (issue #580)")
	}
	for _, want := range []string{
		"evil",                   // the profile that granted the ro bind
		"/srv/app/deep/gen.conf", // the destination that could not be examined
		"permission denied",      // the Stat error itself, not swallowed
		"refuses rather than guess",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not carry %q:\n%v", want, err)
		}
	}
}

// ── the negatives that keep the containment arm from over-reaching ─────────
//
// Each of these is a real arrangement snug ships or generates into on every
// run. A version of the containment arm that refused any of them would refuse
// the common case rather than the attack, which is the failure mode that gets
// a security check deleted rather than fixed.

// TestSystemSSHConfigUnderTheUsrBindIsStillAllowed pins the DEFAULT selection
// on a host whose system-wide ssh_config lives under /usr (openSUSE;
// systemsshconfig_test.go has the full story). replaceSystemSSHConfig
// generates the replacement directly under @sys's ro /usr bind, and a
// rejected alternative fix — walking every ancestor and refusing whenever one
// could not be proven to exist, rather than treating "not there yet" as "the
// escape can only be higher up" — would have refused this on every default
// run on such a host, with no symlink and no attacker anywhere in the
// picture.
func TestSystemSSHConfigUnderTheUsrBindIsStillAllowed(t *testing.T) {
	env := newFakeEnv()
	env.files["/usr/etc/ssh/ssh_config"] = true

	p, err := Resolve(testRegistry(), testDefaults, testCtx(), env)
	if err != nil {
		t.Fatal(err)
	}
	if err := p.Validate(env); err != nil {
		t.Fatalf("refused the default selection's generated system ssh_config under @sys's ro "+
			"/usr bind: %v", err)
	}
}

// TestProjectMCPJSONInsideTheTargetIsStillAllowed mirrors
// stageProjectMCPJSON (internal/cli/claude.go): a read-only generated file over
// the target's own .mcp.json, which the CLI staged only because os.Lstat found
// a regular file there, landing directly inside the target's own rw bind.
//
// The FIXTURE HOST has to hold that file, and this used to pass without it —
// the guard read the CLI's HostDestExists instead of asking. That is the
// exemption the redteam round drove a host write through (a path-translating
// cover makes "the guest path exists" and "the destination exists" different
// claims), so the fixture now states the fact the CLI measured, on the path the
// guard actually consults.
func TestProjectMCPJSONInsideTheTargetIsStillAllowed(t *testing.T) {
	p := mustResolveDefaults(t)
	p.Replace(Mount{
		Guest: "/home/u/proj/sub/.mcp.json", Kind: KindData,
		Access: AccessRO, Content: Secret("generated by snug\n"),
		From: []string{"@claude"}, HostDestExists: true,
	})

	env := newFakeEnv()
	env.files["/home/u/proj/sub/.mcp.json"] = true

	if err := p.Validate(env); err != nil {
		t.Fatalf("refused a generated file over the target's own existing .mcp.json, inside "+
			"the target's own rw bind: %v", err)
	}
}

// TestResolvConfUnderAWholeEtcBindIsStillAllowed pins the arrangement
// base.toml's own comment names as the one-line escape hatch for anyone who
// wants more than the curated fourteen /etc entries (`ro = ["/etc"]`) —
// testRegistry's fake @sys grants the whole tree the same way. /etc/resolv.conf
// (resolve.go) is generated unconditionally on every run and lands directly
// under it, with no intermediate directory to walk.
func TestResolvConfUnderAWholeEtcBindIsStillAllowed(t *testing.T) {
	p := mustResolveDefaults(t)
	if err := p.Validate(newFakeEnv()); err != nil {
		t.Fatalf("refused a default run — /etc granted whole, resolv.conf generated directly "+
			"under it: %v", err)
	}
}

// TestBwrapAtDestinationMirrorsTheMeasuredTable is the table in one place, and
// it is the reason ARM 3 is a lookup rather than an IsRegular test. Every row
// was RUN on bubblewrap 0.12.0 — `bwrap --dev-bind / / <cover> $g $g <flag> 9
// $g/<shape> -- true 9<content`, with the host tree read afterwards — and the
// two rows nobody would have guessed are the ones that make the difference:
// --ro-bind-data MOUNTS over a FIFO and over a socket, writing nothing, so
// refusing them would deny a policy bubblewrap runs.
func TestBwrapAtDestinationMirrorsTheMeasuredTable(t *testing.T) {
	const dest = "/srv/app/gen.conf"
	file := func(mode fs.FileMode) fs.FileInfo { return fakeInfo{name: dest, mode: mode} }

	for _, tc := range []struct {
		name          string
		fi            fs.FileInfo
		access        Access
		coverWritable bool
		said, writes  string
	}{
		// Every row here has the destination's parent directory PRESENT; the
		// missing-parent rows are their own table below, because bwrap says
		// "Can't mkdir parents for …" there and creates directories as well as
		// the file.
		{"regular file, ro mount, ro cover", file(0), AccessRO, false, "", ""},
		{"regular file, ro mount, rw cover", file(0), AccessRO, true, "", ""},
		{"regular file, rw mount, rw cover", file(0), AccessRW, true, "", "overwrites"},
		{"regular file, rw mount, ro cover", file(0), AccessRW, false,
			"bwrap: Can't create file " + dest + ": Read-only file system", ""},

		{"absent, ro mount, rw cover", nil, AccessRO, true, "", "creates"},
		{"absent, rw mount, rw cover", nil, AccessRW, true, "", "creates"},
		{"absent, ro mount, ro cover", nil, AccessRO, false,
			"bwrap: Can't create file " + dest + ": Read-only file system", ""},

		{"symlink, ro mount", file(fs.ModeSymlink), AccessRO, false,
			"bwrap: Can't mount on symlink destination " + dest, ""},
		{"symlink, rw mount", file(fs.ModeSymlink), AccessRW, true,
			"bwrap: Can't create file " + dest + ": Too many levels of symbolic links", ""},

		{"directory, ro mount", file(fs.ModeDir), AccessRO, false,
			"bwrap: Destination is not a file " + dest, ""},
		{"directory, rw mount", file(fs.ModeDir), AccessRW, true,
			"bwrap: Can't create file " + dest + ": Is a directory", ""},

		// The two acceptances that are not regular files.
		{"FIFO, ro mount", file(fs.ModeNamedPipe), AccessRO, false, "", ""},
		{"socket, ro mount", file(fs.ModeSocket), AccessRO, false, "", ""},

		{"socket, rw mount", file(fs.ModeSocket), AccessRW, true,
			"bwrap: Can't create file " + dest + ": No such device or address", ""},
	} {
		t.Run(tc.name, func(t *testing.T) {
			v := bwrapAtDestination(dest, tc.fi, true, tc.access, tc.coverWritable)
			if v.said != tc.said {
				t.Errorf("said = %q, measured %q", v.said, tc.said)
			}
			if v.writes != tc.writes {
				t.Errorf("writes = %q, measured %q", v.writes, tc.writes)
			}
			if got := v.ok(); got != (tc.said == "" && tc.writes == "") {
				t.Errorf("ok() = %v, which disagrees with the row itself", got)
			}
		})
	}

	// The FIFO row for a WRITABLE mount is its own case because bwrap gives no
	// message at all: --file opens the destination, opening a FIFO with no
	// reader blocks, and the run never returns. Measured with `timeout 10`,
	// which is what killed it (rc 124). The refusal says so rather than quoting
	// a sentence that does not exist.
	v := bwrapAtDestination(dest, file(fs.ModeNamedPipe), true, AccessRW, true)
	if v.ok() {
		t.Fatal("accepted a writable generated file onto a FIFO; bwrap blocks in the open and " +
			"the run hangs with nothing printed")
	}
	if !strings.Contains(v.said, "blocks") || strings.Contains(v.said, "Can't create file") {
		t.Errorf("the FIFO verdict quotes a bwrap sentence instead of saying it hangs: %q", v.said)
	}
}

// TestGeneratedFileOverAFifoDestinationIsAllowed is the acceptance the table
// above records, reached through the guard: bwrap binds over a FIFO and writes
// nothing to the host, so refusing it would be snug denying a policy bubblewrap
// runs. Low-reachability — the CLI's projectableTargetFile refuses the shapes a
// user can realistically point at one — which is why it is pinned here rather
// than left to the shipped profiles.
func TestGeneratedFileOverAFifoDestinationIsAllowed(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/srv/app", "/srv/app", AccessRO)
	generated(p, "/srv/app/gen.conf", AccessRO)

	env := newFakeEnv()
	env.fifos = map[string]bool{"/srv/app/gen.conf": true}

	if err := p.Validate(env); err != nil {
		t.Fatalf("refused a read-only generated file over a FIFO, which bwrap mounts over "+
			"happily (measured, 0.12.0, exit 0 and the host FIFO untouched): %v", err)
	}
}

// refusalGeneratedThroughARelativeLinkInATranslatingCover is the third redteam
// round's escape, and it is the one this whole guard exists to stop: SNUG
// writing the host, before the sandbox exists, with exit 0.
//
// The arm resolved the ancestor chain on the HOST, with EvalSymlinks. bwrap
// resolves it inside the SANDBOX, where the components are guest paths. A
// path-translating cover makes those different places, so a relative link can
// stay inside the grant host-side and land in ANOTHER grant guest-side.
//
// MEASURED end to end before the fix, with `ro = ["$S/h/cover:$S/proj"]`,
// `rw = ["$S/data:$S/cover"]` and a host `$S/h/cover/.claude -> ../cover/real`:
//
//	host-side  $S/h/cover/.claude   -> $S/h/cover/real     (inside the grant, accepted)
//	guest-side $S/proj/.claude      -> $S/cover/real       (the OTHER grant)
//	result     snug exit 0, payload ran, and afterwards
//	           $S/data/real/settings.json existed on the host, 0444
//
// Nothing on --dry-run named that path: every generated row prints the GUEST
// path. After the fix the same selection is refused, exit 77, and $S/data is
// still empty.
//
// The fixture mirrors it: the cover translates (/srv/app is the host's
// /host/cover), the link text is relative, and the host side of it stays inside
// the cover while the guest side does not.
func refusalGeneratedThroughARelativeLinkInATranslatingCover(t testing.TB) error {
	p := resolveDefaults(t)
	bind(p, "/srv/app", "/host/cover", AccessRO)
	generated(p, "/srv/app/link/gen.conf", AccessRO)

	env := newFakeEnv()
	env.links["/host/cover/link"] = "../cover/real" // host-side: /host/cover/real, inside
	env.dirs["/host/cover/real"] = true
	env.files["/host/cover/real/gen.conf"] = true
	return p.Validate(env) // guest-side: /srv/cover/real, outside /srv/app
}

func TestGeneratedFileRefusedWhenARelativeLinkEscapesInTheSandboxNamespace(t *testing.T) {
	err := refusalGeneratedThroughARelativeLinkInATranslatingCover(t)
	if err == nil {
		t.Fatal("accepted a policy whose ancestor symlink stays inside the grant on the HOST " +
			"and leaves it inside the SANDBOX — bwrap resolves in the sandbox, so the generated " +
			"file lands in whatever grant covers the landing there, and snug creates it on that " +
			"grant's host tree before the payload exists (issue #186)")
	}
	for _, want := range []string{
		"evil",             // the profile that granted the translating cover
		"/host/cover/link", // the host symlink
		"../cover/real",    // its text, which is what bwrap reads
		"/srv/cover/real",  // where the SANDBOX puts it
		"OUTSIDE that grant",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not name %q:\n%v", want, err)
		}
	}
}

// TestBwrapMkdirParentsRowsAreMeasuredToo covers the rows the first table did
// not: a destination whose PARENT DIRECTORY does not exist. bwrap says
// something else there, and under a writable cover it makes the directories as
// well as the file. MEASURED, bubblewrap 0.12.0:
//
//	--ro-bind cover, either flag   bwrap: Can't mkdir parents for <dest>: Read-only file system
//	--bind cover, --ro-bind-data   exit 0, and on the host: d 700 sub/, f 444 sub/dest.json
func TestBwrapMkdirParentsRowsAreMeasuredToo(t *testing.T) {
	const dest = "/srv/app/sub/gen.conf"

	v := bwrapAtDestination(dest, nil, false, AccessRO, false)
	if want := "bwrap: Can't mkdir parents for " + dest + ": Read-only file system"; v.said != want {
		t.Errorf("read-only cover, missing parent: said = %q, measured %q", v.said, want)
	}
	if v.writes != "" {
		t.Errorf("read-only cover, missing parent: bwrap writes nothing there, got %q", v.writes)
	}

	v = bwrapAtDestination(dest, nil, false, AccessRO, true)
	if v.said != "" {
		t.Errorf("writable cover, missing parent: bwrap succeeds, got the refusal %q", v.said)
	}
	if !strings.Contains(v.writes, "directory") {
		t.Errorf("writable cover, missing parent: the refusal must say the DIRECTORIES are "+
			"created too (measured: a 0700 sub/ as well as the 0444 file), got %q", v.writes)
	}
}

// TestBwrapDeviceNodeRowIsMeasuredToo is the shape fileShape could already name
// and the table had no case for. MEASURED with /dev/null as the destination
// inside a --bind of /dev: --ro-bind-data exits 0 and the sandbox reads the
// generated file, while --file dies on `Can't create file /dev/null: Permission
// denied` — bwrap's /dev is nodev, so the open fails rather than writing.
func TestBwrapDeviceNodeRowIsMeasuredToo(t *testing.T) {
	const dest = "/dev/null"
	dev := fakeInfo{name: dest, mode: fs.ModeDevice}

	if v := bwrapAtDestination(dest, dev, true, AccessRO, true); !v.ok() {
		t.Errorf("refused --ro-bind-data over a device node, which bwrap mounts (exit 0, host "+
			"node intact): %+v", v)
	}
	v := bwrapAtDestination(dest, dev, true, AccessRW, true)
	if want := "bwrap: Can't create file " + dest + ": Permission denied"; v.said != want {
		t.Errorf("device node, --file: said = %q, measured %q", v.said, want)
	}
	if v.writes != "" {
		t.Errorf("device node, --file: bwrap writes nothing (EACCES on the open), got %q", v.writes)
	}
}
