package policy

import (
	"io/fs"
	"strings"
	"syscall"
	"testing"
)

// SNUG'S OWN GENERATED CONTENT MUST NEVER BE WRITTEN ONTO THE HOST.
//
// The property, stated once so the cases below can be read against it:
//
//	for every resolved policy, no KindData mount's guest path resolves
//	through a writable host bind.
//
// It is issue #186, and it is the rarest kind of finding here: not a payload
// doing something, not a grant being exceeded, but SNUG writing, during setup,
// before the sandbox is useful. A profile granted rw on a tree, snug generated a
// file at a path inside it, and bwrap's `--file` copied the generated content
// onto the host's file. A real ~/.claude lost its settings.json to the allowlist
// output, its .credentials.json to the staged copy (refreshToken gone), and
// gained a 0-byte read-only CLAUDE.md.
//
// Every mitigation aimed at the sandboxed process — seccomp, the fd sweep,
// --remount-ro / — is irrelevant to it, because the writer is on the other side.
//
// The cases are deliberately not all @claude. KindData carries /etc/resolv.conf
// and the identity files too, and a fix keyed to the three files that happened
// to be damaged would close one instance of a general defect.

// generated authors a KindData mount the way snug itself does — through
// Policy.Replace, which is what sets Authored. That matters: Authored is exactly
// the field rejectMasking exempts, and this rule exists because that exemption's
// reach does not cover a profile STEERING where the authored mount lands.
func generated(p *Policy, guest string, access Access) {
	p.Replace(Mount{
		Guest:   guest,
		Kind:    KindData,
		Access:  access,
		Content: Secret("generated by snug\n"),
	})
}

// bind puts a profile's grant into an already-resolved policy. Post-resolution
// mutation is the honest fixture here: the defect is about what Validate does
// with a policy, and building it through two profiles would test Resolve's
// merge on the way to testing this.
func bind(p *Policy, guest, host string, access Access) {
	p.Mounts[guest] = Mount{
		Guest: guest, Kind: KindBind, Host: host, Access: access, From: []string{"evil"},
	}
}

func tmpfsAt(p *Policy, guest string) {
	p.Mounts[guest] = Mount{Guest: guest, Kind: KindTmpfs, Access: AccessRW, From: []string{"evil"}}
}

// TestGeneratedFileOverAWritableHostBindIsRefused is the regression. Each row
// that must be refused names a DIFFERENT generator, because the defect is not
// @claude's.
func TestGeneratedFileOverAWritableHostBindIsRefused(t *testing.T) {
	for _, tc := range []struct {
		name  string
		build func(p *Policy)
		want  []string // substrings the refusal must carry; empty means "must not refuse"
	}{
		{
			// The shape that really happened.
			name: "claude settings under an rw grant on ~/.claude",
			build: func(p *Policy) {
				bind(p, "/home/u/.claude", "/home/u/.claude", AccessRW)
				generated(p, "/home/u/.claude/settings.json", AccessRW)
			},
			want: []string{"evil", "/home/u/.claude", "settings.json", "on the HOST", "Fix:"},
		},
		{
			// A generated file snug authors READ-ONLY is refused too, and the
			// reason is measured rather than assumed: bwrap's --ro-bind-data
			// calls ensure_file, which CREATES the destination before mounting
			// over it. That is how a 0-byte -r--r--r-- CLAUDE.md appeared in the
			// host's ~/.claude, in a directory nothing had otherwise touched.
			name: "a read-only generated file is still created on the host",
			build: func(p *Policy) {
				bind(p, "/home/u/.claude", "/home/u/.claude", AccessRW)
				generated(p, "/home/u/.claude/CLAUDE.md", AccessRO)
			},
			want: []string{"CLAUDE.md", "on the HOST"},
		},
		{
			// NOT @claude. The identity band generates here, and a profile
			// granting rw over the ssh directory is the same defect writing
			// snug's known_hosts onto the host's.
			name: "an identity file under an rw grant on ~/.ssh",
			build: func(p *Policy) {
				bind(p, "/home/u/.ssh", "/home/u/.ssh", AccessRW)
				generated(p, "/home/u/.ssh/known_hosts", AccessRO)
			},
			want: []string{"/home/u/.ssh", "known_hosts", "on the HOST"},
		},
		{
			// Nor is it home-rooted. /etc/resolv.conf is generated on every
			// networked run, and rw on /etc reaches it.
			name: "resolv.conf under an rw grant on /etc",
			build: func(p *Policy) {
				bind(p, "/etc", "/etc", AccessRW)
				generated(p, "/etc/resolv.conf", AccessRW)
			},
			want: []string{"/etc/resolv.conf", "on the HOST"},
		},
		{
			// The grant does not have to be the file's own directory. An
			// ancestor resolves it just as well, which is the direction
			// rejectMasking's first version missed on its own rule.
			//
			// On a neutral tree rather than {home}: an rw bind over the
			// ephemeral home would be refused by rejectMasking first (it covers
			// @home's own tmpfs children), and a fixture that trips a different
			// rule proves nothing about this one.
			name: "an ancestor grant two levels up",
			build: func(p *Policy) {
				bind(p, "/srv/app", "/srv/app", AccessRW)
				generated(p, "/srv/app/deep/gen.conf", AccessRW)
			},
			want: []string{"/srv/app", "gen.conf", "on the HOST"},
		},

		{
			// Fail closed on a shape nobody produces. A KindBind with no host
			// source is malformed rather than legitimate, and the rule refuses
			// it: "I cannot tell where this resolves" must give the same answer
			// as "it resolves onto the host". This case exists because the
			// earlier skip-if-empty branch could not be mutation-tested — no
			// break of it made anything fail, which is how an unreachable-looking
			// fail-open branch stays in a security check.
			name: "a malformed writable bind with no host source still refuses",
			build: func(p *Policy) {
				p.Mounts["/srv/app"] = Mount{
					Guest: "/srv/app", Kind: KindBind, Access: AccessRW, From: []string{"evil"},
				}
				generated(p, "/srv/app/gen.conf", AccessRW)
			},
			want: []string{"/srv/app", "gen.conf", "on the HOST"},
		},
		{
			// #580. This used to be a "must NOT refuse" case, on the theory
			// that a read-only bind covering a generated path was bwrap's own
			// to refuse, loudly and by itself:
			//     bwrap: Can't create file .../.claude/settings.json: Read-only file system
			// That sentence names neither snug nor the profile nor a fix. ARM 3
			// pre-empts it: nothing exists at the destination on the host, so
			// bwrap would have to CREATE the file inside a read-only mount and
			// cannot, and snug now refuses with its own message before bwrap
			// ever runs, rather than letting the run die on bwrap's.
			name: "a read-only bind over an absent destination is now snug's to refuse, not bwrap's",
			build: func(p *Policy) {
				bind(p, "/home/u/.claude", "/home/u/.claude", AccessRO)
				generated(p, "/home/u/.claude/settings.json", AccessRW)
			},
			want: []string{"evil", "/home/u/.claude", "settings.json", "Read-only file system", "Fix:"},
		},

		// ── Must NOT refuse ──────────────────────────────────────────────
		{
			// The normal case, and the reason this rule cannot simply refuse
			// every KindData with a bind anywhere above it: everything snug
			// generates into the ephemeral $HOME sits inside @home's tmpfs.
			name:  "a generated file on the ephemeral home tmpfs",
			build: func(p *Policy) { generated(p, "/home/u/.gitconfig", AccessRW) },
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			p := mustResolveDefaults(t)
			tc.build(p)
			err := p.Validate(newFakeEnv())

			if len(tc.want) == 0 {
				if err != nil {
					t.Fatalf("refused a policy that writes nothing to the host: %v", err)
				}
				return
			}
			if err == nil {
				t.Fatal("accepted a policy in which snug would write its generated content onto " +
					"the HOST. Nothing escapes and no grant is exceeded — snug itself does the " +
					"writing, during setup, and there is no undo (issue #186)")
			}
			for _, want := range tc.want {
				if !strings.Contains(err.Error(), want) {
					t.Errorf("refusal does not name %q, so it does not tell anyone which line to "+
						"delete:\n%v", want, err)
				}
			}
		})
	}
}

// TestTheGeneratedOntoHostRuleNamesBothGrants is the "errors name the fix"
// half, asserted separately because it is the part a later message edit would
// quietly drop. The refusal has to name a genuine CHOICE between two grants —
// the rw one and the profile that generates at that path — since snug cannot
// know which the human meant, and picking one silently would be a downgrade.
func TestTheGeneratedOntoHostRuleNamesBothGrants(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/home/u/.claude", "/host/real/.claude", AccessRW)
	generated(p, "/home/u/.claude/settings.json", AccessRW)

	err := p.Validate(newFakeEnv())
	if err == nil {
		t.Fatal("accepted the reproduction from issue #186")
	}
	for _, want := range []string{
		"evil",                             // the profile that granted rw
		"/host/real/.claude/settings.json", // the HOST file that would be overwritten
		"drop the rw grant",                // one of the two ways out
		"deselect",                         // the other
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not carry %q:\n%v", want, err)
		}
	}
}

// TestTheDeepestMountDecidesWhichCoverIsJudged pins the half of the rule that
// cannot be reached through Validate, and says why it still has to hold.
//
// The rule asks the DEEPEST mount covering the generated path, the same relation
// join is keyed on. Walking every ancestor instead would look more thorough and
// would be wrong: a tmpfs between the writable bind and the file means the write
// lands on the tmpfs, and refusing there is a false positive — the kind that
// teaches the next person to delete the check rather than fix it.
//
// That shape is unreachable in a real policy, because a tmpfs nested inside a
// bind is masking and rejectMasking refuses it first. Both halves are asserted
// here so the reason stays visible: the predicate says "fine", the policy is
// still refused, and neither fact is evidence about the other.
func TestTheDeepestMountDecidesWhichCoverIsJudged(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/srv/app", "/srv/app", AccessRW)
	tmpfsAt(p, "/srv/app/deep")
	generated(p, "/srv/app/deep/gen.conf", AccessRW)

	if err := p.rejectGeneratedOntoHost(newFakeEnv()); err != nil {
		t.Fatalf("the generated file resolves onto a tmpfs, not the host, and was still "+
			"refused — a rule that walks past the deepest cover reports writes that do not "+
			"happen:\n%v", err)
	}
	if err := p.Validate(newFakeEnv()); err == nil {
		t.Fatal("a tmpfs nested inside a bind was accepted by Validate; if rejectMasking " +
			"stopped refusing that shape, this rule's deepest-cover reading becomes reachable " +
			"and needs its own end-to-end case")
	}
}

// ── the containment arm (#576) ───────────────────────────────────────────────
//
// A generated file's destination has to stay inside the grant that is meant to
// cover it. A HOST symlink at a directory component between a bind's root and
// the generated file's own directory can take the destination somewhere the
// grant never named — bwrap's mkdir_with_parents follows it when it creates
// the mountpoint, with no error of its own, so the write lands on the host
// silently. Measured (rejectGeneratedOntoHost's own comment): `ro
// {home}/.config` plus a host `~/.config/git -> ~/proj/sub/dotfiles-git`
// produced a 0-byte read-only allowed_signers file on the host, snug exit 0 —
// the old guard passed this exact shape because it skipped every read-only
// cover outright, on the theory that bwrap itself would refuse loudly. It does
// not, once a symlink is involved.

// TestGeneratedFileRefusedWhenAHostSymlinkRedirectsItOutOfItsCoveringGrant is
// the finding itself, under a read-only cover — the shape the pre-#576 guard
// let straight through.
func TestGeneratedFileRefusedWhenAHostSymlinkRedirectsItOutOfItsCoveringGrant(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/home/u/.config", "/home/u/.config", AccessRO)
	generated(p, "/home/u/.config/git/allowed_signers", AccessRO)

	env := newFakeEnv()
	env.links["/home/u/.config/git"] = "/home/u/proj/sub/dotfiles-git"

	err := p.Validate(env)
	if err == nil {
		t.Fatal("accepted a policy where a host symlink takes a generated file's destination " +
			"outside the read-only grant that covers it")
	}
	for _, want := range []string{"evil", "/home/u/.config", "OUTSIDE", "allowed_signers", "symlink"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not name %q:\n%v", want, err)
		}
	}
}

// TestGeneratedFileRefusedWhenAHostSymlinkRedirectsItOutOfARwCoveringGrant is
// the same escape under an RW cover, so the new containment arm is not
// silently shadowed by issue #186's own arm (ARM 2), which already refuses
// most rw cases without needing a symlink at all. The assertion below checks
// for the containment arm's own wording rather than #186's generic overwrite
// text, so a regression that made ARM 2 catch this by accident — leaving the
// containment arm itself unreachable under rw — would still be caught.
func TestGeneratedFileRefusedWhenAHostSymlinkRedirectsItOutOfARwCoveringGrant(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/home/u/.config", "/home/u/.config", AccessRW)
	generated(p, "/home/u/.config/git/allowed_signers", AccessRO)

	env := newFakeEnv()
	env.links["/home/u/.config/git"] = "/home/u/proj/sub/dotfiles-git"

	err := p.Validate(env)
	if err == nil {
		t.Fatal("accepted a policy where a host symlink takes a generated file's destination " +
			"outside an rw grant that covers it")
	}
	if !strings.Contains(err.Error(), "symlink") {
		t.Errorf("refusal does not read as the containment arm's (no mention of a symlink); "+
			"got:\n%v", err)
	}
}

// TestGeneratedFileAllowedWhenTheHostSymlinkStaysInsideTheCoveringGrant is the
// negative of the negative: a symlink that stays inside its own bind is an
// ordinary dotfile layout (~/.config/git -> ~/.config/git.d), not an escape.
// Without this case the rule degrades to "refuse if any symlink is anywhere in
// the chain", which breaks real dotfile layouts that happen to use one.
//
// The destination is made to EXIST on the host (env.files below). #580's ARM 3
// refuses whenever it does not, which after #580 landed was tripping this
// fixture on ARM 3 instead of on the containment check it is named for — this
// test would have passed for the wrong reason. Making the destination exist
// takes ARM 3 out of the decision, so ARM 1's containment check is what
// accepts this policy again.
//
// This is a NEGATIVE CONTROL, and its own limit is worth stating rather than
// assuming away: with ARM 1's loop deleted outright, this fixture still
// reports no error, because nothing is left to object — the loop can only
// ever REFUSE, never require. Confirmed by deleting the loop and re-running:
// this test stays green. What actually holds ARM 1 accountable is the paired
// positive control above,
// TestGeneratedFileRefusedWhenAHostSymlinkRedirectsItOutOfItsCoveringGrant,
// which goes red the moment the loop is gone. This test's job is narrower: it
// proves ARM 1 does not over-refuse an ordinary dotfile symlink, not that ARM
// 1 exists at all.
func TestGeneratedFileAllowedWhenTheHostSymlinkStaysInsideTheCoveringGrant(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/home/u/.config", "/home/u/.config", AccessRO)
	generated(p, "/home/u/.config/git/allowed_signers", AccessRO)

	env := newFakeEnv()
	env.links["/home/u/.config/git"] = "/home/u/.config/git.d"
	env.files["/home/u/.config/git/allowed_signers"] = true

	if err := p.Validate(env); err != nil {
		t.Fatalf("refused a host symlink whose target stays inside its own covering grant: %v", err)
	}
}

// TestGeneratedFileRefusedWhenTheDestinationDoesNotExistYet replaces
// "TestGeneratedFileAllowedWhenNoAncestorExistsYet", whose whole premise —
// every ancestor between the bind's root and the generated file's own
// directory answers fs.ErrNotExist, therefore ALLOWED — is exactly what #580
// reverses. This is the same fixture that test used, and it is also ARM 3's
// canonical case: nothing exists yet at the destination itself, so bwrap
// would have to CREATE the file inside the read-only bind covering it and
// cannot.
//
// ARM 1's own tolerance for an absent ancestor is UNCHANGED by #580 — its
// loop still treats fs.ErrNotExist as "not created yet, the escape can only
// be higher up" and continues rather than refusing. What changed is that ARM
// 3 now also looks at the final destination and refuses on its absence alone,
// so the old test's premise cannot survive as an "allowed" case; it inverts
// wholesale rather than leaving a narrower survivor, because the fixture IS
// #580's reproduction.
func TestGeneratedFileRefusedWhenTheDestinationDoesNotExistYet(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/home/u/.config", "/home/u/.config", AccessRO)
	generated(p, "/home/u/.config/git/allowed_signers", AccessRO)

	err := p.Validate(newFakeEnv())
	if err == nil {
		t.Fatal("accepted a policy in which bwrap would have to create the generated file " +
			"inside a read-only bind — it cannot, and the run used to die on bwrap's own " +
			"message, naming neither snug nor the profile nor a fix (issue #580)")
	}
	for _, want := range []string{"evil", "/home/u/.config", "allowed_signers", "Read-only file system", "Fix:"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not name %q:\n%v", want, err)
		}
	}
}

// TestGeneratedFileRefusedWhenAnAncestorCannotBeResolved is the fail-closed
// arm: EvalSymlinks answering a real error (EACCES here, not ErrNotExist) must
// refuse rather than be treated the same as "not created yet" — "I cannot tell
// where this resolves" and "it resolves outside the grant" have to give the
// same answer, or the guard fails open on exactly the input nobody
// anticipated.
func TestGeneratedFileRefusedWhenAnAncestorCannotBeResolved(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/home/u/.config", "/home/u/.config", AccessRO)
	generated(p, "/home/u/.config/git/allowed_signers", AccessRO)

	env := newFakeEnv()
	env.symlinkErrs["/home/u/.config/git"] = &fs.PathError{
		Op: "lstat", Path: "/home/u/.config/git", Err: syscall.EACCES,
	}

	err := p.Validate(env)
	if err == nil {
		t.Fatal("accepted a policy whose covering directory cannot be resolved on the host — " +
			"snug cannot tell where the generated file's destination lands, so it must refuse " +
			"rather than guess")
	}
	if !strings.Contains(err.Error(), "cannot be resolved") {
		t.Errorf("refusal does not say the ancestor could not be resolved: %v", err)
	}
}

// ── ARM 3: the destination must already exist on the host (#580) ───────────
//
// A read-only bind covering a generated path used to be left entirely to
// bwrap: if nothing was at the destination, bwrap had to create the
// mountpoint inside a read-only mount and died with
//
//	bwrap: Can't create file .../.config/git/allowed_signers: Read-only file system
//
// which names neither snug, nor the profile, nor a fix. ARM 3 stats the
// destination through the injected Environ — the same seam ARM 1 already uses
// for EvalSymlinks — and refuses before bwrap ever runs, with a message that
// does. These cases use a neutral tree (/srv/app) rather than {home}, for the
// same reason "an ancestor grant two levels up" above does: an rw bind over
// the ephemeral home is refused by rejectMasking first, and a fixture that
// trips a different rule proves nothing about this one.

// TestGeneratedFileOverAnAbsentDestinationUnderAReadOnlyBindIsRefused is ARM
// 3's own case: a read-only bind, and nothing at the destination.
func TestGeneratedFileOverAnAbsentDestinationUnderAReadOnlyBindIsRefused(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/srv/app", "/srv/app", AccessRO)
	generated(p, "/srv/app/deep/gen.conf", AccessRW)

	err := p.Validate(newFakeEnv())
	if err == nil {
		t.Fatal("accepted a policy in which bwrap would have to create a file inside a " +
			"read-only bind — it cannot, and the run used to die on bwrap's own message, " +
			"naming neither snug nor the profile nor a fix (issue #580)")
	}
	for _, want := range []string{
		"evil",                   // the profile that granted the ro bind
		"/srv/app",               // the grant
		"/srv/app/deep/gen.conf", // the generated guest path
		"Read-only file system",  // bwrap's own sentence, quoted so the reader recognises it
		"Fix:",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("refusal does not name %q:\n%v", want, err)
		}
	}
}

// TestGeneratedFileOverAPresentDestinationUnderAReadOnlyBindIsAllowed is the
// bind-over that already worked before #580 and must keep working: bwrap's
// --ro-bind-data binds over an EXISTING inode rather than creating one
// (issue #73), so a read-only cover is harmless once the destination is
// already there. This also carries the part of the old
// "TestGeneratedFileAllowedWhenNoAncestorExistsYet" that #580 did not
// reverse: the intermediate directory /srv/app/deep is absent from the fake
// host too, and ARM 1's loop still tolerates that (fs.ErrNotExist there means
// "not created yet, the escape can only be higher up", not a refusal).
func TestGeneratedFileOverAPresentDestinationUnderAReadOnlyBindIsAllowed(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/srv/app", "/srv/app", AccessRO)
	generated(p, "/srv/app/deep/gen.conf", AccessRW)

	env := newFakeEnv()
	env.files["/srv/app/deep/gen.conf"] = true

	if err := p.Validate(env); err != nil {
		t.Fatalf("refused a read-only bind-over of a file that already exists on the host: %v", err)
	}
}

// TestHostDestExistsShortCircuitsARM3BeforeAnyStat proves ARM 2's fast path
// runs BEFORE ARM 3 ever stats the destination, rather than merely agreeing
// with it. The destination here is absent from the fake host — env.Stat on
// it answers fs.ErrNotExist, and ARM 3 refuses on that alone, as the sibling
// test above shows for the identical path. HostDestExists carries the CLI's
// own os.Lstat fact that the destination exists on the REAL host (the fake's
// map is not the same claim), so this policy is only accepted if ARM 2's
// `continue` short-circuits before ARM 3 gets to look.
func TestHostDestExistsShortCircuitsARM3BeforeAnyStat(t *testing.T) {
	p := mustResolveDefaults(t)
	bind(p, "/srv/app", "/srv/app", AccessRO)
	p.Replace(Mount{
		Guest: "/srv/app/deep/gen.conf", Kind: KindData,
		Access: AccessRW, Content: Secret("generated by snug\n"),
		HostDestExists: true,
	})

	if err := p.Validate(newFakeEnv()); err != nil {
		t.Fatalf("refused a generated mount whose HostDestExists is true, even though ARM 2's "+
			"fast path is supposed to accept it before ARM 3 ever stats the (here, absent) "+
			"destination: %v", err)
	}
}

// No test exercises ARM 3's "cannot be examined" branch (a Stat error that is
// NOT fs.ErrNotExist). fakeEnv.Stat in resolve_test.go has no mechanism to
// produce one — unlike EvalSymlinks, which symlinkErrs lets a fixture fail
// with an arbitrary error, Stat here only ever returns success or
// fs.ErrNotExist. Adding that mechanism means touching fakeEnv, which is out
// of scope for this change; this comment records the gap rather than
// papering over it with a test that cannot reach the branch it claims to.

// ── the negatives that keep the containment arm from over-reaching ─────────
//
// Each of these is a real arrangement snug ships or generates into on every
// run. A version of the containment arm that refused any of them would refuse
// the common case rather than the attack, which is the failure mode that gets
// a security check deleted rather than fixed.

// TestSystemSSHConfigUnderTheUsrBindIsStillAllowed pins the DEFAULT selection
// on a host whose system-wide ssh_config lives under /usr (openSUSE;
// systemsshconfig_test.go has the full story). replaceSystemSSHConfig
// generates the replacement directly under @sys's ro /usr bind, and a
// rejected alternative fix — walking every ancestor and refusing whenever one
// could not be proven to exist, rather than treating "not there yet" as "the
// escape can only be higher up" — would have refused this on every default
// run on such a host, with no symlink and no attacker anywhere in the
// picture.
func TestSystemSSHConfigUnderTheUsrBindIsStillAllowed(t *testing.T) {
	env := newFakeEnv()
	env.dirs["/usr/etc/ssh/ssh_config"] = true

	p, err := Resolve(testRegistry(), testDefaults, testCtx(), env)
	if err != nil {
		t.Fatal(err)
	}
	if err := p.Validate(env); err != nil {
		t.Fatalf("refused the default selection's generated system ssh_config under @sys's ro "+
			"/usr bind: %v", err)
	}
}

// TestProjectMCPJSONInsideTheTargetIsStillAllowed mirrors
// stageProjectMCPJSON (internal/cli/claude.go): a read-only generated file
// whose HostDestExists carries the os.Lstat fact that the target's own
// .mcp.json already exists, landing directly inside the target's own rw bind.
func TestProjectMCPJSONInsideTheTargetIsStillAllowed(t *testing.T) {
	p := mustResolveDefaults(t)
	p.Replace(Mount{
		Guest: "/home/u/proj/sub/.mcp.json", Kind: KindData,
		Access: AccessRO, Content: Secret("generated by snug\n"),
		HostDestExists: true,
	})

	if err := p.Validate(newFakeEnv()); err != nil {
		t.Fatalf("refused a generated file whose HostDestExists is true, inside the target's "+
			"own rw bind: %v", err)
	}
}

// TestResolvConfUnderAWholeEtcBindIsStillAllowed pins the arrangement
// base.toml's own comment names as the one-line escape hatch for anyone who
// wants more than the curated fourteen /etc entries (`ro = ["/etc"]`) —
// testRegistry's fake @sys grants the whole tree the same way. /etc/resolv.conf
// (resolve.go) is generated unconditionally on every run and lands directly
// under it, with no intermediate directory to walk.
func TestResolvConfUnderAWholeEtcBindIsStillAllowed(t *testing.T) {
	p := mustResolveDefaults(t)
	if err := p.Validate(newFakeEnv()); err != nil {
		t.Fatalf("refused a default run — /etc granted whole, resolv.conf generated directly "+
			"under it: %v", err)
	}
}
