package policy

import (
	"fmt"
	"sort"
	"strings"
)

// GitMode says whether snug reconstructs the sandbox's git config from the
// host's.
//
// "Reconstructs", not "binds", and the distinction is the whole point.
// ~/.gitconfig is not a data file with a name and an email in it — it is a
// COMMAND TABLE. `credential.helper`, `alias.x = !cmd`, `core.pager`,
// `core.sshCommand`, `diff.*.textconv`, `filter.*.clean/smudge` and
// `core.fsmonitor` all name programs for git to run. Binding it read-only does
// not stop any of that; it SUPPLIES it. The previous `@git-ro` bound the file
// and said so in an abuse comment that called the hazard "secrets you unwisely
// put in ~/.gitconfig" — which reads as a user error, and understates a file
// whose keys are executable by design.
//
// So snug reads the host's config as DATA, keeps a whitelist of keys that carry
// no execution, and generates the file the sandbox sees. Deny-by-default applied
// to configuration keys instead of paths.
type GitMode uint8

const (
	// GitOff is the base state: the sandbox has no global git config beyond
	// whatever an [identity] block generates.
	GitOff GitMode = iota

	// GitExtract reconstructs user.name/user.email/init.defaultBranch from the
	// host's global config, honouring `includeIf "gitdir:"` against the target.
	GitExtract
)

func (m GitMode) Join(o GitMode) GitMode {
	if o > m {
		return o
	}
	return m
}

func (m GitMode) String() string {
	if m == GitExtract {
		return "extract"
	}
	return "off"
}

func ParseGitMode(s string) (GitMode, error) {
	switch s {
	case "", "off":
		return GitOff, nil
	case "extract":
		return GitExtract, nil
	default:
		return GitOff, fmt.Errorf("unknown git mode %q (want extract or off)", s)
	}
}

// GitKeyWhitelist is every key snug will carry from the host's git config into
// the sandbox's. Nothing on this list names a program, a file, or a credential.
//
// It is a WHITELIST and must stay one. The tempting additions are the signing
// keys — `user.signingkey`, `gpg.format`, `commit.gpgsign` — and they are
// deliberately absent: `commit.gpgsign = true` with a signing key that is not
// inside the sandbox turns every commit into a hard failure, which is worse
// than an unsigned commit. Signing needs the key staged AND the agent proxy
// willing to sign with it, and the proxy pins exactly one key today. See
// TODO.md; this list grows when that is built, not before.
var GitKeyWhitelist = []string{
	"user.name",
	"user.email",
	"init.defaultbranch",
}

// GitValues is the whitelisted subset of the host's resolved git config, keyed
// by the lowercase key name. The caller extracts it (that is filesystem work);
// this package only renders it.
type GitValues map[string]string

// GitConfigFrom renders the generated ~/.gitconfig for a GitExtract policy.
//
// An [identity] block always wins: identity is a PIN, and a value extracted
// from the host silently overriding a pinned one would make the pin advisory.
func GitConfigFrom(v GitValues, id *Identity) []byte {
	if len(v) == 0 && id == nil {
		return nil
	}
	// Second guard, deliberately not the only one. The extractor already drops a
	// value carrying a control character (cmd/snug/gitconfig.go), and this is the
	// backstop for whatever calls the renderer next — because the failure it
	// prevents is not cosmetic: a newline inside `user.name` closes the
	// `name = …` line and opens a real `[alias] x = !cmd` section in the file the
	// sandbox trusts. Measured by the red team, with the injected alias executing
	// inside the sandbox. Rendering is the last place this can be caught, so it
	// is caught here too.
	v = withoutControlCharacters(v)
	name, email := v["user.name"], v["user.email"]
	if id != nil {
		if id.GitName != "" {
			name = id.GitName
		}
		if id.GitEmail != "" {
			email = id.GitEmail
		}
	}

	var b strings.Builder
	b.WriteString("# Generated by snug from the host's git config. The host's file is not\n")
	b.WriteString("# mounted: it names programs to run (credential.helper, alias = !cmd,\n")
	b.WriteString("# core.pager, textconv), and a read-only bind supplies those rather than\n")
	b.WriteString("# stopping them. Only keys that carry no execution are carried over.\n")
	if name != "" || email != "" {
		b.WriteString("[user]\n")
		if name != "" {
			fmt.Fprintf(&b, "\tname = %s\n", name)
		}
		if email != "" {
			fmt.Fprintf(&b, "\temail = %s\n", email)
		}
	}
	if br := v["init.defaultbranch"]; br != "" {
		fmt.Fprintf(&b, "[init]\n\tdefaultBranch = %s\n", br)
	}
	if id != nil && id.SSHMode != SSHNone {
		host := id.host()
		fmt.Fprintf(&b, "[url \"git@%s:\"]\n\tinsteadOf = https://%s/\n", host, host)
	}
	b.WriteString("[safe]\n\tdirectory = *\n")
	return []byte(b.String())
}

// withoutControlCharacters drops any value that could author a directive rather
// than be one. A name, an email address and a branch name have no use for a
// control character, so there is nothing to weigh: the value goes.
func withoutControlCharacters(v GitValues) GitValues {
	out := make(GitValues, len(v))
	for k, val := range v {
		if strings.IndexFunc(val, func(r rune) bool { return r < 0x20 || r == 0x7f }) >= 0 {
			continue
		}
		out[k] = val
	}
	return out
}

// GitdirMatches reports whether an `includeIf "gitdir:<pattern>"` condition
// fires for a repository at gitDir.
//
// snug evaluates this ITSELF rather than asking git, and the reason is measured
// rather than stylistic. Asking git means running `git -C <target> config --get
// …`, which reads the TARGET's own config — so the repository being sandboxed
// chooses the identity, and the repository is the untrusted material. Measured:
// a repo that set only `user.email` in its own config won over the included
// file. And the other direction does not work either: `git config --global`
// never fires a `gitdir:` condition at all, because it has no repository to
// match against.
//
// `includeIf "hasconfig:remote.*.url:…"` is REFUSED, not implemented, and that
// is the sharpest reason this function exists. Measured on git 2.55: a repo
// whose only property was a crafted remote URL pulled in a host config file
// carrying `credential.helper = !command`. That condition lets the sandboxed
// material select which of your files is read — invariant 3, exactly.
//
// Pattern rules, from gitconfig(5):
//   - a leading `~/` is home-relative
//   - a pattern with no `/` at all is prefixed with `**/`
//   - a pattern ending in `/` gets `**` appended
//   - `**` matches across `/`; `*` does not
//   - `gitdir/i` is the case-insensitive spelling, handled by the caller
//     lowercasing both sides
func GitdirMatches(pattern, home, gitDir string) bool {
	if pattern == "" {
		return false
	}
	if strings.HasPrefix(pattern, "~/") {
		pattern = strings.TrimSuffix(home, "/") + pattern[1:]
	}
	if !strings.Contains(pattern, "/") {
		pattern = "**/" + pattern
	}
	if strings.HasSuffix(pattern, "/") {
		pattern += "**"
	}
	return wildMatch(pattern, gitDir)
}

// wildMatch is git's wildmatch with WM_PATHNAME, reduced to what a gitdir
// pattern can contain: `**` crossing separators, `*` and `?` not crossing them.
//
// Hand-written because path.Match has no `**` and the difference is exactly the
// case every real gitdir pattern uses.
func wildMatch(pattern, s string) bool {
	// Anchored at both ends, like git's.
	return matchHere([]rune(pattern), []rune(s))
}

func matchHere(p, s []rune) bool {
	for len(p) > 0 {
		switch p[0] {
		case '*':
			if len(p) > 1 && p[1] == '*' {
				// `**` crosses separators. Skip the run of stars and any `/`
				// immediately after it, which is how `a/**/b` also matches `a/b`.
				i := 0
				for i < len(p) && p[i] == '*' {
					i++
				}
				rest := p[i:]
				if len(rest) > 0 && rest[0] == '/' {
					if matchHere(rest[1:], s) {
						return true
					}
				}
				for j := 0; j <= len(s); j++ {
					if matchHere(rest, s[j:]) {
						return true
					}
				}
				return false
			}
			// A single `*` stops at a separator.
			for j := 0; j <= len(s); j++ {
				if j > 0 && s[j-1] == '/' {
					break
				}
				if matchHere(p[1:], s[j:]) {
					return true
				}
			}
			return false
		case '?':
			if len(s) == 0 || s[0] == '/' {
				return false
			}
			p, s = p[1:], s[1:]
		default:
			if len(s) == 0 || s[0] != p[0] {
				return false
			}
			p, s = p[1:], s[1:]
		}
	}
	return len(s) == 0
}

// SortedGitKeys is the whitelist in a stable order, for rendering and tests.
func SortedGitKeys() []string {
	out := append([]string(nil), GitKeyWhitelist...)
	sort.Strings(out)
	return out
}
