package policy

import (
	"fmt"
	"path"
	"sort"
	"strings"
)

// GitMode says whether snug reconstructs the sandbox's git config from the
// host's.
//
// "Reconstructs", not "binds", and the distinction is the whole point.
// ~/.gitconfig is not a data file with a name and an email in it — it is a
// COMMAND TABLE. `credential.helper`, `alias.x = !cmd`, `core.pager`,
// `core.sshCommand`, `diff.*.textconv`, `filter.*.clean/smudge` and
// `core.fsmonitor` all name programs for git to run. Binding it read-only does
// not stop any of that; it SUPPLIES it. The previous `@git-ro` bound the file
// and said so in an abuse comment that called the hazard "secrets you unwisely
// put in ~/.gitconfig" — which reads as a user error, and understates a file
// whose keys are executable by design.
//
// So snug reads the host's config as DATA, keeps a whitelist of keys that carry
// no execution, and generates the file the sandbox sees. Deny-by-default applied
// to configuration keys instead of paths.
type GitMode uint8

const (
	// GitOff is the base state: the sandbox has no global git config beyond
	// whatever an [identity] block generates.
	GitOff GitMode = iota

	// GitExtract reconstructs user.name/user.email/init.defaultBranch from the
	// host's global config, honouring `includeIf "gitdir:"` against the target.
	GitExtract
)

func (m GitMode) Join(o GitMode) GitMode {
	if o > m {
		return o
	}
	return m
}

func (m GitMode) String() string {
	if m == GitExtract {
		return "extract"
	}
	return "off"
}

func ParseGitMode(s string) (GitMode, error) {
	switch s {
	case "", "off":
		return GitOff, nil
	case "extract":
		return GitExtract, nil
	default:
		return GitOff, fmt.Errorf("unknown git mode %q (want extract or off)", s)
	}
}

// GitKeyWhitelist is every key snug will carry from the host's git config into
// the sandbox's. Nothing on this list names a program, a file, or a credential.
//
// It is a WHITELIST and must stay one. The tempting additions are the signing
// keys — `user.signingkey`, `gpg.format`, `commit.gpgsign` — and they are
// deliberately absent: `commit.gpgsign = true` with a signing key that is not
// inside the sandbox turns every commit into a hard failure, which is worse
// than an unsigned commit. Signing needs the key staged AND the agent proxy
// willing to sign with it, and the proxy pins exactly one key today. See
// https://github.com/gomoni/snug/issues/35; this list grows when that is built,
// not before.
var GitKeyWhitelist = []string{
	"user.name",
	"user.email",
	"init.defaultbranch",
}

// GitValues is the whitelisted subset of the host's resolved git config, keyed
// by the lowercase key name. The caller extracts it (that is filesystem work);
// this package only renders it.
type GitValues map[string]string

// GitConfigFrom renders the generated ~/.gitconfig for a GitExtract policy.
//
// An [identity] block always wins: identity is a PIN, and a value extracted
// from the host silently overriding a pinned one would make the pin advisory.
func GitConfigFrom(v GitValues, id *Identity) []byte {
	if len(v) == 0 && id == nil {
		return nil
	}
	// Second guard, deliberately not the only one. The extractor already drops a
	// value carrying a control character (internal/cli/gitconfig.go), and this is the
	// backstop for whatever calls the renderer next — because the failure it
	// prevents is not cosmetic: a newline inside `user.name` closes the
	// `name = …` line and opens a real `[alias] x = !cmd` section in the file the
	// sandbox trusts. Measured by the red team, with the injected alias executing
	// inside the sandbox. Rendering is the last place this can be caught, so it
	// is caught here too.
	v = withoutControlCharacters(v)
	name, email := v["user.name"], v["user.email"]
	if id != nil {
		if id.GitName != "" {
			name = id.GitName
		}
		if id.GitEmail != "" {
			email = id.GitEmail
		}
	}

	var b strings.Builder
	b.WriteString("# Generated by snug from the host's git config. The host's file is not\n")
	b.WriteString("# mounted: it names programs to run (credential.helper, alias = !cmd,\n")
	b.WriteString("# core.pager, textconv), and a read-only bind supplies those rather than\n")
	b.WriteString("# stopping them. Only keys that carry no execution are carried over.\n")
	if name != "" || email != "" {
		b.WriteString("[user]\n")
		if name != "" {
			fmt.Fprintf(&b, "\tname = %s\n", gitQuote(name))
		}
		if email != "" {
			fmt.Fprintf(&b, "\temail = %s\n", gitQuote(email))
		}
	}
	if br := v["init.defaultbranch"]; br != "" {
		fmt.Fprintf(&b, "[init]\n\tdefaultBranch = %s\n", gitQuote(br))
	}
	if id != nil && id.SSHMode != SSHNone {
		host := id.host()
		fmt.Fprintf(&b, "[url \"git@%s:\"]\n\tinsteadOf = https://%s/\n", host, host)
	}
	b.WriteString("[safe]\n\tdirectory = *\n")
	return []byte(b.String())
}

// gitQuote renders a value the way git's own writer does: always quoted, with
// `\` and `"` escaped.
//
// Dropping control characters was only half of it. git's config VALUE syntax has
// four more characters that change meaning, and writing values raw got every one
// of them wrong — measured, host value in, sandbox value out:
//
//	A " B        ->  name = A " B        ->  fatal: bad config line 2
//	Bob # Smith  ->  name = Bob # Smith  ->  Bob        (comment)
//	Bob ; Smith  ->  name = Bob ; Smith  ->  Bob        (comment)
//	"  Bob"      ->  name =   Bob        ->  Bob        (leading space eaten)
//	C:\temp      ->  name = C:\temp      ->  C:<TAB>emp (escape re-read)
//
// The quote case is the sharp one, and it is a total failure rather than a
// cosmetic one: GIT_CONFIG_GLOBAL points at the generated file, so a `"` in the
// host's user.name makes `git version` itself die inside the sandbox, naming a
// file the human never wrote. Quoting is the fix; adding more characters to the
// drop list is not, because a name legitimately containing `"` is a person's
// name and not an attack.
func gitQuote(v string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(v); i++ {
		switch c := v[i]; c {
		case '\\', '"':
			b.WriteByte('\\')
			b.WriteByte(c)
		default:
			b.WriteByte(c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// withoutControlCharacters drops any value that could author a directive rather
// than be one. A name, an email address and a branch name have no use for a
// control character, so there is nothing to weigh: the value goes.
//
// THE ASCII SCOPE IS DELIBERATE AND IS NOT THE SCREEN'S SCOPE. This filter and
// IsForgingRune answer two different questions, and a reader arriving from the
// widened screen guard will want to widen this one out of symmetry. Do not.
//
//   - THIS one asks: can the rune author a DIRECTIVE in the file snug writes?
//     git's config parser terminates a value at a NEWLINE and starts a section
//     at a `[` in column one; nothing else in the grammar is a terminator.
//     U+0085, U+2028 and U+202E are ordinary bytes to it — measured shape, and
//     the same reason `gitQuote` handles `"`, `#`, `;` and `\` rather than this
//     function. So C0 and DEL already cover every rune that can end a line, and
//     the extra ones a wider predicate would add close nothing here.
//   - THE SCREEN asks: can the rune make a rendered line read as something snug
//     did not write? That is IsForgingRune, and it IS wider — but its remedy is
//     to ESCAPE at the sink (policy.VisibleText, internal/cli/gitconfig.go's
//     gitValuesLine), not to drop the value.
//
// The difference matters because THIS function's remedy is a DROP, and a drop is
// a downgrade: a user.name legitimately carrying a directional isolate — a
// mixed-direction personal name is the normal case for one, not an attack — would
// leave the sandbox with no git identity and `git commit` failing, which is the
// same shape as the whitelist's deliberate omission of commit.gpgsign. Widening
// a filter whose remedy is "the value goes" costs a working sandbox; widening a
// guard whose remedy is "the value is escaped" costs nothing.
func withoutControlCharacters(v GitValues) GitValues {
	out := make(GitValues, len(v))
	for k, val := range v {
		if strings.IndexFunc(val, func(r rune) bool { return r < 0x20 || r == 0x7f }) >= 0 {
			continue
		}
		out[k] = val
	}
	return out
}

// negatedClasses rewrites `[!…]` as `[^…]`.
//
// wildmatch accepts both spellings for a negated character class and path.Match
// accepts only `^`, so `gitdir:~/w[!x]rk/` matched in git and not in snug — the
// silent direction, where the sandbox falls back to the global identity. Found
// by the oracle test, which is exactly the class of divergence a hand-written
// table does not think of.
func negatedClasses(p string) string {
	var b strings.Builder
	inClass := false
	for i := 0; i < len(p); i++ {
		c := p[i]
		switch {
		case c == '\\' && i+1 < len(p):
			b.WriteByte(c)
			i++
			b.WriteByte(p[i])
			continue
		case c == '[':
			inClass = true
			b.WriteByte(c)
			if i+1 < len(p) && p[i+1] == '!' {
				b.WriteByte('^')
				i++
			}
			continue
		case c == ']':
			inClass = false
		}
		b.WriteByte(c)
	}
	_ = inClass
	return b.String()
}

// GitdirMatches reports whether an `includeIf "gitdir:<pattern>"` condition
// fires for a repository at gitDir.
//
// snug evaluates this ITSELF rather than asking git, and the reason is measured
// rather than stylistic. Asking git means running `git -C <target> config --get
// …`, which reads the TARGET's own config — so the repository being sandboxed
// chooses the identity, and the repository is the untrusted material. Measured:
// a repo that set only `user.email` in its own config won over the included
// file. And the other direction does not work either: `git config --global`
// never fires a `gitdir:` condition at all, because it has no repository to
// match against.
//
// `includeIf "hasconfig:remote.*.url:…"` is REFUSED, not implemented, and that
// is the sharpest reason this function exists. Measured on git 2.55: a repo
// whose only property was a crafted remote URL pulled in a host config file
// carrying `credential.helper = !command`. That condition lets the sandboxed
// material select which of your files is read — invariant 3, exactly.
//
// Pattern rules, from gitconfig(5):
//   - a leading `~/` is home-relative
//   - a pattern with no `/` at all is prefixed with `**/`
//   - a pattern ending in `/` gets `**` appended
//   - `**` matches across `/`; `*` does not
//   - `gitdir/i` is the case-insensitive spelling, handled by the caller
//     lowercasing both sides
func GitdirMatches(pattern, home, gitDir string) bool {
	if pattern == "" {
		return false
	}
	// The prefix forms, from gitconfig(5). The `**/` rule is ANY pattern that
	// does not start with `~/`, `./` or `/` — not, as an earlier version of this
	// function and its comment both had it, "a pattern with no `/` at all".
	// `gitdir:work/` is the plainest relative pattern there is, and it silently
	// never fired.
	switch {
	case strings.HasPrefix(pattern, "~/"):
		pattern = strings.TrimSuffix(home, "/") + pattern[1:]
	case strings.HasPrefix(pattern, "./"):
		// Relative to the directory of the file the condition was written in.
		// The caller has already resolved include paths, so what is left here is
		// treated like any other relative pattern.
		pattern = "**/" + pattern[2:]
	case !strings.HasPrefix(pattern, "/"):
		pattern = "**/" + pattern
	}
	if strings.HasSuffix(pattern, "/") {
		pattern += "**"
	}
	return wildMatch(pattern, gitDir)
}

// wildMatch is git's wildmatch under WM_PATHNAME, done over path COMPONENTS.
//
// The component split is the point, and it fixes two defects in the
// character-by-character matcher it replaces. `**` crosses `/` ONLY when it is a
// whole component — preceded by the start or a `/`, and followed by a `/` or the
// end. Anywhere else (`a**b`) git degrades it to `*`, which does not cross. The
// old version let every `**` cross, so `~/**work/` matched `~/a/xwork/proj`
// where git does not: the sandbox then commits under an identity the host would
// not use, silently.
//
// It also removes an exponential case. The old recursive matcher retried every
// suffix per `**` group and took 3 seconds on `/**a**a**a**b` against a
// 400-component path, and did not finish with one more group. This is a
// dynamic-programming sweep: linear in pattern components times path components.
//
// Each non-`**` component goes to path.Match, which implements exactly what
// wildmatch does WITHIN a component — `*`, `?`, `[...]` classes with `!`
// negation, and `\` escapes — and never crosses a separator.
func wildMatch(pattern, s string) bool {
	pat := strings.Split(pattern, "/")
	str := strings.Split(s, "/")

	// reach[j] reports whether the pattern components handled so far can consume
	// exactly the first j components of the path.
	reach := make([]bool, len(str)+1)
	reach[0] = true

	for _, pc := range pat {
		next := make([]bool, len(str)+1)
		if pc == "**" {
			// Zero or more components: once a position is reachable, every later
			// one is too.
			seen := false
			for j := 0; j <= len(str); j++ {
				if reach[j] {
					seen = true
				}
				next[j] = seen
			}
		} else {
			// Not a whole component, so a `**` inside it is git's degraded `*`.
			pc := negatedClasses(strings.ReplaceAll(pc, "**", "*"))
			for j := 0; j < len(str); j++ {
				if !reach[j] {
					continue
				}
				if ok, err := path.Match(pc, str[j]); err == nil && ok {
					next[j+1] = true
				}
			}
		}
		reach = next
	}
	return reach[len(str)]
}

// SortedGitKeys is the whitelist in a stable order, for rendering and tests.
func SortedGitKeys() []string {
	out := append([]string(nil), GitKeyWhitelist...)
	sort.Strings(out)
	return out
}
