package policy

import "fmt"

// SSHMode says how (and whether) the sandbox can use an ssh key.
type SSHMode string

const (
	// SSHAgentProxy is the recommendation for every real workflow: a filtering
	// proxy to the host's ALREADY-UNLOCKED agent, exposing exactly one key. No
	// key material inside, no passphrase prompt, other keys not enumerable.
	SSHAgentProxy SSHMode = "agent-proxy"

	// SSHHostAgent forwards the whole host agent — every key, no filtering.
	// Requires --i-know.
	SSHHostAgent SSHMode = "host-agent"

	SSHNone SSHMode = "none"
)

func ParseSSHMode(s string) (SSHMode, error) {
	switch SSHMode(s) {
	case SSHAgentProxy, SSHHostAgent, SSHNone:
		return SSHMode(s), nil
	case "":
		return SSHNone, nil
	default:
		return "", fmt.Errorf("unknown ssh_mode %q (want agent-proxy, host-agent or none)", s)
	}
}

// Identity pins the sandbox to exactly one git/ssh/gh account.
//
// The point is not secrecy — it is blast radius. An agent that can sign with
// one key can push as that account and no other, and `gh api user` answers with
// that account and no other. Without pinning, "the agent has ssh" means "the
// agent is you, everywhere".
type Identity struct {
	// SSHKey is the PUBLIC key file that pins the identity. Only the public
	// half is read; the private key never leaves the host agent.
	SSHKey  string
	SSHMode SSHMode

	GitName  string
	GitEmail string

	GhUser string
	GhHost string // default github.com
}

// CheckText refuses a control character in any identity field.
//
// The same rule as checkEnvValue, at a sink that did not exist when it was
// written — and it is load-bearing rather than defensive, because every one of
// these fields is interpolated into a CONFIG FILE snug generates. With \u000A
// spelled as an escape, which is the only spelling go-toml accepts:
//
//	git_name = "x\u000A[core]\u000A\tsshCommand = curl ... | sh"
//	gh_host  = "a\u000Ab: {oauth_token: ...}"
//
// The first writes a git directive into ~/.gitconfig; the second a second host
// entry into gh's hosts.yml. Neither is a Mount, so Validate, rejectMasking and
// the provenance model are all blind to it — the same shape as the NUL in
// environ.set, one layer over. gh_user and gh_host additionally reach a terminal
// through the no-token refusal, where ESC[1A CR forges a `snug:` line.
//
// A raw control character never survives go-toml in a basic string; the \u
// escape does, which is what anyone re-testing this needs.
//
// The verdict is a property of the profile text, so it is the same on every host
// and belongs beside resolution rather than in a renderer.
func (i *Identity) CheckText(profileName string) error {
	if i == nil {
		return nil
	}
	for _, f := range []struct{ key, val string }{
		{"ssh_key", i.SSHKey},
		{"ssh_mode", string(i.SSHMode)},
		{"git_name", i.GitName},
		{"git_email", i.GitEmail},
		{"gh_user", i.GhUser},
		{"gh_host", i.GhHost},
	} {
		for j := 0; j < len(f.val); j++ {
			if c := f.val[j]; c < 0x20 || c == 0x7f {
				return fmt.Errorf("profile %q: identity.%s contains %q. Every identity field is "+
					"interpolated into a config file snug GENERATES — ~/.gitconfig, ~/.ssh/config, "+
					"gh's hosts.yml — so a control character writes a directive snug did not "+
					"author, and none of it is a Mount that Validate could refuse. Remove it",
					profileName, f.key, string(c))
			}
		}
	}
	return nil
}

// GitConfig is the generated ~/.gitconfig.
//
// The insteadOf rule rewrites https://github.com/ to the ssh form so a push
// goes over the pinned key rather than prompting for a token that the sandbox
// does not have. Without it, `git push` on an https remote hangs on a
// credential prompt that no one can answer.
func (i *Identity) GitConfig() []byte {
	if i == nil {
		return nil
	}
	host := i.host()
	out := []byte("# Generated by snug. The host's ~/.gitconfig is not mounted.\n")
	if i.GitName != "" || i.GitEmail != "" {
		out = append(out, "[user]\n"...)
		if i.GitName != "" {
			out = fmt.Appendf(out, "\tname = %s\n", i.GitName)
		}
		if i.GitEmail != "" {
			out = fmt.Appendf(out, "\temail = %s\n", i.GitEmail)
		}
	}
	if i.SSHMode != SSHNone {
		out = fmt.Appendf(out, "[url \"git@%s:\"]\n\tinsteadOf = https://%s/\n", host, host)
	}
	out = append(out, "[safe]\n\tdirectory = *\n"...)
	return out
}

// PubKeyGuest is where the pinned PUBLIC key is staged inside the sandbox.
const PubKeyGuest = ".ssh/id_snug.pub"

// SSHConfig is the generated ~/.ssh/config.
//
// IdentityFile pointing at a .pub is the standard way to make ssh select
// exactly one agent identity, and it is REQUIRED here rather than decorative:
// `IdentitiesOnly yes` with no IdentityFile tells ssh to use only the
// identities named in the config, and naming none can leave it declining to
// offer the agent's key at all. The previous generation of this project staged
// the .pub for exactly this reason; an earlier draft of snug set
// IdentitiesOnly without it and would have broken agent auth.
//
// Only the public half is ever staged. The private key stays in the host agent.
func (i *Identity) SSHConfig(home string) []byte {
	if i == nil || i.SSHMode == SSHNone {
		return nil
	}
	return fmt.Appendf(nil,
		"# Generated by snug. The host's ~/.ssh is not mounted.\n"+
			"Host %s\n"+
			"\tUser git\n"+
			"\tIdentitiesOnly yes\n"+
			"\tIdentityFile %s/%s\n"+
			"\tStrictHostKeyChecking accept-new\n"+
			"\tUserKnownHostsFile %s/.ssh/known_hosts\n",
		i.host(), home, PubKeyGuest, home)
}

// SystemSSHConfigPaths are the system-wide ssh_config locations snug replaces
// when an identity is pinned. Both spellings ship in the wild: the traditional
// /etc/ssh, and /usr/etc/ssh on distributions that moved the vendor copy out of
// /etc (openSUSE). Only paths that exist on the host are replaced — snug does
// not invent a config file at a path this host's ssh would never read.
var SystemSSHConfigPaths = []string{
	"/etc/ssh/ssh_config",
	"/usr/etc/ssh/ssh_config",
}

// SystemSSHConfig is the generated replacement for the system-wide ssh_config.
//
// WHY THIS EXISTS, measured rather than reasoned: the sandbox maps exactly one
// uid, so every root-owned file under the read-only /usr bind reads as 65534
// inside it. OpenSSH refuses to use a configuration file owned by neither root
// nor the invoking user, and the refusal is fatal rather than a warning:
//
//	$ git clone git@github.com:owner/repo.git
//	Bad owner or permissions on /usr/etc/ssh/ssh_config.d/50-suse.conf
//
// So ssh — and therefore git-over-ssh, which is the whole point of pinning an
// identity — did not work inside snug at all on such a host. `ssh -F <file>`
// works, because -F makes ssh skip the system-wide file entirely; that is the
// same escape this replacement takes, applied once by snug instead of relying
// on every caller to pass a flag.
//
// This is a REPLACEMENT, not masking: snug authors it, the sandbox still sees a
// file at that path, and no profile's grant is subtracted (CLAUDE.md, "PATH
// precedence, not overmounting"). It appears in --dry-run as a `data` row with
// `identity:<profile>` provenance, like the generated ~/.gitconfig.
//
// What it costs, stated plainly: the host's system-wide ssh defaults do not
// apply inside the sandbox. On this host that is openSUSE's crypto-policy
// include; ssh's compiled-in defaults are used instead. That is the correct
// trade for a sandbox — the alternative was ssh not running.
func (i *Identity) SystemSSHConfig() []byte {
	if i == nil || i.SSHMode == SSHNone {
		return nil
	}
	return []byte("# Generated by snug, replacing this host's system-wide ssh_config.\n" +
		"#\n" +
		"# The host's copy is owned by root, which reads as uid 65534 inside the\n" +
		"# sandbox's user namespace, and OpenSSH refuses a config file owned by\n" +
		"# neither root nor the caller. It has no Include line for the same reason:\n" +
		"# every file it would pull in is root-owned too.\n" +
		"#\n" +
		"# Per-host settings for the pinned identity are in ~/.ssh/config, also\n" +
		"# generated by snug. ssh's compiled-in defaults apply to everything else.\n")
}

func (i *Identity) host() string {
	if i == nil || i.GhHost == "" {
		return "github.com"
	}
	return i.GhHost
}
