package sandbox

import (
	"golang.org/x/sys/unix"

	"github.com/gomoni/snug/internal/policy"
)

// terminalWillDeliver reports whether a signal generated by the CONTROLLING
// TERMINAL — the operator's Ctrl-C — reaches the payload on its own, without
// snug relaying anything.
//
// It exists so that the grace in teardownGuard.wait relays a signal exactly
// where the terminal could not have. Go's os/signal carries no si_code, so
// "was this signal from a tty or from kill(2)" is not knowable from the signal
// itself; these three facts ARE knowable, and they err in the safe direction —
// a false "no" costs a duplicate that never happens, a false "yes" costs the
// payload its handler, and only the first is silent.
//
// ALL THREE must hold, and each is a separate way for the answer to be no:
//
//  1. bwrap was not passed --new-session. It calls setsid(), which puts the
//     payload in a session of its own with no controlling terminal, so no tty
//     can signal it. policy.NewSession() decides this, and it is true whenever
//     legacy_tiocsti is non-zero OR none of stdio is a terminal
//     (internal/policy/newsession.go) — so on a host where TIOCSTI still
//     exists the session is cut even with a terminal present.
//  2. one of stdio is a terminal and answers TIOCGPGRP. Without a controlling
//     terminal there is nothing to generate a signal in the first place.
//  3. that terminal's FOREGROUND process group is this process's own. A snug
//     running as a background job is not who the tty signals; `bash -c 'snug
//     … &'` is exactly that shape, and it is also where the payload used to
//     inherit SIG_IGN (see internal/sigseal).
//
// MEASURED on this host, which is what (1) and (3) are written from. With the
// session shared and snug in the foreground, a ^C on the pty fires the
// payload's own trap. With --new-session emitted, a SIGINT to the WHOLE of
// snug's process group does not reach the payload at all:
//
//	snug 332607 -> bwrap 332620 -> bwrap 332626 -> sh 332630   all pgrp=332607
//	snug 337522 -> bwrap 337535 (pgrp 337522)
//	            -> bwrap 337541 (pgrp/sid 337541) -> sh 337542
//
// THE RESIDUAL, stated because it is the one case this predicate gets
// deliberately wrong: `kill -INT <snug>` sent to snug ALONE while snug is a
// foreground tty job answers true here, so nothing is relayed and the payload
// never sees that signal. It costs the payload its handler and costs the
// operator payloadGraceBudget of waiting for an exit that is not coming. The
// alternative is relaying on every path and double-delivering every real ^C,
// which turns one keypress into the two that mean "force quit" to compose,
// npm, pytest and vite. A duplicate that changes behaviour beats a delay that
// does not.
func terminalWillDeliver(p *policy.Policy) bool {
	if p.NewSession() {
		return false
	}
	self := unix.Getpgrp()
	for _, fd := range []int{0, 1, 2} {
		fg, err := unix.IoctlGetInt(fd, unix.TIOCGPGRP)
		if err != nil {
			// Not a terminal, or a terminal this process does not control.
			// Either way it is not a route to the payload; try the next.
			continue
		}
		if fg == self {
			return true
		}
	}
	return false
}
