package cli

import (
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"slices"
	"strings"
	"testing"

	"github.com/gomoni/snug/internal/profile"
)

// bookBuiltinsPath is the user guide's page listing every builtin profile.
const bookBuiltinsPath = "../../docs/src/builtins.md"

// TestBookBuiltinsPageIsGenerated renders docs/src/builtins.md from `snug
// profile show` for every builtin and compares it with the committed page.
//
// The page is the command's output, not a description of it: a builtin added,
// removed or changed moves the page in the same diff, and there is no prose in
// it that could say something the command does not. Regenerate with
//
//	go test ./internal/cli -run TestBookBuiltinsPageIsGenerated -update
func TestBookBuiltinsPageIsGenerated(t *testing.T) {
	reg, err := profile.Builtins()
	if err != nil {
		t.Fatal(err)
	}
	var b strings.Builder
	b.WriteString("<!-- GENERATED by TestBookBuiltinsPageIsGenerated (internal/cli/bookbuiltins_test.go)\n" +
		"     from `snug profile show`. Do not edit; regenerate with -update. -->\n\n")
	b.WriteString("# Built-in profiles\n\n")
	b.WriteString("Profiles snug ships. Each section is the output of `snug profile show NAME`.\n")
	b.WriteString("`snug --dry-run -p NAME DIR` shows what one produces for a directory.\n")
	var defaults []string
	for _, n := range profile.BuiltinDefaults() {
		defaults = append(defaults, "`"+string(n)+"`")
	}
	b.WriteString("\nEvery run starts with " + strings.Join(defaults, " ") + ", unless `config.toml` or\n" +
		"`--no-defaults` changes that. See [Selecting profiles](configuration.md#selecting-profiles).\n")
	for _, name := range sortedNames(reg) {
		out, code := showGolden(t, string(name))
		if code != 0 {
			t.Fatalf("snug profile show %s exited %d:\n%s", name, code, out)
		}
		b.WriteString("\n## `" + string(name) + "`\n\n```text\n")
		b.WriteString(strings.TrimRight(out, "\n"))
		b.WriteString("\n```\n")
	}
	got := b.String()

	if *update {
		if err := os.WriteFile(bookBuiltinsPath, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(bookBuiltinsPath)
	if err != nil {
		t.Fatalf("%v\n  generate it: go test ./internal/cli -run TestBookBuiltinsPageIsGenerated -update", err)
	}
	if string(want) != got {
		t.Errorf("%s is stale: a builtin profile changed and the page did not.\n"+
			"  regenerate: go test ./internal/cli -run TestBookBuiltinsPageIsGenerated -update\n"+
			"  and read the diff: it is the change in what a builtin grants", filepath.Clean(bookBuiltinsPath))
	}
}

// TestBookConfigTableListsEveryKey compares the config.toml key table in
// docs/src/configuration.md with userConfig's keys, in both directions.
func TestBookConfigTableListsEveryKey(t *testing.T) {
	const page = "../../docs/src/configuration.md"
	data, err := os.ReadFile(page)
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	i := strings.Index(text, "## `config.toml`")
	if i < 0 {
		t.Fatalf("%s has no \"## `config.toml`\" section; this test grades its key table", page)
	}
	var documented []string
	for _, m := range regexp.MustCompile("(?m)^\\| `([a-z_]+)` \\|").FindAllStringSubmatch(text[i:], -1) {
		documented = append(documented, m[1])
	}
	var accepted []string
	ty := reflect.TypeOf(userConfig{})
	for i := range ty.NumField() {
		if tag := ty.Field(i).Tag.Get("toml"); tag != "" {
			accepted = append(accepted, tag)
		}
	}
	for _, k := range accepted {
		if !slices.Contains(documented, k) {
			t.Errorf("%s does not list config key %q", page, k)
		}
	}
	for _, k := range documented {
		if !slices.Contains(accepted, k) {
			t.Errorf("%s lists config key %q, which config.toml refuses", page, k)
		}
	}
}
