package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gomoni/snug/internal/policy"
	"github.com/gomoni/snug/internal/profile"
)

// ── the review artifact for @claude's bwrap argv ─────────────────────────────
//
// internal/policy/testdata/*.bwrap.txt is where a resolved policy's exact
// bwrap argv is pinned (internal/policy/bwrap_test.go's TestGoldenBwrapArgs),
// and bwrapnotegolden_test.go says so directly: "the real argv already has
// its own review artifact in internal/policy/testdata/*.bwrap.txt". But that
// table's registry is a FAKE one (testRegistry(), internal/policy/resolve_test.go)
// standing in for the shipped profiles, and @claude is not in it — the profile
// with the largest credential surface (a staged Anthropic OAuth token, and
// host paths mounted in) is the one profile whose argv nobody has ever diffed
// (issue #71).
//
// @claude cannot be added as just another row of that table, though, because
// its most security-relevant mounts are not something internal/policy's
// Resolve produces at all: ~/.claude/settings.json is generated by
// stageClaudeSettings (claude.go) from a host file read AFTER Resolve
// returns, and ~/.claude.json is generated by claudeStateJSON the same way.
// Both are injected into the policy with Policy.Replace, exactly the
// machinery claudeblockgolden_test.go already exercises for the CLAUDE
// block. This golden reuses THAT mechanism (profile.Builtins(), the real
// claudeFiles staging, a fake host so the file is stable) rather than
// inventing a second fake-registry entry that could only ever pin half of
// what the profile hands over — see TestClaudeArgvGoldenWouldHaveCaughtPR74's
// comment for the measurement that a fake-registry-only golden misses.
//
// goldenFormat is duplicated from internal/policy/bwrap_test.go rather than
// exported from it, for the same reason envFakeEnv is duplicated from
// internal/policy's fakeEnv in envgolden_test.go: a test fixture that has to
// live in non-test code is one something other than a test could reach.
func goldenFormat(args []string) string {
	var b strings.Builder
	for i, a := range args {
		if strings.HasPrefix(a, "--") && i > 0 {
			b.WriteString("\n")
		} else if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString(a)
	}
	b.WriteString("\n")
	return b.String()
}

// TestGoldenClaudeArgv pins the bwrap argv for `snug -p @claude`, resolved
// against the REAL builtin profiles (profile.Builtins()) with the fake host
// envgolden_test.go already uses for env.claude.txt and the fake trust-dialog
// host claudeblockgolden_test.go uses for the trusted arm, so this file needs
// no third fixture.
//
// ONE GOLDEN, NOT TWO, even though claudeblockgolden_test.go's CLAUDE block
// has an untrusted and a trusted arm. TestClaudeArgvIsByteIdenticalAcrossTrustArms
// below is the control that justifies this: the trust decision and the
// settings-filter decision change the CONTENT of two mounts snug generates,
// never the PATH or the mount COUNT, and bwrap's argv carries paths and
// placeholder fd numbers, never content — so the two arms produce the exact
// same argv. The content-level diff between the arms has its own review
// artifact already (claude-block.txt / claude-block-trusted.txt); pinning it
// a second time here would only make an unrelated content change look like an
// argv change.
func TestGoldenClaudeArgv(t *testing.T) {
	reg, err := profile.Builtins()
	if err != nil {
		t.Fatal(err)
	}
	sel := append(append([]policy.ProfileName{}, profile.BuiltinDefaults()...), "@claude")
	ctx := envGoldenCtx()

	p, err := policy.Resolve(map[policy.ProfileName]*policy.Profile(reg), sel, ctx, newEnvFakeEnv())
	if err != nil {
		t.Fatalf("Resolve(%v): %v", sel, err)
	}
	// The real staging code, against the fake host's home — same call
	// claudeblockgolden_test.go makes for the untrusted arm. /home/u does not
	// exist, so the credentials copy is skipped and ~/.claude.json carries no
	// trust entry, but ~/.claude/settings.json is still generated
	// unconditionally (issue #17) and is exactly the mount PR #74 added.
	if err := claudeFiles(p, ctx.Home, nil); err != nil {
		t.Fatalf("claudeFiles: %v", err)
	}
	// CONTROL: the two mounts PR #74 is about must really be in the policy, or
	// this golden pins an argv that says nothing about the change it exists to
	// catch.
	if _, ok := p.Mounts[filepath.Join(ctx.Home, ".claude.json")]; !ok {
		t.Fatal("control: nothing staged at ~/.claude.json — this golden would pin an argv " +
			"that never exercises claudeFiles' generated mounts")
	}
	if _, ok := claudeSettingsMount(p); !ok {
		t.Fatal("control: nothing staged at ~/.claude/settings.json — it is unconditional " +
			"(issue #17); its absence here means stageClaudeSettings silently stopped running " +
			"rather than that this golden has an argv to pin")
	}

	got := goldenFormat(p.BwrapArgs(1000, 1000))

	path := filepath.Join("testdata", "bwrap.claude.txt")
	if *update {
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%v (run: go test ./internal/cli -update)", err)
	}
	if got != string(want) {
		t.Errorf("@claude's bwrap argv changed — this is a change to what the profile with the "+
			"largest credential surface hands the sandbox. Read this diff as a change to the "+
			"security boundary, not as a refactor.\n--- got\n%s\n--- want\n%s", got, want)
	}
}

// TestClaudeArgvDoesNotVaryWithMountContent is the control for
// TestGoldenClaudeArgv shipping ONE golden: bwrap's argv carries paths, modes
// and fd numbers, never the bytes behind a KindData mount, so a golden argv
// cannot pin content and does not need an arm per content.
//
// It used to drive the two TRUST arms — host trusts the target versus host does
// not — and that subject is gone: since issue #460 the trust entry is written
// unconditionally and there is one arm. The premise it was really checking is
// the one above, so it is checked directly, with the largest KindData file
// @claude authors standing in for all of them.
func TestClaudeArgvDoesNotVaryWithMountContent(t *testing.T) {
	reg, err := profile.Builtins()
	if err != nil {
		t.Fatal(err)
	}
	sel := append(append([]policy.ProfileName{}, profile.BuiltinDefaults()...), "@claude")
	ctx := envGoldenCtx()

	argv := func(t *testing.T, content string) []string {
		t.Helper()
		p, err := policy.Resolve(map[policy.ProfileName]*policy.Profile(reg), sel, ctx, newEnvFakeEnv())
		if err != nil {
			t.Fatalf("Resolve(%v): %v", sel, err)
		}
		if err := claudeFiles(p, ctx.Home, nil); err != nil {
			t.Fatalf("claudeFiles: %v", err)
		}
		guest := filepath.Join(ctx.Home, ".claude.json")
		m, ok := p.Mounts[guest]
		if !ok {
			t.Fatalf("control: nothing staged at %s, so this test would compare two "+
				"identical policies and prove nothing", guest)
		}
		m.Content = policy.Secret(content)
		p.Replace(m)
		return p.BwrapArgs(1000, 1000)
	}

	// Two documents of DIFFERENT lengths: --ro-bind-data/--file carry an fd
	// number and a path, and a length that reached the argv would show here.
	short := argv(t, "{}\n")
	long := argv(t, `{"autoUpdates":false,"hasCompletedOnboarding":true,"projects":{}}`+"\n")

	if strings.Join(short, "\x00") != strings.Join(long, "\x00") {
		t.Errorf("the bwrap argv differs between two ~/.claude.json contents — this test's "+
			"premise (bwrap carries paths and fd numbers, never mount content) no longer "+
			"holds, and TestGoldenClaudeArgv needs a golden per content.\n--- short\n%s"+
			"\n--- long\n%s", goldenFormat(short), goldenFormat(long))
	}
}
