package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gomoni/snug/internal/policy"
	"github.com/gomoni/snug/internal/profile"
)

// ── the review artifact for @claude's bwrap argv ─────────────────────────────
//
// internal/policy/testdata/*.bwrap.txt is where a resolved policy's exact
// bwrap argv is pinned (internal/policy/bwrap_test.go's TestGoldenBwrapArgs),
// and bwrapnotegolden_test.go says so directly: "the real argv already has
// its own review artifact in internal/policy/testdata/*.bwrap.txt". But that
// table's registry is a FAKE one (testRegistry(), internal/policy/resolve_test.go)
// standing in for the shipped profiles, and @claude is not in it — the profile
// with the largest credential surface (a staged Anthropic OAuth token, and
// host paths mounted in) is the one profile whose argv nobody has ever diffed
// (issue #71).
//
// @claude cannot be added as just another row of that table, though, because
// its most security-relevant mounts are not something internal/policy's
// Resolve produces at all: ~/.claude/settings.json is generated by
// stageClaudeSettings (claude.go) from a host file read AFTER Resolve
// returns, and ~/.claude.json is generated by claudeStateJSON the same way.
// Both are injected into the policy with Policy.Replace, exactly the
// machinery claudeblockgolden_test.go already exercises for the CLAUDE
// block. This golden reuses THAT mechanism (profile.Builtins(), the real
// claudeFiles staging, a fake host so the file is stable) rather than
// inventing a second fake-registry entry that could only ever pin half of
// what the profile hands over — see TestClaudeArgvGoldenWouldHaveCaughtPR74's
// comment for the measurement that a fake-registry-only golden misses.
//
// goldenFormat is duplicated from internal/policy/bwrap_test.go rather than
// exported from it, for the same reason envFakeEnv is duplicated from
// internal/policy's fakeEnv in envgolden_test.go: a test fixture that has to
// live in non-test code is one something other than a test could reach.
func goldenFormat(args []string) string {
	var b strings.Builder
	for i, a := range args {
		if strings.HasPrefix(a, "--") && i > 0 {
			b.WriteString("\n")
		} else if i > 0 {
			b.WriteString(" ")
		}
		b.WriteString(a)
	}
	b.WriteString("\n")
	return b.String()
}

// TestGoldenClaudeArgv pins the bwrap argv for `snug -p @claude`, resolved
// against the REAL builtin profiles (profile.Builtins()) with the fake host
// envgolden_test.go already uses for env.claude.txt and the fake trust-dialog
// host claudeblockgolden_test.go uses for the trusted arm, so this file needs
// no third fixture.
//
// ONE GOLDEN, NOT TWO, even though claudeblockgolden_test.go's CLAUDE block
// has an untrusted and a trusted arm. TestClaudeArgvIsByteIdenticalAcrossTrustArms
// below is the control that justifies this: the trust decision and the
// settings-filter decision change the CONTENT of two mounts snug generates,
// never the PATH or the mount COUNT, and bwrap's argv carries paths and
// placeholder fd numbers, never content — so the two arms produce the exact
// same argv. The content-level diff between the arms has its own review
// artifact already (claude-block.txt / claude-block-trusted.txt); pinning it
// a second time here would only make an unrelated content change look like an
// argv change.
func TestGoldenClaudeArgv(t *testing.T) {
	reg, err := profile.Builtins()
	if err != nil {
		t.Fatal(err)
	}
	sel := append(append([]policy.ProfileName{}, profile.BuiltinDefaults()...), "@claude")
	ctx := envGoldenCtx()

	p, err := policy.Resolve(map[policy.ProfileName]*policy.Profile(reg), sel, ctx, newEnvFakeEnv())
	if err != nil {
		t.Fatalf("Resolve(%v): %v", sel, err)
	}
	// The real staging code, against the fake host's home — same call
	// claudeblockgolden_test.go makes for the untrusted arm. /home/u does not
	// exist, so the credentials copy is skipped and ~/.claude.json carries no
	// trust entry, but ~/.claude/settings.json is still generated
	// unconditionally (issue #17) and is exactly the mount PR #74 added.
	claudeFiles(p, ctx.Home, false)

	// CONTROL: the two mounts PR #74 is about must really be in the policy, or
	// this golden pins an argv that says nothing about the change it exists to
	// catch.
	if _, ok := p.Mounts[filepath.Join(ctx.Home, ".claude.json")]; !ok {
		t.Fatal("control: nothing staged at ~/.claude.json — this golden would pin an argv " +
			"that never exercises claudeFiles' generated mounts")
	}
	if _, ok := claudeSettingsMount(p); !ok {
		t.Fatal("control: nothing staged at ~/.claude/settings.json — it is unconditional " +
			"(issue #17); its absence here means stageClaudeSettings silently stopped running " +
			"rather than that this golden has an argv to pin")
	}

	got := goldenFormat(p.BwrapArgs(1000, 1000))

	path := filepath.Join("testdata", "bwrap.claude.txt")
	if *update {
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%v (run: go test ./internal/cli -update)", err)
	}
	if got != string(want) {
		t.Errorf("@claude's bwrap argv changed — this is a change to what the profile with the "+
			"largest credential surface hands the sandbox. Read this diff as a change to the "+
			"security boundary, not as a refactor.\n--- got\n%s\n--- want\n%s", got, want)
	}
}

// TestClaudeArgvIsByteIdenticalAcrossTrustArms is the control for
// TestGoldenClaudeArgv shipping only one golden. It drives the SAME two arms
// claudeblockgolden_test.go's TestGoldenClaudeBlock does — host does not trust
// the target versus host trusts this exact path, via the real claudeStateJSON
// — and asserts the resulting argv is identical, so "one golden is enough" is
// verified by execution rather than assumed by omission.
func TestClaudeArgvIsByteIdenticalAcrossTrustArms(t *testing.T) {
	reg, err := profile.Builtins()
	if err != nil {
		t.Fatal(err)
	}
	sel := append(append([]policy.ProfileName{}, profile.BuiltinDefaults()...), "@claude")
	ctx := envGoldenCtx()

	// Untrusted arm: same shape as TestGoldenClaudeArgv above.
	untrustedPolicy, err := policy.Resolve(map[policy.ProfileName]*policy.Profile(reg), sel, ctx, newEnvFakeEnv())
	if err != nil {
		t.Fatalf("Resolve(%v): %v", sel, err)
	}
	claudeFiles(untrustedPolicy, ctx.Home, false)
	untrusted := untrustedPolicy.BwrapArgs(1000, 1000)

	// Trusted arm: same recipe claudeblockgolden_test.go uses — a real host
	// home in a temp dir whose ~/.claude.json records this exact target as
	// trusted, fed through the real generator.
	trustedPolicy, err := policy.Resolve(map[policy.ProfileName]*policy.Profile(reg), sel, ctx, newEnvFakeEnv())
	if err != nil {
		t.Fatalf("Resolve(%v): %v", sel, err)
	}
	claudeFiles(trustedPolicy, ctx.Home, false)
	hostHome := t.TempDir()
	body := []byte(`{"projects":{"` + ctx.Target + `":{"hasTrustDialogAccepted":true}}}`)
	if err := os.WriteFile(filepath.Join(hostHome, ".claude.json"), body, 0o600); err != nil {
		t.Fatal(err)
	}
	gen := claudeStateJSON(trustedPolicy, hostHome)
	if !strings.Contains(string(gen), "hasTrustDialogAccepted") {
		t.Fatalf("control: the generator produced no trust entry for a host that trusts %q, "+
			"so this test would compare the untrusted arm against itself:\n%s", ctx.Target, gen)
	}
	perm := uint32(0o600)
	trustedPolicy.Replace(policy.Mount{
		Guest: filepath.Join(ctx.Home, ".claude.json"), Kind: policy.KindData,
		Access: policy.AccessRW, Content: policy.Secret(gen),
		Perms: &perm, From: []string{"@claude"},
	})
	trusted := trustedPolicy.BwrapArgs(1000, 1000)

	// CONTROL: the two arms really are in the states they claim, or a
	// byte-for-byte match below proves nothing about trust.
	if claudeTrustCarried(untrustedPolicy, mustMount(t, untrustedPolicy, filepath.Join(ctx.Home, ".claude.json"))) {
		t.Fatal("control: the untrusted arm's ~/.claude.json already carries a trust entry")
	}
	if !claudeTrustCarried(trustedPolicy, mustMount(t, trustedPolicy, filepath.Join(ctx.Home, ".claude.json"))) {
		t.Fatal("control: the trusted arm's ~/.claude.json does not carry the trust entry it was built to carry")
	}

	if strings.Join(untrusted, "\x00") != strings.Join(trusted, "\x00") {
		t.Errorf("the bwrap argv differs between the untrusted and trusted arms — this test's "+
			"premise (bwrap carries paths and fd numbers, never mount content) no longer holds, "+
			"and TestGoldenClaudeArgv needs a second golden for the trusted arm.\n--- untrusted\n%s"+
			"\n--- trusted\n%s", goldenFormat(untrusted), goldenFormat(trusted))
	}
}

func mustMount(t *testing.T, p *policy.Policy, guest string) policy.Mount {
	t.Helper()
	m, ok := p.Mounts[guest]
	if !ok {
		t.Fatalf("no mount at %s", guest)
	}
	return m
}
