package cli

import (
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/gomoni/snug/internal/policy"
)

// guidanceFor resolves the default @claude selection and renders the injected
// ~/.claude/CLAUDE.md, which is the file these tests grade.
func guidanceFor(t *testing.T) (*policy.Policy, string) {
	t.Helper()
	reg := loadTestRegistry(t)
	home, target := testTree(t)
	ctx := policy.Context{Target: target, Home: home, Shell: "/bin/sh", Command: []string{"/bin/sh"}}
	sel := []policy.ProfileName{"@sys", "@home", "@cwd-rw", "@claude"}
	p, err := policy.Resolve(reg, sel, ctx, policy.OSEnviron{})
	if err != nil {
		t.Fatalf("Resolve(%v): %v", sel, err)
	}
	return p, string(claudeGuidance(p))
}

var backtickedName = regexp.MustCompile("`([A-Za-z][A-Za-z0-9.]*)`")

// span returns the guidance text between two anchors, failing with a control
// message if either anchor is gone — a substring test whose anchor moved
// silently checks the empty string and can no longer fail.
func span(t *testing.T, guidance, from, to string) string {
	t.Helper()
	start := strings.Index(guidance, from)
	if start < 0 {
		t.Fatalf("control: anchor %q is not in the generated guidance, so this test would "+
			"be grading the wrong text:\n%s", from, guidance)
	}
	rest := guidance[start:]
	end := strings.Index(rest, to)
	if end < 0 {
		t.Fatalf("control: anchor %q does not follow %q in the generated guidance:\n%s",
			to, from, guidance)
	}
	return rest[:end]
}

// TestClaudeGuidanceNamesTheStateKeysItWrites fails if the ~/.claude.json
// sentence and claudeState disagree about which keys snug writes.
//
// What it would have caught: the sentence hand-counted the table ("holds at
// most three keys"), so a fourth key would have left it silently wrong — the
// defect claudeAllowlistNames was introduced to end for the settings.json
// sentence, in the same paragraph, one release earlier.
func TestClaudeGuidanceNamesTheStateKeysItWrites(t *testing.T) {
	pol, guidance := guidanceFor(t)

	sentence := span(t, guidance, "`~/.claude.json` here is GENERATED by snug", "The\n")
	var named []string
	for _, m := range backtickedName.FindAllStringSubmatch(sentence, -1) {
		named = append(named, m[1])
	}
	sort.Strings(named)

	want := make([]string, 0, len(claudeState(pol)))
	for k := range claudeState(pol) {
		want = append(want, k)
	}
	sort.Strings(want)

	if strings.Join(named, ",") != strings.Join(want, ",") {
		t.Errorf("the guidance's ~/.claude.json sentence names %v but claudeState writes %v — "+
			"the two must be the same set, and claudeStateNames is what keeps them so:\n%s",
			named, want, sentence)
	}
}

// TestClaudeGuidanceNamesOnlyRefusedKeys fails if a key the guidance offers as
// an EXAMPLE of what is dropped from ~/.claude/settings.json is not actually
// refused — either because it reached policy.ClaudeSettingAllowlist, or because
// it was never in policy.ClaudeExecutingKeys to begin with.
//
// What it would have caught: nothing, at the time it was written — `env` really
// is refused. The falsehood was the SHAPE of the old sentence, which presented
// five names under "NOT carried:" as if they were the whole refused set, so an
// agent finding `env` in the live file (Claude Code writes one there, disabling
// its own auto-updater) read it as evidence snug had carried the host's. The
// sentence now states the drop as the invariant and these names as examples;
// this test is what stops an example from going stale into a false one.
//
// It does NOT check that the refused set is complete — policy.ClaudeExecutingKeys
// is 91 names and the guidance names five on purpose. Completeness is the
// allowlist's property, and FilterClaudeSettings' own tests are where it lives.
func TestClaudeGuidanceNamesOnlyRefusedKeys(t *testing.T) {
	_, guidance := guidanceFor(t)

	examples := span(t, guidance, "every other key in the host's file is dropped", "because each names a")
	var named []string
	for _, m := range backtickedName.FindAllStringSubmatch(examples, -1) {
		named = append(named, m[1])
	}
	if len(named) == 0 {
		t.Fatalf("control: no backticked key names in the dropped-keys sentence, so this "+
			"test asserts nothing:\n%s", examples)
	}

	carried := make(map[string]bool, len(policy.ClaudeSettingAllowlist))
	for _, k := range policy.ClaudeSettingAllowlist {
		carried[k.Name] = true
	}
	for _, name := range named {
		if carried[name] {
			t.Errorf("the guidance offers %q as an example of a key that is DROPPED, but it is "+
				"in policy.ClaudeSettingAllowlist and is therefore carried", name)
		}
		if _, refused := policy.ClaudeExecutingKeys[name]; !refused {
			t.Errorf("the guidance offers %q as an example of a dropped key, but it is not in "+
				"policy.ClaudeExecutingKeys — either the catalogue lost it or the example is "+
				"invented, and an agent reading this screen cannot tell which", name)
		}
	}
}

// TestClaudeGuidanceSaysBothGeneratedFilesAreRewritten fails if the guidance
// stops warning that Claude Code rewrites ~/.claude.json and
// ~/.claude/settings.json after snug hands off.
//
// What it would have caught, measured in a real snug run (claude 2.1.263, from
// /proc/2/stat field 22 against stat(1) mtimes): this guidance file is written
// 25 ms BEFORE claude starts, settings.json 247 ms after and ~/.claude.json 51 s
// after — both on the writable $HOME tmpfs the sandboxed process owns. On that
// run `autoUpdates` was gone from ~/.claude.json and an `env` key had appeared
// in settings.json. Without this paragraph an agent cats either file, finds it
// contradicting the two sentences above, and reports a hole that is not one.
//
// The assertion is deliberately about the CLAIM and not about either instance:
// both are one claude version's behaviour, and the screen names neither.
func TestClaudeGuidanceSaysBothGeneratedFilesAreRewritten(t *testing.T) {
	_, guidance := guidanceFor(t)

	// Newlines collapsed: the guidance is hand-wrapped prose, so a phrase this
	// test names can sit across a line break — as all three below did when
	// first written.
	para := span(t, guidance, "REWRITTEN BY CLAUDE CODE", "snug also SETS these keys")
	flat := strings.Join(strings.Fields(para), " ")
	for _, want := range []string{
		"a key snug wrote may be gone",
		"a key snug never carried may be present",
		"not a hole to report",
	} {
		if !strings.Contains(flat, want) {
			t.Errorf("the rewrite paragraph no longer says %q, so an agent reading a rewritten "+
				"generated file has nothing telling it the file is not snug's state:\n%s",
				want, para)
		}
	}
}
