package cli

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/gomoni/snug/internal/hostread"
	"github.com/gomoni/snug/internal/policy"
	"github.com/gomoni/snug/internal/profile"
	"github.com/gomoni/snug/internal/sshproxy"
)

// maxKnownHostsBytes bounds the read of the host's ~/.ssh/known_hosts. A
// busy user can accumulate thousands of hosts, each roughly a few hundred
// bytes (hostname patterns, key type, base64 key blob, optional comment); 8
// MiB covers tens of thousands of such entries with room to spare while
// still bounding the host-side allocation a planted symlink or oversized
// file would otherwise demand (issue #337).
const maxKnownHostsBytes = 8 << 20

// knownHostsFor extracts the entries for one host from the host's known_hosts.
//
// Binding the whole file would tell the sandbox every machine you have ever
// connected to — an inventory of your infrastructure, for no benefit. Hashed
// entries (HashKnownHosts) cannot be matched by name and are skipped; the
// generated ssh config uses accept-new so a first connection still works.
func knownHostsFor(host string) []byte {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil
	}
	// hostread.Optional, not os.ReadFile: the same FIFO/symlink primitive
	// issue #337 measured against identity.ssh.key applies here too — this
	// one is the host user's own file rather than payload-reachable, but a
	// FIFO at ~/.ssh/known_hosts would still hang every run before the
	// sandbox exists. "Optional" because an absent or unreadable
	// known_hosts already meant "no entries" here, silently, before this fix.
	data, note := hostread.Optional(filepath.Join(home, ".ssh", "known_hosts"), maxKnownHostsBytes)
	if note != "" || data == nil {
		return nil
	}
	var out bytes.Buffer
	out.WriteString("# Generated by snug: only entries for " + host + ".\n")
	for line := range strings.SplitSeq(string(data), "\n") {
		fields := strings.Fields(line)
		if len(fields) < 3 || strings.HasPrefix(line, "#") {
			continue
		}
		for pattern := range strings.SplitSeq(fields[0], ",") {
			if pattern == host || strings.HasSuffix(pattern, "@"+host) {
				out.WriteString(line + "\n")
				break
			}
		}
	}
	return out.Bytes()
}

// tokenMinter is stageGhConfig's one host touch, as a parameter.
//
// It exists because the gh half of #454's host split was assertable by nothing
// that runs without a forge account. identity.ssh.host feeds three GENERATED
// files, which testdata/identity-generated.txt pins byte for byte; identity.gh.host
// feeds `gh auth token --hostname`, the hosts.yml top key and GH_HOST, and all
// three of those sit behind an exec. So the half that MOVES A CREDENTIAL was the
// half with no pure test — the asymmetry is worth a parameter to remove.
//
// A parameter and not a package-level var a test swaps: a mutable global here
// would be reachable from every other test in this package, and the value it
// carries decides which account's token is staged.
type tokenMinter func(host, user string) policy.Secret

// ghToken asks the gh CLI for the token of one account. Shelling out rather
// than parsing ~/.config/gh/hosts.yml: gh owns that format, it changes, and a
// wrong parse here would either break auth or hand over the wrong account's
// token. Absent gh, the sandbox simply has no token.
//
// Returns policy.Secret rather than string: cmd.Output() is the acquisition
// point for the OAuth token, and wrapping it there — rather than at whatever
// later line happens to store it into a Mount — means there is no plain-string
// hop in between for a future line to print by mistake.
func ghToken(host, user string) policy.Secret {
	gh, err := exec.LookPath("gh")
	if err != nil {
		return nil
	}
	cmd := exec.Command(gh, "auth", "token", "--hostname", host)
	if user != "" {
		cmd.Args = append(cmd.Args, "--user", user)
	}
	out, err := cmd.Output()
	if err != nil {
		return nil
	}
	return policy.Secret(bytes.TrimSpace(out))
}

// startIdentity brings up whatever the pinned identity needs, and returns the
// mounts and env the policy could not produce on its own.
//
// On error it returns a nil cleanup, having already run its own.
//
// dryRun starts NOTHING (issue #21): no runtime directory is created, no
// listening socket is bound, no proxy goroutine runs. The socket path is
// NAMED instead — plannedSocket computes the path a real run would use — so
// --dry-run's MOUNTS section is unchanged and still shows where the agent
// socket would appear. plannedRuntimeSocket (runtimedir.go) draws the same
// distinction for the runtime directory: name it, do not create it.
//
// Two host-state checks go with the proxy, and that is the intended
// direction rather than a loss: sshproxy.New refuses when SSH_AUTH_SOCK is
// unset and parses the pinned public key, so before this a dry run on a host
// with no agent running could not inspect an identity profile at all.
// failing on host state would make --dry-run refuse a policy the real run
// might well accept. An UNREADABLE identity.ssh.key is still refused here, by the
// staging read below.
//
// dryRun also still decides what a MISSING gh token means: a refusal for a
// real run, a warning for a dry run, for exactly the same reason.
func startIdentity(pol *policy.Policy, verbose, dryRun bool) (cleanup func(), err error) {
	id := pol.Identity
	if id == nil {
		return func() {}, nil
	}
	cleanup = func() {}

	// THE TWO HALVES ARE INDEPENDENT, AND THIS FUNCTION IS WHERE THAT STOPPED
	// BEING TRUE. The whole of the ssh half sat behind one early return on
	// `id.SSH.Agent == SSHNone`, and stageGhConfig sat at the bottom of it — so a
	// profile whose [identity] names only a gh account got no token, no
	// GH_CONFIG_DIR, no GH_HOST and no line saying so, and exited 0. That is the
	// exact sentence stageGhConfig's own refusal exists to prevent, reached by
	// the gate ABOVE it rather than by the gate it guards, and `snug profile
	// show` meanwhile printed THE SANDBOX HOLDS A FORGE TOKEN FOR THIS ACCOUNT.
	// Found by redteam on #454's branch.
	//
	// #454 is what made the shape easy to write: once [identity] is a container
	// of per-tool blocks, `[identity.gh] user = "you"` alone is the natural
	// spelling for "I want gh in the sandbox, not ssh", and the maintainer
	// decision on this ticket is that a one-tool identity stays legal. Legal has
	// to mean it WORKS, not merely that it resolves.
	if id.SSH.Agent != policy.SSHNone {
		cleanup, err = startSSHIdentity(pol, id, verbose, dryRun)
		if err != nil {
			return nil, err
		}
	}

	if err := stageGhConfig(pol, id, dryRun, ghToken); err != nil {
		cleanup()
		return nil, err
	}
	return cleanup, nil
}

// startSSHIdentity is everything identity.ssh.agent = "proxy" needs: the agent
// proxy itself, the staged public halves of the pinned keys, and SSH_AUTH_SOCK.
//
// Its caller gates it on the agent mode, and every line in here answers to that
// gate rather than to a second check of its own. The staged key exists so the
// generated ~/.ssh/config's IdentityFile resolves, and resolve.go generates that
// file for every mode except none; identity.git.signing_key is refused in Resolve
// without an agent. So there is nothing here a profile with no agent wants.
func startSSHIdentity(pol *policy.Policy, id *policy.Identity, verbose, dryRun bool) (cleanup func(), err error) {
	cleanup = func() {}

	// No os.RemoveAll here: the run directory now has one owner for its
	// whole lifetime — run() in main.go, which creates it on every REAL run
	// and is the sole remover, once, after the sandbox has exited. Two removers racing each
	// other over the same directory is exactly the shape issue #85's sweep
	// already has to defend against from a DIFFERENT process; there is no
	// reason to build a second copy of that race inside one.
	cleanup = func() {}

	// A dry run NAMES the socket; a real run opens the directory that will
	// hold it. openRuntimeDir is what creates that directory, so it is on
	// this side of the branch and not above it.
	var sock string
	if dryRun {
		sock, err = plannedSocket("ssh-agent.sock")
		if err != nil {
			return nil, err
		}
	} else {
		rt, rerr := openRuntimeDir()
		if rerr != nil {
			return nil, rerr
		}
		sock, err = rt.Socket("ssh-agent.sock")
		if err != nil {
			return nil, err
		}
	}
	upstream := os.Getenv("SSH_AUTH_SOCK")

	switch id.SSH.Agent {
	case policy.SSHAgentProxy:
		if id.SSH.Key == "" {
			cleanup()
			return nil, fmt.Errorf("identity.ssh.agent = \"proxy\" needs identity.ssh.key: " +
				"the PUBLIC key file that pins which identity the sandbox may sign with")
		}
		// The identity.ssh.key refusal above is a POLICY error — the profile is
		// incomplete however the host is configured — so it is checked
		// before this branch, not after. Everything below it starts
		// something, which a dry run may not.
		if dryRun {
			pol.BindSocket(sock, policy.AgentSocketGuest, "(identity)")
			break
		}
		audit := func(string) {}
		if verbose {
			audit = func(msg string) { fmt.Fprintln(os.Stderr, "snug: ssh-agent: "+msg) }
		}
		// A SLICE, not one parameter per identity field: #454 turns the field
		// set into an enumeration, and a positional parameter per field would
		// make every new field an edit to this call and to sshproxy.New's
		// signature. sshproxy never learns the field names — it takes labels.
		keys := []sshproxy.PinnedKey{{Field: "identity.ssh.key", Path: id.SSH.Key}}
		if id.Git.SigningKey != "" {
			// MustSign: GitConfigFrom authors `commit.gpgsign = true` for this
			// key, so "the agent lists it" is not enough — see
			// sshproxy.probeSign. The auth key is deliberately NOT MustSign: its
			// failure is `Permission denied (publickey)` against a generated
			// ~/.ssh/config naming exactly one key, which is attributable, and
			// probing it would put a confirmation dialog in front of every snug
			// start including runs that never touch the network.
			keys = append(keys, sshproxy.PinnedKey{
				Field: "identity.git.signing_key", Path: id.Git.SigningKey, MustSign: true})
		}
		// A confirm-constrained key makes sshproxy.New block on a dialog the
		// human may not have noticed, on a desktop they may not be looking at.
		// Nothing is printed on the fast path (measured: 57 ms for a refusal,
		// sub-millisecond for a plain signature); this speaks only once the wait
		// is long enough to look like a hang.
		slow := time.AfterFunc(2*time.Second, func() {
			fmt.Fprintln(os.Stderr, "snug: waiting for the host ssh-agent to sign a startup probe.\n"+
				"      If a pinned key was added with `ssh-add -c`, your agent is asking you to confirm.")
		})
		p, perr := sshproxy.New(keys, upstream, sock, audit)
		slow.Stop()
		if perr != nil {
			cleanup()
			return nil, perr
		}
		go p.Serve()
		inner := cleanup
		cleanup = func() { p.Close(); inner() }
		pol.BindSocket(sock, policy.AgentSocketGuest, "(identity)")
	}

	// The pinned PUBLIC key, so the generated ~/.ssh/config's IdentityFile
	// resolves. Public material only; the private half stays in the host agent.
	//
	// OUTSIDE the switch, and it stays there now that agent-proxy is the only
	// mode left: resolve.go generates ~/.ssh/config for EVERY mode except none,
	// with `IdentitiesOnly yes` and an IdentityFile naming this very file, so
	// the staging answers to the CONFIG's coverage and not to one branch's. A
	// draft that put it inside `case SSHAgentProxy` left the second mode with
	// an IdentityFile pointing at nothing — SSHConfig's own doc comment says
	// that state "would have broken agent auth" — and a mode added here later
	// would inherit that bug from the same placement.
	//
	// Read HERE rather than before Resolve, which is the other half of the fix:
	// the pre-resolve version read the profile's raw text and understood `~/`
	// alone, so `key = "{home}/.ssh/id.pub"` — the spelling base.toml's own
	// example uses, and the one every grant in every profile uses — read a file
	// literally called `{home}/...`, failed, and staged nothing. Silently.
	// pol.Identity.SSH.Key has been through the same expansion and the same
	// under-target symlink check as a mount path, so there is one spelling with
	// one fate.
	if id.SSH.Key != "" {
		// hostread.Required, not os.ReadFile: the key is a path a payload can
		// plant a FIFO or a symlink to /dev/zero at (issue #337) — it is
		// resolved under the target, which a previous run's own @cwd-rw could
		// have written into. "Required" because an unreadable pinned key must
		// stay a hard error naming the path, exactly as os.ReadFile's did.
		data, rerr := hostread.Required(id.SSH.Key, hostread.MaxSSHPublicKeyBytes)
		if rerr != nil {
			// Reachable on a DRY RUN, which breaks out of the switch above
			// before sshproxy.New exists to read the same file and fail
			// there first. A real agent-proxy run has already refused.
			cleanup()
			return nil, fmt.Errorf("identity.ssh.key %q: %w\n\n"+
				"      This is the PUBLIC half of the key the sandbox may sign with. snug\n"+
				"      stages it inside so ssh can select that one identity; without it ssh\n"+
				"      offers nothing and every push fails with 'Permission denied'.", id.SSH.Key, rerr)
		}
		pol.Replace(policy.Mount{
			Guest: pol.Home + "/" + policy.PubKeyGuest, Kind: policy.KindData,
			Access: policy.AccessRO, Content: data,
			From: []string{identityProvenance(pol)},
		})
	}

	if id.Git.SigningKey != "" {
		// Same hostread.Required for the same reason (#337): the signing key is a
		// path that may resolve under the target, which a previous run's own
		// @cwd-rw could have replaced with a FIFO.
		data, rerr := hostread.Required(id.Git.SigningKey, hostread.MaxSSHPublicKeyBytes)
		if rerr != nil {
			cleanup()
			return nil, fmt.Errorf("identity.git.signing_key %q: %w\n\n"+
				"      This is the PUBLIC half of the key the sandbox signs commits and tags\n"+
				"      with. snug stages it inside and points user.signingkey at it; the\n"+
				"      private half stays in your agent.", id.Git.SigningKey, rerr)
		}
		pol.Replace(policy.Mount{
			Guest: pol.Home + "/" + policy.SigningKeyGuest, Kind: policy.KindData,
			Access: policy.AccessRO, Content: data,
			From: []string{identityProvenance(pol)},
		})
	}

	pol.AuthorEnv("SSH_AUTH_SOCK", policy.AgentSocketGuest)

	return cleanup, nil
}

// identityProvenance is the `identity:<profile>` string Resolve stages its own
// identity files with. A mount staged after resolution must carry the same one
// or the --dry-run screen attributes one of four sibling files to nobody.
func identityProvenance(pol *policy.Policy) string {
	if pol.IdentityOwner == "" {
		return "(identity)"
	}
	return "identity:" + string(pol.IdentityOwner)
}

// stageGhConfig gives gh a private config directory instead of a token in the
// environment.
//
// A secret in the environment is passively readable by every process in the
// sandbox through /proc/self/environ, is inherited by every child, and turns up
// in crash dumps. A secret in a file has to be deliberately opened. So snug
// generates a minimal `hosts.yml` holding exactly the pinned account and points
// GH_CONFIG_DIR at it — the env var then carries a PATH, not a credential.
//
// The file is staged WRITABLE, and that is not an oversight. gh migrates a
// file-stored token on first use and rewrites the file; with a read-only copy it
// fails outright with "failed to write config after migration" (verified on gh
// 2.96). It is a private copy on a tmpfs, so the host's real gh config is never
// touched and the rewrite goes nowhere.
//
// BLAST RADIUS, unchanged by any of this: a normal `gh auth login` token
// commonly carries repo, gist, read:org and admin:public_key. With
// admin:public_key a sandbox that reads the file can add an SSH key to the
// account — an effect that OUTLIVES the sandbox. Use a fine-grained token if
// that matters.
// AN IDENTITY WITH NO [identity.gh] BLOCK GETS NO TOKEN AT ALL, which is a
// deliberate narrowing rather than an omission. The previous version called
// `gh auth token` unconditionally, so a profile pinning only an ssh key and a
// git author had the host's ACTIVE gh account staged inside as
// `x-access-token` — a credential nobody named, from an account the profile
// does not mention, and the one the human is most likely to be logged into.
// Pinning is the whole point; an unpinned credential is the thing it exists to
// prevent.
func stageGhConfig(pol *policy.Policy, id *policy.Identity, dryRun bool, mint tokenMinter) error {
	// THE GATE IS THE USER, AND IT IS FAIL-CLOSED ON PURPOSE. Resolve refuses
	// gh.host with no gh.user, so this is unreachable for a profile that resolved;
	// written this way round, deleting that refusal later reverts to "no token"
	// rather than to "stage whatever account the host happens to be logged in to".
	if id.Gh.User == "" {
		return nil
	}
	host := id.GhHost()
	tok := mint(host, id.Gh.User)
	if len(tok) == 0 {
		// Invariant 5: no silent downgrade. identity.gh.user is an explicit request for
		// a capability, and the previous version of this function returned
		// quietly — you got a sandbox with no gh credential, no GH_CONFIG_DIR
		// and no line anywhere saying so, which is indistinguishable from a
		// working one until `gh` asks you to log in.
		//
		// %q, not %s, on every profile-supplied value below. These strings are
		// profile-authored text reaching a terminal, and a gh.user containing
		// ESC[1A CR overwrites the `snug:` line above it with a forged one —
		// CLAUDE.md's control-character rule, arriving at a sink that did not
		// exist when the rule was written.
		// gh.user is non-empty by the gate at the top of this function, so there is
		// no "the active account on HOST" arm any more: that wording existed for the
		// gh.host-alone shape, which Resolve refuses outright.
		who := strconv.Quote(id.Gh.User) + " on " + strconv.Quote(host)
		msg := fmt.Sprintf("no gh token for %s.\n\n"+
			"      The profile pins a GitHub account, so snug will not start a sandbox\n"+
			"      that silently has no credential for it. Either:\n"+
			"        - log in on the host:  gh auth login --hostname %s\n"+
			"        - check the spelling:  gh auth status\n"+
			"        - or drop the [identity.gh] block if the sandbox does not need gh\n"+
			"          (identity.ssh.* alone still pins git-over-ssh).\n"+
			"      If gh is not installed on the host there is nothing to mint, and the\n"+
			"      same applies.", who, strconv.Quote(host))
		if dryRun {
			// A dry run inspects a policy; it does not need the credential to
			// exist, and refusing here would make the policy unreadable on
			// exactly the hosts where reading it matters most — a CI box, a
			// machine without gh, someone reviewing a colleague's profile.
			// plannedSocket above makes the same call for the agent socket.
			fmt.Fprintln(os.Stderr, "snug: "+msg)
			fmt.Fprintln(os.Stderr, "      (dry run: continuing, and the FILESYSTEM block below "+
				"therefore has no hosts.yml row)")
			return nil
		}
		return errors.New(msg)
	}
	// No x-access-token fallback: gh.user is non-empty by the gate above, and a
	// fallback here is what staged an account the profile never named.
	user := id.Gh.User

	dir := pol.Home + "/.config/gh"
	// string(tok) is the one explicit escape this document needs: fmt.Sprintf's
	// %s on a policy.Secret would render "<redacted N bytes>" into the file
	// instead of the token, so the interpolation itself must convert — visibly,
	// at this one point — rather than the whole document staying a plain
	// string until it is stored.
	hosts := policy.Secret(fmt.Sprintf("%s:\n    oauth_token: %s\n    user: %s\n    git_protocol: ssh\n",
		host, string(tok), user))

	perm := uint32(0o600)
	pol.Replace(policy.Mount{
		Guest: dir + "/hosts.yml", Kind: policy.KindData, Access: policy.AccessRW,
		Content: hosts, Perms: &perm, From: []string{"(identity)"},
	})
	pol.AuthorEnv("GH_CONFIG_DIR", dir)
	pol.AuthorEnv("GH_HOST", host)
	return nil
}

// identitySSHHost peeks at the selected profiles for a pinned identity.ssh.host,
// so the caller can filter known_hosts before resolution needs it.
//
// SSH AND NOT GH, because known_hosts is read by the ssh client connecting to the
// host you push to — not by gh, which speaks HTTPS to an API. Before #454 one
// field answered both questions; splitting it made this the ssh one.
//
// It runs BEFORE Resolve, so on a selection whose identities conflict it may pick
// either. Resolve then refuses the whole run, so nothing downstream can act on the
// wrong answer.
type profileRegistry = profile.Registry

func identitySSHHost(reg profileRegistry, selected []policy.ProfileName) string {
	set, err := policy.Expand(map[policy.ProfileName]*policy.Profile(reg), selected)
	if err != nil {
		return policy.DefaultIdentityHost
	}
	for _, p := range set {
		if p.Identity != nil && p.Identity.SSH.Host != "" {
			return p.Identity.SSH.Host
		}
	}
	return policy.DefaultIdentityHost
}

// pinnedPubKey is gone deliberately. It read the profile's RAW key text
// before Resolve ran, so it understood `~/` and nothing else — `{home}/…`, the
// spelling base.toml's own example uses, silently staged no key at all. The
// read now happens in startIdentity against pol.Identity.SSH.Key, which has been
// expanded and symlink-checked exactly like a mount path. One spelling, one
// fate, and a missing file is an error instead of an absence.
