package cli

import (
	"io"
	"strings"
	"testing"

	"github.com/gomoni/snug/internal/policy"
)

// TestClaudeGuidanceDoesNotClaimTheSessionMeshIsClosed is NEGATIVE, for issue
// #87. isolatePeerMachines' HEADLESS arm is NOT MEASURED (see
// ClaudeAuthoredSettings' own doc comment: it is an ASK, interactive, and
// nothing here has established what an unanswerable ask resolves to) — so
// neither the file an AGENT reads (~/.claude/CLAUDE.md, generated by
// claudeGuidance) nor the file a HUMAN reads (--dry-run's CLAUDE block, from
// describeClaude) may say the session mesh is unreachable or closed. The
// human-facing screen is allowed the weaker, measured qualifier
// ("CLIENT-SIDE... not a boundary"); the agent-facing file is not, by
// claudeGuidance's own doc comment ("the client-side, not a boundary half
// deliberately stays off this screen").
func TestClaudeGuidanceDoesNotClaimTheSessionMeshIsClosed(t *testing.T) {
	reg := loadTestRegistry(t)
	home, target := testTree(t)
	ctx := policy.Context{Target: target, Home: home, Shell: "/bin/sh", Command: []string{"/bin/sh"}}
	sel := []policy.ProfileName{"@sys", "@home", "@cwd-rw", "@claude"}
	p, err := policy.Resolve(reg, sel, ctx, policy.OSEnviron{})
	if err != nil {
		t.Fatalf("Resolve(%v): %v", sel, err)
	}
	if err := claudeFiles(p, home, false); err != nil {
		t.Fatalf("claudeFiles: %v", err)
	}

	closureWords := []string{"unreachable", "cannot reach a session", "blocked", "is closed"}

	// The agent-facing file. Scoped to the authored-key paragraph rather than
	// the whole document: claudeGuidance's filesystem paragraph legitimately
	// says a DIFFERENT hole ("It is not fully closed OUTBOUND") is not fully
	// closed, about renaming out of ~/.claude — a whole-document substring
	// check on "closed" would fail on that unrelated sentence.
	guidance := string(claudeGuidance(p))
	start := strings.Index(guidance, "snug also SETS these keys")
	end := strings.Index(guidance, "One exception, narrowed.")
	if start < 0 || end < 0 || end <= start {
		t.Fatalf("control: could not locate the authored-key paragraph in claudeGuidance's "+
			"output — this test would be checking the wrong text:\n%s", guidance)
	}
	block := guidance[start:end]
	for _, name := range policy.ClaudeAuthoredNames() {
		if !strings.Contains(block, name) {
			t.Errorf("claudeGuidance's authored-key paragraph does not name %q:\n%s", name, block)
		}
	}
	for _, w := range closureWords {
		if strings.Contains(strings.ToLower(block), w) {
			t.Errorf("claudeGuidance's authored-key paragraph claims the session mesh is "+
				"closed/unreachable (%q), which isolatePeerMachines' headless arm was never "+
				"measured to guarantee:\n%s", w, block)
		}
	}

	// The human-facing screen. Scoped to the `snug set` block the same way,
	// bounded by its own fixed closing line.
	dry := captureFile(t, func(f io.Writer) { describeClaude(f, p) })
	dstart := strings.Index(dry, "snug set")
	dend := strings.Index(dry, "THREAT-MODEL.md 3.1")
	if dstart < 0 || dend < 0 || dend <= dstart {
		t.Fatalf("control: could not locate the `snug set` block in describeClaude's output — "+
			"this test would be checking the wrong text:\n%s", dry)
	}
	dblock := dry[dstart : dend+len("THREAT-MODEL.md 3.1")]
	if !strings.Contains(dblock, "not a boundary") {
		t.Errorf("describeClaude's `snug set` block does not say \"not a boundary\" — the "+
			"human-facing qualifier this test requires:\n%s", dblock)
	}
	for _, w := range closureWords {
		if strings.Contains(strings.ToLower(dblock), w) {
			t.Errorf("describeClaude's `snug set` block claims the session mesh is "+
				"closed/unreachable (%q), which isolatePeerMachines' headless arm was never "+
				"measured to guarantee:\n%s", w, dblock)
		}
	}
}
