[book]
title = "snug"
description = "An unprivileged sandbox for running untrusted code"
authors = ["Michal Vyskocil"]
language = "en"
src = "src"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/gomoni/snug"
edit-url-template = "https://github.com/gomoni/snug/edit/main/docs/{path}"

[output.html.fold]
enable = true
level = 1
