package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/gomoni/snug/internal/policy"
	"github.com/gomoni/snug/internal/profile"
	"github.com/gomoni/snug/internal/sshproxy"
)

// runtimeDir is a private per-run directory for sockets. Under
// $XDG_RUNTIME_DIR, which is a tmpfs owned by us with mode 0700, so a stale
// socket cannot survive a reboot and nobody else can connect to one.
func runtimeDir() (string, error) {
	base := os.Getenv("XDG_RUNTIME_DIR")
	if base == "" {
		base = os.TempDir()
	}
	dir := filepath.Join(base, "snug", fmt.Sprintf("run-%d", os.Getpid()))
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	return dir, nil
}

// knownHostsFor extracts the entries for one host from the host's known_hosts.
//
// Binding the whole file would tell the sandbox every machine you have ever
// connected to — an inventory of your infrastructure, for no benefit. Hashed
// entries (HashKnownHosts) cannot be matched by name and are skipped; the
// generated ssh config uses accept-new so a first connection still works.
func knownHostsFor(host string) []byte {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil
	}
	data, err := os.ReadFile(filepath.Join(home, ".ssh", "known_hosts"))
	if err != nil {
		return nil
	}
	var out bytes.Buffer
	out.WriteString("# Generated by snug: only entries for " + host + ".\n")
	for line := range strings.SplitSeq(string(data), "\n") {
		fields := strings.Fields(line)
		if len(fields) < 3 || strings.HasPrefix(line, "#") {
			continue
		}
		for pattern := range strings.SplitSeq(fields[0], ",") {
			if pattern == host || strings.HasSuffix(pattern, "@"+host) {
				out.WriteString(line + "\n")
				break
			}
		}
	}
	return out.Bytes()
}

// ghToken asks the gh CLI for the token of one account. Shelling out rather
// than parsing ~/.config/gh/hosts.yml: gh owns that format, it changes, and a
// wrong parse here would either break auth or hand over the wrong account's
// token. Absent gh, the sandbox simply has no token.
//
// Returns policy.Secret rather than string: cmd.Output() is the acquisition
// point for the OAuth token, and wrapping it there — rather than at whatever
// later line happens to store it into a Mount — means there is no plain-string
// hop in between for a future line to print by mistake.
func ghToken(host, user string) policy.Secret {
	gh, err := exec.LookPath("gh")
	if err != nil {
		return nil
	}
	if host == "" {
		host = "github.com"
	}
	cmd := exec.Command(gh, "auth", "token", "--hostname", host)
	if user != "" {
		cmd.Args = append(cmd.Args, "--user", user)
	}
	out, err := cmd.Output()
	if err != nil {
		return nil
	}
	return policy.Secret(bytes.TrimSpace(out))
}

// startIdentity brings up whatever the pinned identity needs, and returns the
// mounts and env the policy could not produce on its own.
//
// On error it returns a nil cleanup, having already run its own.
//
// dryRun does not stop the proxy or the runtime directory — those are still
// started, and https://github.com/gomoni/snug/issues/21 records that with its
// reproduction — but it
// does decide what a MISSING gh token means: a refusal for a real run, a warning
// for a dry run. main.go makes the same distinction for the @tmp-shared host
// directory, and for the same stated reason: failing on host state would make
// --dry-run refuse a policy the real run might well accept, and --dry-run is the
// only way to inspect a profile on a host that cannot mint the token at all.
func startIdentity(pol *policy.Policy, verbose, iKnow, dryRun bool) (cleanup func(), err error) {
	id := pol.Identity
	if id == nil || id.SSHMode == policy.SSHNone {
		return func() {}, nil
	}

	dir, err := runtimeDir()
	if err != nil {
		return nil, err
	}
	cleanup = func() { os.RemoveAll(dir) }

	sock := filepath.Join(dir, "ssh-agent.sock")
	upstream := os.Getenv("SSH_AUTH_SOCK")

	switch id.SSHMode {
	case policy.SSHHostAgent:
		// No filtering at all: every key in your agent, usable by the sandbox.
		//
		// This gate was documented in three places and implemented in none —
		// the redteam agent walked in and signed with a key the profile had not
		// pinned. A weakening this large must be a human act at the CLI, never
		// something a profile can assert on its own (INDEX §2.3).
		if !iKnow {
			cleanup()
			return nil, fmt.Errorf(`refusing ssh_mode = "host-agent" without --i-know.

      This forwards your ENTIRE ssh-agent into the sandbox: every key you have
      loaded becomes enumerable AND usable as a signing oracle, not just the
      pinned one. Anything the sandbox signs is indistinguishable from you.

      If you meant "the sandbox needs one key", use ssh_mode = "agent-proxy"
      with ssh_key set. To proceed anyway, add --i-know.`)
		}
		if upstream == "" {
			cleanup()
			return nil, fmt.Errorf("ssh_mode = \"host-agent\" but no agent is running on the host")
		}
		pol.BindSocket(upstream, "/run/snug/ssh-agent.sock", "(identity)")

	case policy.SSHAgentProxy:
		if id.SSHKey == "" {
			cleanup()
			return nil, fmt.Errorf("ssh_mode = \"agent-proxy\" needs ssh_key: the PUBLIC key " +
				"file that pins which identity the sandbox may sign with")
		}
		audit := func(string) {}
		if verbose {
			audit = func(msg string) { fmt.Fprintln(os.Stderr, "snug: ssh-agent: "+msg) }
		}
		p, perr := sshproxy.New(id.SSHKey, upstream, sock, audit)
		if perr != nil {
			cleanup()
			return nil, perr
		}
		go p.Serve()
		inner := cleanup
		cleanup = func() { p.Close(); inner() }
		pol.BindSocket(sock, "/run/snug/ssh-agent.sock", "(identity)")
	}

	// The pinned PUBLIC key, so the generated ~/.ssh/config's IdentityFile
	// resolves. Public material only; the private half stays in the host agent.
	//
	// OUTSIDE the switch, and that placement is a bug fix of its own: an earlier
	// draft put it inside `case SSHAgentProxy`, which quietly dropped it for
	// `host-agent` — while resolve.go generates ~/.ssh/config for EVERY mode
	// except none, with `IdentitiesOnly yes` and an IdentityFile naming the very
	// file that was no longer staged. SSHConfig's own doc comment says that
	// state "would have broken agent auth". Found by review, not by a test.
	//
	// Read HERE rather than before Resolve, which is the other half of the fix:
	// the pre-resolve version read the profile's raw text and understood `~/`
	// alone, so `ssh_key = "{home}/.ssh/id.pub"` — the spelling base.toml's own
	// example uses, and the one every grant in every profile uses — read a file
	// literally called `{home}/...`, failed, and staged nothing. Silently.
	// pol.Identity.SSHKey has been through the same expansion and the same
	// under-target symlink check as a mount path, so there is one spelling with
	// one fate.
	if id.SSHKey != "" {
		data, rerr := os.ReadFile(id.SSHKey)
		if rerr != nil {
			// Reachable in practice only for host-agent mode: agent-proxy has
			// already read the same file through sshproxy.New and failed there.
			cleanup()
			return nil, fmt.Errorf("ssh_key %q: %w\n\n"+
				"      This is the PUBLIC half of the key the sandbox may sign with. snug\n"+
				"      stages it inside so ssh can select that one identity; without it ssh\n"+
				"      offers nothing and every push fails with 'Permission denied'.", id.SSHKey, rerr)
		}
		pol.Replace(policy.Mount{
			Guest: pol.Home + "/" + policy.PubKeyGuest, Kind: policy.KindData,
			Access: policy.AccessRO, Content: data,
			From: []string{identityProvenance(pol)},
		})
	}

	pol.AuthorEnv("SSH_AUTH_SOCK", "/run/snug/ssh-agent.sock")

	if err := stageGhConfig(pol, id, dryRun); err != nil {
		cleanup()
		return nil, err
	}
	return cleanup, nil
}

// identityProvenance is the `identity:<profile>` string Resolve stages its own
// identity files with. A mount staged after resolution must carry the same one
// or the --dry-run screen attributes one of four sibling files to nobody.
func identityProvenance(pol *policy.Policy) string {
	if pol.IdentityOwner == "" {
		return "(identity)"
	}
	return "identity:" + pol.IdentityOwner
}

// stageGhConfig gives gh a private config directory instead of a token in the
// environment.
//
// A secret in the environment is passively readable by every process in the
// sandbox through /proc/self/environ, is inherited by every child, and turns up
// in crash dumps. A secret in a file has to be deliberately opened. So snug
// generates a minimal `hosts.yml` holding exactly the pinned account and points
// GH_CONFIG_DIR at it — the env var then carries a PATH, not a credential.
//
// The file is staged WRITABLE, and that is not an oversight. gh migrates a
// file-stored token on first use and rewrites the file; with a read-only copy it
// fails outright with "failed to write config after migration" (verified on gh
// 2.96). It is a private copy on a tmpfs, so the host's real gh config is never
// touched and the rewrite goes nowhere.
//
// BLAST RADIUS, unchanged by any of this: a normal `gh auth login` token
// commonly carries repo, gist, read:org and admin:public_key. With
// admin:public_key a sandbox that reads the file can add an SSH key to the
// account — an effect that OUTLIVES the sandbox. Use a fine-grained token if
// that matters.
// AN IDENTITY WITH NO gh_user AND NO gh_host GETS NO TOKEN AT ALL, which is a
// deliberate narrowing rather than an omission. The previous version called
// `gh auth token` unconditionally, so a profile pinning only an ssh key and a
// git author had the host's ACTIVE gh account staged inside as
// `x-access-token` — a credential nobody named, from an account the profile
// does not mention, and the one the human is most likely to be logged into.
// Pinning is the whole point; an unpinned credential is the thing it exists to
// prevent.
func stageGhConfig(pol *policy.Policy, id *policy.Identity, dryRun bool) error {
	host := id.GhHost
	if host == "" {
		host = "github.com"
	}
	if id.GhUser == "" && id.GhHost == "" {
		return nil
	}
	tok := ghToken(host, id.GhUser)
	if len(tok) == 0 {
		// Invariant 5: no silent downgrade. gh_user is an explicit request for
		// a capability, and the previous version of this function returned
		// quietly — you got a sandbox with no gh credential, no GH_CONFIG_DIR
		// and no line anywhere saying so, which is indistinguishable from a
		// working one until `gh` asks you to log in.
		//
		// %q, not %s, on every profile-supplied value below. These strings are
		// profile-authored text reaching a terminal, and a gh_user containing
		// ESC[1A CR overwrites the `snug:` line above it with a forged one —
		// CLAUDE.md's control-character rule, arriving at a sink that did not
		// exist when the rule was written.
		who := "the active account on " + strconv.Quote(host)
		if id.GhUser != "" {
			who = strconv.Quote(id.GhUser) + " on " + strconv.Quote(host)
		}
		msg := fmt.Sprintf("no gh token for %s.\n\n"+
			"      The profile pins a GitHub account, so snug will not start a sandbox\n"+
			"      that silently has no credential for it. Either:\n"+
			"        - log in on the host:  gh auth login --hostname %s\n"+
			"        - check the spelling:  gh auth status\n"+
			"        - or drop gh_user/gh_host from the profile if the sandbox does not\n"+
			"          need gh (ssh_key alone still pins git-over-ssh).\n"+
			"      If gh is not installed on the host there is nothing to mint, and the\n"+
			"      same applies.", who, strconv.Quote(host))
		if dryRun {
			// A dry run inspects a policy; it does not need the credential to
			// exist, and refusing here would make the policy unreadable on
			// exactly the hosts where reading it matters most — a CI box, a
			// machine without gh, someone reviewing a colleague's profile.
			// main.go:230 makes the same call for the @tmp-shared host dir.
			fmt.Fprintln(os.Stderr, "snug: "+msg)
			fmt.Fprintln(os.Stderr, "      (dry run: continuing, and the FILESYSTEM block below "+
				"therefore has no hosts.yml row)")
			return nil
		}
		return errors.New(msg)
	}
	user := id.GhUser
	if user == "" {
		user = "x-access-token"
	}

	dir := pol.Home + "/.config/gh"
	// string(tok) is the one explicit escape this document needs: fmt.Sprintf's
	// %s on a policy.Secret would render "<redacted N bytes>" into the file
	// instead of the token, so the interpolation itself must convert — visibly,
	// at this one point — rather than the whole document staying a plain
	// string until it is stored.
	hosts := policy.Secret(fmt.Sprintf("%s:\n    oauth_token: %s\n    user: %s\n    git_protocol: ssh\n",
		host, string(tok), user))

	perm := uint32(0o600)
	pol.Replace(policy.Mount{
		Guest: dir + "/hosts.yml", Kind: policy.KindData, Access: policy.AccessRW,
		Content: hosts, Perms: &perm, From: []string{"(identity)"},
	})
	pol.AuthorEnv("GH_CONFIG_DIR", dir)
	pol.AuthorEnv("GH_HOST", host)
	return nil
}

// identityHost peeks at the selected profiles for a pinned gh_host, so the
// caller can filter known_hosts before resolution needs it.
type profileRegistry = profile.Registry

func identityHost(reg profileRegistry, selected []string) string {
	set, err := policy.Expand(map[string]*policy.Profile(reg), selected)
	if err != nil {
		return "github.com"
	}
	for _, p := range set {
		if p.Identity != nil && p.Identity.GhHost != "" {
			return p.Identity.GhHost
		}
	}
	return "github.com"
}

// pinnedPubKey is gone deliberately. It read the profile's RAW ssh_key text
// before Resolve ran, so it understood `~/` and nothing else — `{home}/…`, the
// spelling base.toml's own example uses, silently staged no key at all. The
// read now happens in startIdentity against pol.Identity.SSHKey, which has been
// expanded and symlink-checked exactly like a mount path. One spelling, one
// fate, and a missing file is an error instead of an absence.
