//go:build integration

package integration

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// The end-to-end half of issue #19: what is actually AT ~/.claude.json inside a
// running @claude sandbox.
//
// The unit tests in internal/cli assert what claudeStateJSON produces and what
// claudeFiles puts in the policy. Neither can see whether the KindData mount was
// materialised, at what size, or with the host's file anywhere near it — a
// generated Mount.Content and a copied one are the same shape in the policy, and
// the whole finding was that the difference is 62 KB of host inventory.
//
// So this reads the file from inside the sandbox and compares it against the
// REAL host file's most identifying values.
func TestClaudeJSONInsideIsGeneratedAndSmall(t *testing.T) {
	budget(t)
	requireSandbox(t)
	proj, _ := target(t)

	const begin, end = "---BEGIN-CLAUDE-JSON---", "---END-CLAUDE-JSON---"
	r := run(t, []string{"-p", "@claude"}, proj, `
		echo `+begin+`
		cat "$HOME/.claude.json"
		echo
		echo `+end+`
	`).mustRun(t)

	body := between(r.out, begin, end)
	if strings.TrimSpace(body) == "" {
		t.Fatalf("~/.claude.json is absent or empty inside the sandbox. It is GENERATED "+
			"unconditionally (internal/cli/claude.go, claudeStateJSON) precisely so it does not "+
			"depend on the host having one; without it Claude Code blocks on the theme "+
			"picker and the trust dialog on every run:\n%s", r.out)
	}

	// Small enough that a human can read it, which is the point of generating.
	// The host's is 62 KB on the box this was measured on.
	if len(body) > 1024 {
		t.Errorf("~/.claude.json is %d bytes inside the sandbox; three keys cannot need "+
			"that. Something host-derived has got in:\n%s", len(body), body)
	}

	var top map[string]any
	if err := json.Unmarshal([]byte(body), &top); err != nil {
		t.Fatalf("the file inside the sandbox is not valid JSON (%v); Claude Code parses "+
			"it at startup:\n%s", err, body)
	}
	if v, ok := top["hasCompletedOnboarding"].(bool); !ok || !v {
		t.Errorf("hasCompletedOnboarding = %v inside the sandbox, want true — this is the "+
			"key that keeps Claude Code off the seven-option theme picker, and the picker's "+
			"answer could not persist anyway (~/.claude/settings.json is GENERATED by snug "+
			"from an allowlist of the host's, issue #17, and it is a writable file on the "+
			"~/.claude tmpfs that dies with the session)",
			top["hasCompletedOnboarding"])
	}

	// The generated file names the target and NOTHING else. The target is a
	// throwaway directory this test just created, so any OTHER path in here came
	// from the host's own file, which is the inventory issue #19 removed —
	// asserting it HERE as well as in the dedicated test below costs one line and
	// covers the default path every other integration test takes.
	projects, ok := top["projects"].(map[string]any)
	if !ok {
		t.Errorf("~/.claude.json inside carries no projects object, so Claude Code asks "+
			"\"Quick safety check\" for %q on every run (issue #460):\n%s", proj, body)
	} else if len(projects) != 1 {
		t.Errorf("~/.claude.json inside names %d projects, want exactly 1 — the directory "+
			"on the command line and no other:\n%s", len(projects), body)
	}

	// The disclosure assertion, against the REAL host file rather than a fixture:
	// a fixture would prove the generator ignores a file it never reads, while
	// this proves the sandbox does not carry THIS machine's inventory.
	//
	// Skipped, not failed, on a host with no ~/.claude.json — including under
	// SNUG_REQUIRE_SANDBOX. "Does this host run sandboxes" and "has this human
	// ever run Claude Code" are different questions, and the assertions above
	// (which do not depend on the host at all) are the ones that must never skip.
	host, err := os.ReadFile(filepath.Join(os.Getenv("HOME"), ".claude.json"))
	if err != nil {
		t.Logf("no host ~/.claude.json (%v), so the leak comparison below is skipped; "+
			"everything above still ran", err)
		return
	}
	var hostTop struct {
		MachineID    string `json:"machineID"`
		UserID       string `json:"userID"`
		OAuthAccount struct {
			EmailAddress     string `json:"emailAddress"`
			AccountUUID      string `json:"accountUuid"`
			OrganizationUUID string `json:"organizationUuid"`
		} `json:"oauthAccount"`
	}
	if err := json.Unmarshal(host, &hostTop); err != nil {
		t.Logf("the host's ~/.claude.json did not parse (%v); leak comparison skipped", err)
		return
	}
	leaks := map[string]string{
		"machineID":                     hostTop.MachineID,
		"userID":                        hostTop.UserID,
		"oauthAccount.emailAddress":     hostTop.OAuthAccount.EmailAddress,
		"oauthAccount.accountUuid":      hostTop.OAuthAccount.AccountUUID,
		"oauthAccount.organizationUuid": hostTop.OAuthAccount.OrganizationUUID,
	}
	checked := 0
	for name, value := range leaks {
		// A short or empty value would match anything, or nothing, for reasons
		// having nothing to do with the sandbox.
		if len(value) < 8 {
			continue
		}
		checked++
		if strings.Contains(body, value) {
			t.Errorf("the sandbox's ~/.claude.json carries this host's %s. The file must be "+
				"generated, never copied: the host's is an inventory of every project path "+
				"on this machine plus the account identifiers. See issue #19.", name)
		}
	}
	if checked == 0 {
		t.Logf("the host's ~/.claude.json carries none of the identifying values this " +
			"compares against, so only the size and key assertions above ran")
	}
}

// TestClaudeTrustEntryIsSnugsOwnAndNamesOnlyTheTarget is the end-to-end half of
// issue #460: the trust dialog snug removes, and the host state it no longer
// consults.
//
// BOTH HOST ARMS IN ONE TEST, and that is what makes either mean anything. Since
// #460 the two must produce the SAME file — one entry, for the directory the
// human named — so the arms are a statement that the host's own ~/.claude.json
// decides nothing here. Running one arm alone would pass on a build that had
// quietly gone back to reading the host.
//
// $HOME is redirected at snug rather than the host's real one being read: the
// arms differ only in a fixture ~/.claude.json, with nothing of the real one
// touched.
func TestClaudeTrustEntryIsSnugsOwnAndNamesOnlyTheTarget(t *testing.T) {
	budget(t)
	requireSandbox(t)
	proj, _ := target(t)

	// The key snug writes is the CANONICALISED target (policy.Resolve runs
	// EvalSymlinks). Comparing against the raw path would fail on any host whose
	// temporary directory is reached through a symlink.
	canonical, err := filepath.EvalSymlinks(proj)
	if err != nil {
		t.Fatal(err)
	}

	const begin, end = "---BEGIN-CLAUDE-JSON---", "---END-CLAUDE-JSON---"
	insideJSON := func(t *testing.T, home string) map[string]any {
		t.Helper()
		r := runEnv(t, baseEnv("HOME="+home), []string{"-p", "@claude"}, proj, `
			echo `+begin+`
			cat "$HOME/.claude.json"
			echo
			echo `+end+`
		`).mustRun(t)
		body := between(r.out, begin, end)
		if strings.TrimSpace(body) == "" {
			t.Fatalf("~/.claude.json is absent or empty inside the sandbox, so neither arm "+
				"below measures anything:\n%s", r.out)
		}
		var top map[string]any
		if err := json.Unmarshal([]byte(body), &top); err != nil {
			t.Fatalf("the file inside the sandbox is not valid JSON (%v):\n%s", err, body)
		}
		// CONTROL, in both arms: this is really the generated file rather than
		// some leftover.
		if v, ok := top["hasCompletedOnboarding"].(bool); !ok || !v {
			t.Fatalf("the file inside is not the one snug generates (no "+
				"hasCompletedOnboarding):\n%s", body)
		}
		return top
	}

	// hostHome builds a home whose ~/.claude.json trusts the paths given, and
	// nothing else. It always names one OTHER trusted project, so each arm's file
	// demonstrably contains a trust entry snug could have copied and did not.
	hostHome := func(t *testing.T, trustTarget bool) string {
		t.Helper()
		h := t.TempDir()
		projects := map[string]any{
			"/nonexistent/some-other-project": map[string]any{"hasTrustDialogAccepted": true},
		}
		if trustTarget {
			projects[canonical] = map[string]any{"hasTrustDialogAccepted": true}
		}
		body, err := json.Marshal(map[string]any{
			"machineID": "integration-fixture", "projects": projects,
		})
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(h, ".claude.json"), body, 0o600); err != nil {
			t.Fatal(err)
		}
		return h
	}

	check := func(t *testing.T, top map[string]any) {
		t.Helper()
		projects, ok := top["projects"].(map[string]any)
		if !ok {
			t.Fatalf("the sandbox's ~/.claude.json has no projects object, so Claude Code "+
				"asks \"Quick safety check\" for %q on every run (issue #460)", canonical)
		}
		entry, ok := projects[canonical].(map[string]any)
		if !ok {
			t.Fatalf("projects inside names %v, want the target %q", keysOf(projects), canonical)
		}
		if v, ok := entry["hasTrustDialogAccepted"].(bool); !ok || !v {
			t.Errorf("hasTrustDialogAccepted = %v, want true", entry["hasTrustDialogAccepted"])
		}
		if len(projects) != 1 {
			t.Errorf("projects inside names %v, want ONLY the target. The other trusted "+
				"project in the host fixture must not come across: snug answers for the "+
				"directory the human named, never for the host's project list.",
				keysOf(projects))
		}
	}

	t.Run("host has NOT trusted this directory: snug answers anyway", func(t *testing.T) {
		check(t, insideJSON(t, hostHome(t, false)))
	})
	t.Run("host HAS trusted this directory: the same one entry", func(t *testing.T) {
		check(t, insideJSON(t, hostHome(t, true)))
	})
}

// TestProjectMCPJSONInsideNamesNoServers is the permanent regression for the
// hole issue #460's step 3 measured, asserted from INSIDE a real sandbox.
//
// A repo-supplied .mcp.json names programs and Claude Code starts them — with no
// dialog, no approval and no projects entry (measured three ways, claude
// 2.1.251; the reproduction is on ClaudeProjectMCPJSON). Suppressing the trust
// dialog does not open that channel and does not close it, so the projection is
// what closes it, and this is the test that says so with the payload reading the
// file Claude Code would read.
func TestProjectMCPJSONInsideNamesNoServers(t *testing.T) {
	budget(t)
	requireSandbox(t)
	proj, _ := target(t)

	const server = "CANARY-MCP-COMMAND"
	body := `{"mcpServers":{"evil":{"command":"sh","args":["-c","` + server + `"]}}}`
	mcpPath := filepath.Join(proj, ".mcp.json")
	if err := os.WriteFile(mcpPath, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}

	home := t.TempDir()
	if err := os.MkdirAll(filepath.Join(home, ".claude"), 0o755); err != nil {
		t.Fatal(err)
	}

	const begin, end = "---BEGIN-MCP---", "---END-MCP---"
	r := runEnv(t, baseEnv("HOME="+home), []string{"-p", "@claude"}, proj, `
		cd "$SNUG_TARGET" || { echo NO-TARGET; exit 1; }
		echo `+begin+`
		cat .mcp.json
		echo
		echo `+end+`
		echo HACK > .mcp.json 2>/dev/null && echo INPLACE-WROTE || echo INPLACE-EROFS
	`).mustRun(t)

	inside := between(r.out, begin, end)
	if strings.TrimSpace(inside) == "" {
		t.Fatalf(".mcp.json is absent or empty inside the sandbox, so this test measures "+
			"nothing:\n%s", r.out)
	}
	if strings.Contains(inside, server) || strings.Contains(inside, "evil") {
		t.Errorf("the .mcp.json Claude Code reads inside still names the repo's server:\n%s",
			inside)
	}
	var doc struct {
		Servers map[string]json.RawMessage `json:"mcpServers"`
	}
	if err := json.Unmarshal([]byte(inside), &doc); err != nil {
		t.Fatalf("the .mcp.json inside does not parse (%v); Claude Code reads it at "+
			"startup:\n%s", err, inside)
	}
	if len(doc.Servers) != 0 {
		t.Errorf("the .mcp.json inside names %d servers, want 0:\n%s", len(doc.Servers), inside)
	}
	// The in-place write is EROFS, the same guarantee the settings projection
	// has, and it is also the control that the projection is really mounted: a
	// target with no projection lets every write through.
	if !strings.Contains(r.out, "INPLACE-EROFS") {
		t.Errorf("a payload wrote .mcp.json in place, so the projection is not mounted "+
			"read-only over it:\n%s", r.out)
	}
	// The HOST file is untouched — snug reinterprets, it does not edit the repo.
	host, err := os.ReadFile(mcpPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(host) != body {
		t.Errorf("the host's .mcp.json changed during the run:\nwant %s\ngot  %s", body, host)
	}
}

func keysOf(m map[string]any) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// between returns the text strictly between two markers, or "" if either is
// missing. The markers are echoed by the payload rather than assumed, so a
// sandbox that never started yields "" and the caller fails with that reason
// rather than parsing snug's own diagnostics as a JSON file.
func between(s, begin, end string) string {
	i := strings.Index(s, begin)
	if i < 0 {
		return ""
	}
	rest := s[i+len(begin):]
	j := strings.Index(rest, end)
	if j < 0 {
		return ""
	}
	return strings.TrimSpace(rest[:j])
}

// TestADanglingSymlinkAtAProjectedNameWritesNothingToTheHost is the end-to-end
// half of the red team's finding on issue #460's branch, and the only half that
// can observe the harm: the artifact appeared in the HOST tree, so the
// assertion has to be made on the host after a real run.
//
// Before the fix: a target shipping `ln -s NOTES.generated .mcp.json` left a
// 0-byte read-only NOTES.generated beside it, created by bwrap during setup,
// before the payload ran. os.Lstat said the name existed, HostDestExists was set
// on the strength of that, and rejectGeneratedOntoHost (issue #186) skipped its
// check — while bwrap followed the link Lstat had not.
func TestADanglingSymlinkAtAProjectedNameWritesNothingToTheHost(t *testing.T) {
	budget(t)
	requireSandbox(t)
	proj, _ := target(t)

	if err := os.Symlink("NOTES.generated", filepath.Join(proj, ".mcp.json")); err != nil {
		t.Fatal(err)
	}
	home := t.TempDir()
	if err := os.MkdirAll(filepath.Join(home, ".claude"), 0o755); err != nil {
		t.Fatal(err)
	}

	// NOT mustRun: the payload must NOT run. snug refuses before the sandbox
	// exists, because it cannot reinterpret through a link and running anyway
	// would hand Claude Code a file snug did not author.
	res := runEnv(t, baseEnv("HOME="+home), []string{"-p", "@claude"}, proj, `echo RAN`)
	if res.ran {
		t.Errorf("the payload ran with a symlink at .mcp.json; snug must refuse rather than "+
			"leave the file un-reinterpreted:\n%s", res.out)
	}
	if res.code == 0 {
		t.Errorf("snug exited 0 with a symlink at .mcp.json:\n%s", res.out)
	}
	if !strings.Contains(res.out, "regular file") {
		t.Errorf("the refusal does not name what is wrong:\n%s", res.out)
	}

	// THE HARM, asserted where it landed. This is the assertion the unit test
	// cannot make: no mount was performed, so nothing was created beside the link.
	created := filepath.Join(proj, "NOTES.generated")
	if _, err := os.Lstat(created); err == nil {
		t.Errorf("%s exists on the host after the run. snug wrote the host during setup — "+
			"the file the symlink pointed at, created by bwrap following a name os.Lstat "+
			"had only looked at (issue #186's guard, defeated through its own exemption)",
			created)
	}
}
